flatpak/flatpak

- tests/libtest.sh
- tests/test-builder.sh
- tests/test-run.sh
---
For example, on an Ubuntu live system, we can run bwrap (the kernel
allows unprivileged user namespace creation by default) but we cannot
write xattrs in /var/tmp (because everything mutable is tmpfs).
This is very similar to a check I added to ostree: https://github.com/ostreedev/ostree/commit/3e3755c497bd85e22b01829c5715119d46394687
> Skip tests that make a repository if /var/tmp lacks user xattrs

- app/flatpak-builtins-build.c
- builder/builder-manifest.c
...so use the == -1 idiom as already used in common/flatpak-run.c
(another fix would be to drop the if completely, as exec* doesn't
return on success)
> exec* returns -1 on error

- builder/builder-module.c
- doc/flatpak-builder.xml
flatpak-builder does a lot of commandline construction, using the module names and other data from the .json file to construct options, filenames, etc. There's a ton of possible errors that can happen if the module name contains spaces or slashes.
> prevent confusing errors

- builder/builder-manifest.c
When the sdk is not specified in the manifest, we get a confusing
error from running flatpak info with an invalid commandline.
Avoid that by checking for the the sdk string beforehand.
> builder: Avoid a confusing error

- Makefile.am
- tests/Makefile.am.inc
According to the FHS, applications which place internal libraries in
/usr/libexec should not also use /usr/lib for this purpose:
http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html
As several flatpak helpers are already installed in libexecdir, move the
bwrap helper to /usr/libexec/flatpak/bwrap.
> bwrap: Move to under libexecdir

- autogen.sh
It's minor but hey, warnings stand out.
> build: autogen.sh: Use mkdir -p to suppress warning

- common/flatpak-dir.c
This pull request adds commits to warn the user about a common cause of the remote summary being unavailable. The previous error message left me scratching my head to some degree.
Also fixes the use of a NULL ptr in `cached_summary_new`
> Warn on adding invalid remote

- doc/flatpak-builder.xml
Document that app-id is the same as id, and fix a case
of suffixed<>suffix confusion.
> Small additions to flatpak-builder(1)

- builder/builder-manifest.c
Add a message for the 'rewriting the desktop file' step.
This helps in providing context for error messages when something
goes wrong.
> Add another status message to flatpak-builder

- common/flatpak-run.c
In a minimal environment (like the one where we run installed-tests
in Debian), we might not have /usr/share/fonts.
---
This is highly unlikely "in real life", but it could conceivably happen if someone is deploying non-GUI Flatpak bundles (webapps? proprietary command-line tools? game servers?) on a headless system.
I'm currently applying this patch in Debian to make the installed-tests pass, but if you would prefer I can give flatpak a hard dependency on `fontconfig-config` (which itself depends on some reasonable fallback fonts) or on a fallback font like `fonts-dejavu-core`.
> flatpak-run: don't fail if there are no system fonts

- configure.ac
- system-helper/Makefile.am.inc
I tried to fix up the gnome-software build in gnome-apps-nightly, but it still doesn't work - it uses the flatpak libraries, so it has flatpak as dependency. flatpak configure now requires polkit, so we end up pulling in mozjs for polkit, which is really to much when we just want libflatpak.
I would suggest either a configure flat to turn off the building of the system helper, or separating out the library.
> library-only build

- common/flatpak-dir.c
This causes a compiler warning.
> Fix a case of NULL<>FALSE confusion

- doc/flatpak-builder.xml
Since we are doing open source, we should put some consideration into preserving that aspect. Can we make the recipe that an app or runtime was built from easily available from the repo ? Ideally in a form that makes it easy to reproduce the build.
> consider sources

- document-portal/xdp-main.c
This way we return a critical warning in the unlikely event of a write
error.
> Silence compiler warning about unused result of write()

- document-portal/xdp-main.c
The xdp-impl-dbus.h header no longer exists - it came from an
earlier version of the document commands branch where I introduced
a separate interface. Just drop the include, it is not needed.
> Fix the build

- doc/flatpak-document-export.xml
- doc/flatpak-document-info.xml
- doc/flatpak-document-list.xml
- doc/flatpak-document-unexport.xml
Revise the man pages for the new document commands a bit, using
'document id' consistently, and adding cross references among them.
> Clarify the documentation a bit

- doc/flatpak-builder.xml
builddir is actually boolean, not string.
> Fix builddir option type in flatpak-builder documentation

- Makefile.am
- common/flatpak-run.c
- tests/Makefile.am.inc
- tests/libtest.sh
* If the document portal is unavailable because we don't have working FUSE, setting fatal warnings means that we will fail all tests. Downgrade that to a message. (Alternatively, we could make the `fatal-warnings` flag conditional on having working FUSE.)
* My fixes for the dist tarball in 0.6.6 wrongly caused the `installed-tests` to include scripts that are actually not tests. Move them to the correct `extra_scripts` so they are not run as tests, which won't work.
* Run tests with a private `XDG_RUNTIME_DIR` so they can coexist with the user's "production" copy of the document portal.
> Various test fixes

- doc/flatpak-run.xml
I was trying to debug some problem with a sandboxed app by using the sdk as runtime, and launching the app in gdb inside the sandbox. But gdb doesn't react to ^C, and setting breakpoints doesn't work.
I suspect that this warning might be related:
(gdb) r
Starting program: /app/bin/portal-test 
warning: Error disabling address space randomization: Operation not permitted
> gdb in sandbox doesn't work

- Makefile.am
- app/flatpak-builtins-build.c
- common/flatpak-dir.c
- configure.ac
- tests/Makefile.am.inc
This lets distributors share a system copy of bubblewrap (>= 0.1.0)
between Flatpak and any other projects that benefit from it, if they are
careful to keep new versions in sync. The default is still to use the
bundled submodule, ensuring compatibility and simplifying dependencies.
Enable $PATH search everywhere that runs bwrap, so that $BWRAP doesn't
necessarily need to be a fully-qualified path.
> Add BWRAP and --with-system-bubblewrap configure arguments

- tests/test-basic.sh
One of the variations tested on Debian's reproducible build
infrastructure is that the second build is done in a French locale.
This test fails there, because it doesn't see "Usage:" in the help.
> test-basic: do not fail in non-English locales

- lib/flatpak-installed-ref.c
The latest_commit string needs to be freed.
> Fix leak in flatpak-installed-ref

- common/flatpak-run.c
- doc/flatpak-run.xml
This is not intented for normal use, but it can be useful in cases where
we don't have a running session and sandboxing is not strictly required.
Fixes https://github.com/flatpak/flatpak/issues/170
> flatpak-run: Add a new --no-desktop option to prevent creation of cgroups

- configure.ac
- document-portal/xdp-main.c
> Allow building on GLib 2.40 or older

- builder/builder-manifest.c
This commit makes flatpak-builder print the flatpak build-finish command
it constructs before executing it in a subprocess, which matches the
behavior for flatpak build-init and flatpak build.
> builder: Print a message when running flatpak build-finish

- common/flatpak-utils.c
When trying to extract icons to regenerate the appstream, we are looping
over the entire file every time, instead of only trying to copy icons
for the application ID we're looking at the moment.
This is most likely benign, but it causes a lot of "Error copying icon:
No such file or directory:" spew when calling flatpak build-update-repo.
> utils: fix double loop when extracting icons for appstream

- doc/flatpak-build-export.xml
- doc/flatpak-build-init.xml
- doc/flatpak-build-sign.xml
- doc/flatpak-build-update-repo.xml
- doc/flatpak-builder.xml
Some of the options do not explicitly say they can be used multiple
times even though it's clear from the code that they can. This commit
fixes that by saying so in the manpages.
> docs: Clarify which options can be used multiple times

- app/flatpak-builtins-run.c
- common/flatpak-run.c
- common/flatpak-run.h
- configure.ac
- doc/flatpak-run.xml
Systemd does this for services it runs. In fact, for a while I thought we would just inherit this via activation: if your app is dbus activatable, dbus would forward the activation to systemd, which would set up journal redirection for flatpak, from where it gets 'inherited' by the sandbox. But a) this only works if dbus actually forwards the activation (for which you need to install not just a dbus service file but also a systemd unit), and b) it is probably a little too indirect and accidental.
I think we should do the same thing systemd does when we set up the sandbox. There should be a way to opt out of this in the manifest, and in the flatpak run commandline.
> Set up logging to the journal

- .gitignore
- Makefile.am
- dbus.service.d/flatpak.conf.in
flatpak currently installs a gdm env.d and a bash profile.d file to
ensure XDG_DATA_DIRS is set to the right value.  Neither is sufficient
when the dbus daemon is activated as a system --user service.
This commit adds a dbus service file snippet to frob its environment
variable for that case.
> install dbus systemd service file snippet

- app/flatpak-builtins-list.c
- doc/flatpak-list.xml
Works for install though. Having --arch=all would be useful to see what is physically installed.
> --arch doesn't work for "list"

- tests/libtest.sh
dbus-launch is X11-specific and contains a lot of legacy code to
support X11 autolaunching. It should not be part of the Wayland
(and/or Mir) future.
Start a dbus-daemon directly instead.
> libtest: replace dbus-launch with dbus-daemon

- Makefile.am
The !WITH_SYSTEM_BWRAP conditional was too broad here.
> build: run install-test-data-hook even if using system bwrap

- builder/builder-source-git.c
- doc/flatpak-builder.xml
Currently to use a local copy of a git repo you have to specify the url
as "file:///path/to/repo". This commit allows you to specify a path directly
as "/path/to/repo", which is faster and more space-efficient because
git-clone will hardlink the objects rather than copying them.
> builder: Allow git sources to be specified as paths

- app/flatpak-builtins-build.c
"non-devel runtime" isn't an expression in the Flatpak vocabulary, so
explain what it really does.
> build: Better description for --runtime option

- builder/builder-source-archive.c
Substituting into a shell command-line without escaping is a bad idea.
If the argument is attacker-controlled, it's a security vulnerability;
if the argument is legitimate-user-controlled (as I think it is here)
it's merely wrong.
We could escape the filename with g_shell_quote(), but it's more
straightforward to take advantage of the shell's argument processing.
The first positional parameter (if given) is $0, and the rest are $@.
---
This is untested (do we have a test-case for RPM-based Flatpaks?) but should work.
> unrpm: prevent shell injection

- README.md
Use css to align the Flatpak image on the Readme.md since markdown doesn't allow tweaking the positioning.
Sorry, I couldn't leave it like this :)
> Readme.md: align image

- common/Makefile.am.inc
- document-portal/Makefile.am.inc
- permission-store/Makefile.am.inc
If flatpak is built from a separate build directory, code generation fails because the directory structure is not in place. Create the necessary directories before code generation.
> Create directories before attempting to generate code into them

- builder/builder-manifest.c
- builder/builder-module.c
- builder/builder-source-shell.c
- common/flatpak-run.c
- common/flatpak-utils.c
This commit makes flatpak print a debug message (which only appears to
the user if the -v option is used) whenever a subprocess is launched.
This should make debugging easier, both for flatpak users and
developers.
> utils: Print a debug message when launching subprocesses

- common/flatpak-utils.c
Two optimizations to the summary regeneration:
* Only operate on flatpak refs
* Only collect data once per revision
This makes a pretty big difference on my test repo with the following setup that's similar to our production Endless repos.
```
$ for ref in `ostree refs --repo ~/tmp/ostree/apps | sort`; do echo -n "$ref: "; ostree rev-parse --repo ~/tmp/ostree/apps $ref; done
app/org.gnome.Gnote/x86_64/eos3: 87ff33882acb8e2cf5665f6dc20cada1ac1f0d8639155d9b12389a17966094a3
app/org.gnome.Gnote/x86_64/eos3.0: 87ff33882acb8e2cf5665f6dc20cada1ac1f0d8639155d9b12389a17966094a3
app/org.gnome.Gnote/x86_64/master: 2ccbe50bb1325257e8a88dceacb69c42af253e18d80b9f0171a6627d33c52963
app/org.wesnoth.Wesnoth/x86_64/eos3: 6cafec1bedbe5b9c14e03bc7b026fb1ece533aca0043b3154fd8a29d624379af …
```
> Speed up summary regeneration

- dbus-proxy/flatpak-proxy.c
Common bit-twiddling to remove the multiply and divide for realignment.
> dbus-proxy: alignment bit-twiddling to remove multiple and divide

- session-helper/flatpak-session-helper.c
To prevent crashers like the following:
Starting program: /var/tmp/flatpak/libexec/flatpak-session-helper
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed8a9700 (LWP 7893)]
[New Thread 0x7fffed0a8700 (LWP 7894)]
[New Thread 0x7fffec439700 (LWP 7895)]
session-helper/flatpak-session-helper.c:176:20: runtime error: load of null pointer of type 'const gchar'
Thread 1 "flatpak-session" received signal SIGSEGV, Segmentation fault.
0x000000000040d6ce in handle_host_command (object=0x62100001ab90,
invocation=0x61d000014dc0, arg_cwd_path=0x0, arg_argv=0x602000003dd0,
arg_fds=0x61900000b130, arg_envs=0x61900001d2a0, flags=1)
at session-helper/flatpak-session-helper.c:176
176   if (*arg_argv[0] == 0)
(gdb)
> flatpak-session-helper: Check for arg_argv being NULL

- app/flatpak-builtins-build-sign.c
Currently, the message seems to be wrong.
> build-sign: fix short help message

- builder/builder-source-git.c
Today I tried building a nightly Blender, and feeling way too courageous I tried building it against a nightly Boost.
Boost is full of submodules, and its submodules also have submodules. And some of them probably also have submodules, and... But some of these do bad things.
For example, Boost's submodule odelint has a `.gitmodules` file, which lists a submodule at the `doc` path. But that path isn't a `gitlink`, it's a regular folder.
That's because the `doc` path used to be a submodule, but then [the submodule got removed some 5 years ago](https://github.com/boostorg/odeint/commit/e719fbc35d805654ad5583cafc1d89e9c18bdd5d) and made into a proper folder with documentation inside.
However the `.gitmodules` file still lists it on the master branch (it only got removed on the develop branch …
> Improve git submodules... again

- session-helper/flatpak-session-helper.c
Make sure we let the caller know we handled the message immediately after
sending our error reply.
> session-helper: return after sending DBus error

- app/flatpak-builtins-build-export.c
These get all mixed up into one line when using build-export
> build-export: Add missing \n to g_print calls

- builder/builder-manifest.c
If this is not checked, flatpak-builder might crash like this:
Starting program: /var/tmp/flatpak/bin/flatpak-builder -v --force-clean
-v --ccache --repo=/tmp/fb.repo --gpg-sign=tobiasmue@gnome.org
/tmp/fpbuilder org.gnome.Sdk.ASan.json
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-
gnu/libthread_db.so.1".
[New Thread 0x7ffff139c700 (LWP 20407)]
Thread 1 "flatpak-builder" received signal SIGSEGV, Segmentation fault.
0x00007ffff697c770 in g_str_hash () from /lib/x86_64-linux-
gnu/libglib-2.0.so.0
(gdb) bt
from /lib/x86_64-linux-gnu/libglib-2.0.so.0
from /lib/x86_64-linux-gnu/libglib-2.0.so.0
expanded=expanded@entry=0x7fffffffdae0, names=names@entry=0x690a40,
error=error@entry=0x7fffffffdc08) at builder/builder-manifest.c:175 …
> builder: check for name being defined in expand_modules

- session-helper/flatpak-session-helper.c
This was using the "from" fd from the fd_map, which will have already been closed by time we reach this portion of the child setup.
Tracking the movement of FDs while resolving the remappings is rather tedious and error prone, so just locate the final fd before calling the ioctl() in child setup.
This fixes the following warning when creating a terminal with Vte.
```
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
```
> session-helper: use proper fd with ioctl() for tty setup

- doc/flatpak-build-finish.xml
This adds a short bit of text on what the --allow=devel build-finish
argument does (which allows access to perf and ptrace syscalls).
> doc: add blurb about what --allow=devel does

- common/flatpak-run.c
The kernel keyring is currently accessible to sandboxed flatpak applications.  This is a problem because it means that those applications can, for instance, access the kerberos credentials of a user and impersonate the user, or read any secrets stored on the user's keyrings.  The kernel keyring subsystem has no notion of namespaces at the moment, so there's no way to "unshare" access to the keyrings used in the outside session from the sandbox.  Since the sandboxed user runs with the same UID as the outside, it can get full access to everything.
Aside from direct access to user keys, there's also the problem of indirect access to logon keys via kernel services (mainly filesystem access, I think, but other things. too). I think those are less of a concern, because access to those keys can …
> flatpak should close up access to kernel keyring

- app/flatpak-builtins-build-export.c
While creating first project, I forgot to create "export/" dir. Why not directly mention that `.../export` dir is missing?
> More decriptive "error: Build directory ... not finalized"

- app/flatpak-builtins-build.c
When running flatpak build on a non-existing directory, the error message is not particularly helpful.
For my version, it behaves the following way:
```
$ flatpak build    /tmp/fpbuilder echo foo
error: Error opening file: No such file or directory
$
```
It would have helped me if it said something like   "The build directory >>/tmp/fpbuilder<< seems to not exist!  error: Error opening file: No such file or directory".
With strace I found out that it tries to open() /tmp/fpbuilder/metadata. When creating (i.e. touching) that file, flatpak prints "error: Key file does not have group 'Application'" which again, could be more helpful by at least including the filename in question.
> error message for flatpak build on non existing directory could be improved

- common/flatpak-run.c
- common/flatpak-run.h
- doc/flatpak-build-finish.xml
- doc/flatpak-run.xml
This adds a new `multiarch` feature which allows bundling e.g. 32-bit binaries to be run in a `x86_64` environment. By default, the seccomp filter is configured to allow only the native architecture. When the `multiarch` feature is enabled, the filter will be configured to allow running binaries of additional architectures supported. For `x86_64`, this allows `x86` 32-bit binaries; and for `aarch64`, allows 32-bit `arm` binaries.
Application bundles can use the feature e.g. in order to ship 32-bit binaries alongside with a mostly-64-bit application. This is particularly interesting when for applications that might launch themselves prebuilt programs for which 64-bit versions do not exist. For example, the Steam application is available as a 64-bit executable, but some of the games …
> Support mixed (multilib/multiarch) binaries in Flatpaks

- builder/builder-utils.c
It is allowed to make a self-executable zip, it will then be an ELF file
on Linux. The problem is that the current stripping code somehow breaks
that file (i.e. ./file.zip doesn't work anymore after stripping).
Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>
> flatpak-builder: don't strip zip files

- app/flatpak-builtins-install.c
Otherwise we'll be always trying to force the installation from the
default branch for a repo, regardless of whether the app being
installed is available for that branch.
> Only override the default branch, if needed, after splitting a ref

- app/flatpak-builtins-add-remote.c
The g_key_file_load_from_bytes() function was added in GLib 2.50, and that
is too high as flatpak wants to support centos7/rhel7, which is now in 2.42.
> Use g_key_file_load_from_data() instead of g_key_file_load_from_bytes()

- common/flatpak-dir.c
- common/flatpak-dir.h
- common/flatpak-utils.c
- common/flatpak-utils.h
This adds basic support for using extensions unmaintained by flatpak.
See #167
> Add support for unmaintained extensions

- common/flatpak-dir.c
Without this patch flatpak-remote-add (and anything else that uses this
section of code) segfaults if org.freedesktop.Flatpak.SystemHelper is
unavailable because it tries to cast an integer to a GDbusProxy.
> common: Don't segfault w/o org.freedesktop.Flatpak.SystemHelper

- common/flatpak-dir.c
It turns out that flatpak_dir_remote_fetch_summary can return TRUE,
yet leave summary_bytes NULL. The code further down does not deal
gracefully with summary_bytes being NULL, so error out early instead
of crashing.
> Avoid a crash during update --appstream

- builder/builder-source-git.c
This commit checks if <revision>:.gitmodules exists in the repo before
calling git-show on it, so an error message doesn't show up in the
program's output.
> builder: Check if .gitmodules exists before showing it. Fixes #366

- po/POTFILES.in
A file is missing from po/POTFILES.in, making it untranslatable.
> Update POTFILES.in 161101

- common/flatpak-dir.c
- system-helper/org.freedesktop.Flatpak.policy.in
Add logic in flatpak_dir_update_remote_configuration() so that the step of
configuring the local remotes after fetching the required date from the
server's summary file is performed via the system helper when present.
Note this will require the user authorizing the action by introducing
the password explicitly when asked, but this is necessary as updating
the local remotes configuration is something that can't be allowed
without explicit authentication.
> Integrate flatpak_dir_update_remote_configuration() with the system helper

- builder/builder-manifest.c
- doc/flatpak-builder.xml
In Builder with [these](https://bugzilla.gnome.org/show_bug.cgi?id=773764) patches, flatpak-builder fails when there aren't any git commits yet, which seems unnecessary. Is there any use case that would require the ignored modules to be downloaded?
> builder: Don't download modules that won't be built

- tests/Makefile.am.inc
We should append to it, but not totally replace it, or things like
running test under jhbuild will not work properly.
> tests: don't stomp on LD_LIBRARY_PATH

- app/flatpak-builtins-info.c
- common/flatpak-run.c
When no session helper is available (e.g. running flatpak run from a
socket-activated service unit), we need to be extra careful before
making these two files appear inside the sandbox. Otherwise, if they
are not reachable on the host system (or just symlinks to non-existent
targets), flatpak won't be able to create the sandbox, which will fail
due to a "No such file or directory error".
https://github.com/flatpak/flatpak/issues/409
> Extra checks mounting /etc/{resolv.conf|localtime} without session helper

- builder/builder-module.c
- doc/flatpak-builder.xml
An example project I tested against can be found here: https://github.com/TingPing/flatpak-meson-test/blob/master/org.gnome.Twitch.json
Specifically:
```json
{
"name": "gnome-twitch",
"buildsystem": "meson",
"builddir": true,
"sources": [{
"type": "git",
"url": "https://github.com/vinszent/gnome-twitch.git"
}]
}
```
To really be useful this depends upon the Sdks adding `ninja` and `meson`.
Closes #400
> builder: Add buildsystem option and meson support

- doc/flatpak-build-export.xml
The repo-update command was renamed to build-update-repo.
> Update the flatpak-build-export docs

- system-helper/org.freedesktop.Flatpak.rules.in
As it's already done for installing an app or runtime, we shouldn't ask
privileged users to authenticate in order to remove them.
> system-helper: Do not ask for password when removing apps/runtimes

- app/flatpak-builtins-install.c
So we avoid an error message like:
error: Can't load uri XXXXUnacceptable TLS certificate
> install: fix error message

- po/POTFILES.in
app/flatpak-oci.c is no longer in the tree and causes a build failure when updating potfiles.
> po: update POTFILES.in

- common/flatpak-dir.c
The old '.install' one was probably too specific, so let's move it to
a more generic (and common) extension before making the release.
> Change file extension for installations configuration files to '.conf'

- doc/flatpak-info.xml
- doc/flatpak-install.xml
- doc/flatpak-list.xml
- doc/flatpak-make-current.xml
- doc/flatpak-override.xml
- doc/flatpak-remote-add.xml
- doc/flatpak-remote-delete.xml
- doc/flatpak-remote-list.xml
- doc/flatpak-remote-ls.xml
- doc/flatpak-remote-modify.xml
- doc/flatpak-uninstall.xml
- doc/flatpak-update.xml
- doc/flatpak.xml
Documented the --installation parameter for all the CLI commands
that accept it, and added a small generic description in the main
flatpak document.
> Add bits to document the multiple installations feature

- doc/flatpak-builder.xml
Found by Debian's Lintian tool.
> flatpak-builder(1): fix typo

- builder/builder-manifest.c
Currently it can silently continue if an included file is invalid or missing.
I didn't see any way to propagate up the error during parsing so it is just fatal.
> builder: Error when failing to include modules

- .gitignore
flatpak-flatpakref.5 and flatpak-flatpakrepo.5 were not included in .gitignore.
> Add all man5 files to .gitignore

- common/flatpak-utils.c
The main loop that is initiated while the extra data is being downloaded
needs a different context to be the thread-default one, otherwise the
operations just hang when running from a different thread.
> Fix downloading extra data when run from a different thread

- configure.ac
Before this change, configure script looked for them only in $includedir, which doesn't work well with jhbuild.
Fixes #471
> configure: Look for the libdwarf headers also in /usr/include/libdwarf

- Makefile.am
- system-helper/flatpak-system-helper.service.in
Otherwise we can see in the log that update-mime-database will complain
about it not being set when installing an application using the system
helper.
> system-helper: make sure to run with XDG_DATA_DIRS set

- tests/Makefile.am.inc
- tests/testlibrary.c
* testlibrary crashed because it failed to NULL-terminate a GStrv
* testpython.py was not installed +x, causing a "permission denied" error when running the test that uses it as an installed-test
> Fix some test issues

- Makefile.am
- app/flatpak-builtins-list.c
- app/flatpak-main.c
- builder/builder-main.c
- builder/builder-source-bzr.c
- builder/builder-source.c
- common/flatpak-dir.c
- common/flatpak-run.c
- configure.ac
- permission-store/xdg-permission-store.c
- system-helper/Makefile.am.inc
- system-helper/flatpak-system-helper.c
- Add `--with-dbus-config-dir` to override the dbus `system.d` directory for newer dbus versions
- Add `--with-profile-dir` to support using alternative profile environment directory for vendor files
- Cleanup some compiler warnings whereby the cleanup variables were not initialised.
> Add configure options for stateless distros & fix warnings

- Makefile.am
- system-helper/flatpak-system-helper.service.in
If EXTERNAL_INSTALL_DIR wasn't defined (which is likely, since nothing
in the build system does), then we would tell the system helper
to search /exports/share, which is not Flatpak's territory
(but is a semi-commonly-used path for site-specific NFS shares,
which might have contents that are inappropriate to search here).
Installations that do define an external installation directory
(Endless OS?) can easily override the Environment to include it
by placing a drop-in in
/etc/systemd/user/flatpak-system-helper.service.d/external.conf
or similar.
---
cc @cosimoc: I assume this was unintended?
> flatpak-system-helper: remove dangling reference to EXTERNAL_INSTALL_DIR

- app/flatpak-builtins-install.c
- common/flatpak-dir.c
- common/flatpak-dir.h
- lib/flatpak-installation.c
Before this commit
$ flatpak install --arch someArch --from some.flatpakref
Would completely ignore the arch argument and only install for the
default flatpak architecture. Since flatpakref files don't include
an arch field, there's no reason we can't attempt to install the
arch specified on the command line.
https://github.com/flatpak/flatpak/issues/406
> install: handle arch when installing from a flatpakref

- builder/builder-module.c
- doc/flatpak-builder.xml
Please don't yell too much at me, I didn't touch C in ages. Note that for some reason it currently doesn't work as expected, CMake returns `CMake Error: Could not create named generator 'Ninja'` or `CMake Error: Could not create named generator 'Unix Makefiles'`. I looked at debug log and ran exactly the same command:
```flatpak build --nofilesystem=host --filesystem=/home/bp/dev/flatpak-ppsspp/.flatpak-builder/build/ppsspp-12 --bind-mount=/run/build/ppsspp=/home/bp/dev/flatpak-ppsspp/.flatpak-builder/build/ppsspp-12 --build-dir=/run/build/ppsspp --bind-mount=/run/ccache=/home/bp/dev/flatpak-ppsspp/.flatpak-builder/ccache --env=PATH=/run/ccache/bin:/app/bin:/usr/bin --env=CCACHE_DIR=/run/ccache /home/bp/dev/flatpak-ppsspp/builddir cmake -DCMAKE_INSTALL_PREFIX:PATH='/app' -G'Unix …
```
> builder: add cmake-ninja support

- session-helper/flatpak-session-helper.c
Just because stdout/stderr happen to be going to a terminal doesn't
necessarily mean that we want the command launched by HostCommand
to take ownership of the terminal - in the case where 'flatpak run'
is launched from a terminal, stderr will typically be left pointing
to the terminal for any command. In that case the terminal already
has a controlling process, and TIOCSCTTY will fail; avoid scary
messages by making the failure only a g_debug()
> flatpak-session-helper.c: Make failure of TIOCSCTTY a g_debug()

- README.md
I removed an extra bracket that was presumably made when adding the hyperlink.
> Remove extra bracket from README.md

- common/flatpak-utils.c
So far, the installation of external apps can only be cancelled
before flatpak starts downloading the extra data, as there's no
cancellable being passed to g_input_stream_read_async().
This fixes that problem, making it possible to cancel installs
from GNOME Software regardless of the installation stage.
Fixes: https://github.com/flatpak/flatpak/issues/559
> Allow cancelling the downloading process for extra data

- Makefile.am
- scripts/flatpak-bisect
The CLI is pretty similare to the `git bisect` one and works as follow:
$ flatpak-bisect org.app.App start # Update application and get the history
$ flatpak-bisect org.app.App bad # Sets current commit as first bad commit
$ flatpak-bisect org.app.App checkout GoodHash # Checkout the first known good commit
$ flatpak-bisect org.app.App good # Sets GoodHash as first good commit
... Here it starts bisection and checkouts a commit on the way, the user should launch the
app to check if the commit is good or bad and run:
$ flatpak-bisect org.app.App good # if commit is good
$ flatpak-bisect org.app.App bad # if commit is bad
flatpak-bisect will tell when the first bad commit is found.
Fixes https://github.com/flatpak/flatpak/issues/530
> scripts: Add a script to allow bisecting failures

- app/flatpak-builtins-run.c
Currently if you pass flatpak-run an app that's not installed it prints
an error message to that effect, but if you pass it a runtime that's not
installed (and use the full ref format, e.g.
runtime/org.gnome.Sdk//master) it prints this message and crashes:
```
(flatpak run:15104): GLib-CRITICAL **: g_propagate_error: assertion 'src != NULL' failed
flatpak:ERROR:app/flatpak-main.c:394:flatpak_run: assertion failed: (success || error)
```
This commit makes flatpak print the appropriate error message, while
still printing an "app not found" error if the user didn't specify
whether the ref is an app or runtime.
> run: Print an error for runtimes that aren't installed

- doc/flatpak-run.xml
The ability to use flatpak-run to enter into a shell in a runtime was
added in flatpak 0.6.13 but the docs weren't updated to reflect that.
This commit updates the flatpak-run documentation to explain the
functionality.
> doc: Mention that flatpak-run can be used with runtimes

- app/flatpak-builtins-build-commit-from.c
- app/flatpak-builtins-build-export.c
- app/flatpak-builtins-build-import-bundle.c
- app/flatpak-builtins-repo-update.c
- common/flatpak-utils.c
- common/flatpak-utils.h
This allows us to build reproducable repo summaries, for instance in gnome-software self tests.
> Allow specifying an ISO-8601 timestamp when using build-export

- profile/flatpak.sh.in
Otherwise it will be impossible to run flatpak apps from desktop menus.
This issue can happen if another app (e.g. snapd) wants to add custom
folders to XDG_DATA_DIRS through /etc/profile.d
If XDG_DATA_DIRS is empty or unset, define it as before.
Fixes #606
> Append flatpak data dirs if XDG_DATA_DIRS is already set

- profile/flatpak.sh.in
Avoid setting a temporary variable flatpak_dirs which, while not
exported to the environment, would still be defined as a
shell "parameter" (variable) in the login shell itself.
Consistently put the Flatpak directories before other XDG_DATA_DIRS,
rather than putting them last if XDG_DATA_DIRS happens to be already
set.
Expand XDG_DATA_HOME if necessary, rather than assuming it will
always be ~/.local/share.
I don't know exactly which shells source profile.d, but it's possible
that one of them might only implement POSIX test syntax, so prefer
[ x = y ] over [ x == y ].
Fix some insufficient quoting that could have gone wrong if
XDG_DATA_DIRS somehow contained spaces.
Signed-off-by: Simon McVittie <smcv@debian.org>
---
This is based on the assumption that consistently prepending is the …
> Improve and simplify profile snippet

- doc/flatpak-metadata.xml
A bunch of keys got added in code recently, and the
flatpak-metadata(5) man page has not been kept up-to-date.
> document more metadata keys

- builder/builder-manifest.c
The --require-version option works for build-finish but not build, so
don't pass it along when using a manifest to build.
> builder: Don't pass --require-version along to build

- common/flatpak-dir.c
Now that Ostree has a 'bare user only' mode for repositories, we should
use it.
This allows installing Flatpak run times inside different Docker layers.
Original patch by: Alexander Larsson <alexl@redhat.com>
Tested-by: Emmanuele Bassi <ebassi@gmail.com>
> Use ostree's BARE_USER_ONLY flag

- app/flatpak-main.c
This option takes an argument, so specify an argument
name in the GOptionEntry to make the --help output
come out right.
> Fix --help output for --installation

- doc/flatpak-docs.xml.in
- doc/xmlto-config.xsl
We have a docbook file that generates html versions of
the man pages. Keep it updated.
> doc: Include all man pages in html

- common/flatpak-run.c
WAYLAND_DISPLAY can be other than "wayland-0" for various reasons, such
as using a custom Wayland display server or the session display server
using a custom display name.
Note that for xdg-desktop-portal to support showing portal windows, the
xdg-desktop-portal service MUST use the same WAYLAND_DISPLAY.
---
I needed this to be able to debug a mutter crash where the reproducer was a flatpak app, so that I could make that app use the display server instance I was debugging. There are probably other reasons for WAYLAND_DISPLAY being something other than "wayland-0" where flatpak should till work though.
> run: Handle non-default WAYLAND_DISPLAY

- builder/builder-context.c
My understanding is that rofiles-fuse is just an optimization,
and we support building without it anyway (using --disable-rofiles-fuse).
So, instead of failing the build, we can just not use rofiles-fuse
if it is not present on the system, which seems to be the case on
some OSes, we've seen this reported from Debian and Arch.
> Don't fail the build if rofiles-fuse is not available

- builder/builder-context.c
- builder/builder-context.h
- builder/builder-git.c
- builder/builder-git.h
- builder/builder-main.c
- builder/builder-manifest.c
- builder/builder-manifest.h
- builder/builder-module.c
- builder/builder-module.h
- builder/builder-source-archive.c
- builder/builder-source-bzr.c
- builder/builder-source-file.c
- builder/builder-source-git.c
- builder/builder-source-patch.c
- builder/builder-source-script.c
- builder/builder-source-shell.c
- builder/builder-source.c
- builder/builder-source.h
This adds a step to the build process to bundle
the module sources, used for building the flatpak,
as a runtime extension.
The sources can then be installed like the
debug or translation runtime.
This also adds an option to flatpak-builder
for specifying sources directories. One can specify
source dirctories with the use-sources argument. This
will skip the download part of the processing
and will extract the sources from the given sources
directory directly for further processing.
Those source directories do need the same
structure as the ones that flatpak-builder
creates during processing in .flatpak-builder
and which is also used in the exported sources
runtime.
> flatpak-builder: bundle module sources as runtime

- common/flatpak-run.c
Some previous g_set_error messages were related to 'unknown type', but this one about 'unknown location'. So it would probably be best to suggest 'valid locations', instead of 'valid types'.
> flatpak-run.c:  valid locations, not types

- common/flatpak-dir.c
- lib/flatpak-installation.c
After the introduction of linear progress reports based on
heuristics, Flatpak still couldn't make precise reports for
the extra-data field is contained in the commits. When we
were setting extra-data up, Flatpak didn't have the commits,
so it always failed.
Fix that by downloading the commits first, and then setting
up the extra-data fields.
flatpak/flatpak#609
> Ensure commits are available when checking for extra-data

- builder/builder-post-process.c
- common/flatpak-oci-registry.c
- common/flatpak-utils.c
- common/flatpak-utils.h
The new `glnx_regfile_copy_bytes()` is better than the previous
`flatpak_copy_bytes()` in that it will use reflink/sendfile if available.
More information in https://github.com/GNOME/libglnx/commit/3a4d0f4684f4653338c4756c8a1abfc6b5738467
> libglnx: Bump to latest master, use new file copy API

- app/flatpak-builtins-info.c
The installed size in the metadata refers to the full
extension. If we have subpaths, the actual installed
size may be much smaller. Unfortunately, it appears
hard to obtain the actual size, so just hint at this
fact by displaying a '<' before the size.
> Improve display of partial extension sizes

- doc/flatpak.xml
These are only the most 'official' looking ones.
One thing to consider: maybe rename the last one to FLATPAK_TRIGGERS_DIR ?
As it is now, it looks pointlessly different from the others.
> Document some environment variables

- scripts/flatpak-bisect
The script was using stdout=subprocess.STDOUT but the Popen
documentation does not mention this as a valid value.
An exception was being thrown when running flatpak-bisect <name> log:
OSError: [Errno 9] Bad file descriptor
> scripts: Fix flatpak-bisect log

- common/flatpak-table-printer.c
This was crashing when running flatpak list for
an empty installation.
> Don't crash if there's more titles than columns

- tests/test-webserver.sh
I was seeing this when trying to run flatpak's tests in ostree's CI:
https://github.com/ostreedev/ostree/pull/824
The race here is that the python process can still be writing to the output
while sed is reading it, and hence we'll find a difference on the next line.
Fix this by making a tmp copy of the file, which then both sed and cmp will
read consistently.
I'm not *entirely* sure this will fix the problem as I couldn't easily reproduce
the race locally, but I believe it at least fixes *a* race.
> tests: Fix race condition in tmp webserver

- doc/flatpak-metadata.xml
Differentiate between the 'extension point' (definition of
a place where extensions can be mounted) and the 'extension'
(a runtime matching an extension point).
> Use clearer terminology in docs about extensions

- common/flatpak-dir.c
Add X-Flatpak=true to rewritten desktop files.
Desktop files have multiple consumers, and this
makes it easier for them to know what to do.
> Add a marker to rewritten desktop files

- app/flatpak-builtins-install.c
I just saw a confusing error messages that looked like two error
messages just running into each other. Better to end the first
one with a colon when using g_prefix_error.
> Improve error wording

- common/flatpak-dir.c
- common/flatpak-dir.h
Flatpak relies on OSTree to report the progress, and
OSTree's progress report frequency fallbacks to 1 second.
Recently, however, OSTree received support for setting
custom update frequencies. Since it relies on GVariant
options, if the user has an older OSTree, it'll simply
be ignored.
This patch, then, makes Flatpak report progress every
100ms rather than the default value of 1 second.
flatpak/flatpak#609
> dir: Report progress more frequently

- common/flatpak-utils.c
Now that we have access to the total extra-data download size,
we can have much more precise progress reports by summing up
all the download sizes from OSTree and extra-data.
flatpak/flatpak#609
> Improve progress report calculation

- builder/builder-manifest.c
We have some extra conditions here that are not evident
from the rename-icon key in the manifest, so add some
verbose output to make it easier to figure out why an
icon is not renamed.
> Add some hints when icons are not found

- document-portal/xdp-main.c
As a file path, the mountpoint should probably be sent
as ay. Also, remove an extra level of gvariant wrapping.
> Correct mountpoint handling

- common/flatpak-run.c
Ideally it would always be a URI but it seems in real usage you do get normal paths.
> Handle file paths when forwarding uris

- builder/builder-module.c
Meson does not support builddir == srcdir, so there is no reason to
require developers to set "builddir" to true in their manifests, when we
can just do the right thing.
> Automatically use a separate builddir with Meson

- data/org.freedesktop.portal.Documents.xml
Mention the new flag and its functionality in the portal API
documentation.
> document store: Document as-needed functionality of AddFull

- common/flatpak-dir.c
g_variant_get_type_string() is like g_dbus_message_get_signature(),
not like G_VALUE_HOLDS_STRING(). Use g_variant_is_of_type() to get
the equivalent of G_VALUE_HOLDS_STRING(). This was correct on master,
but went wrong during backporting to 0.8.x.
> flatpak-dir: Check for variant containing string correctly

- tests/testlibrary.c
Failing tests produce much clearer diagnostics this way round.
> testlibrary: Call g_assert_no_error first

- common/flatpak-dir.c
Looking at the git history, this code originally retried on
some cases for pull, then stopped doing so, then a later commit
added code after it, which made it incorrect.
Just do an early return again and drop the `res` variable.
> dir: Ensure we return on pull error to avoid error-overwrites

- common/flatpak-dir.c
This goes into a big old topic about Unix homedir permissions; it's not uncommon
for general purpose OS vendors to have homedirs be 0755. In that case,
applications need to ensure confidentiality for data requiring it (classically
e.g. `~/.ssh`) by making the dirs `0700`.
While most of the data in the flatpak per-user dir probably isn't confidential
(debatably) we have a different issue; if container content includes suid or
world-writable files/dirs, then having that data accessible to other users
is obviously problematic.
We're going to fix flatpak/ostree to not create files with those modes
to begin with, but this simple fix closes off the attack route for
the per-user directory.
A different fix will be necessary for the system-wide repo.
See: …
> dir: Ensure ~/.local/share/flatpak is 0700

- common/flatpak-dir.c
This results in one ‘changed’ signal emission rather than several at
once.
> common: Use bulk OstreeAsyncProgress API for setting keys

- common/flatpak-dir.c
- tests/libtest.sh
- tests/test-run.sh
I'm not sure whether this is appropriate to merge into a stable-branch, but I'm going to need it as distro patches for as long as I'm shipping flatpak 0.8.x in Debian unstable, so I'd appreciate review even if you subsequently reject the PR.
This branch backports commits from master to fix the incompatibility with libostree 2017.7 discussed in <https://lists.freedesktop.org/archives/flatpak/2017-June/000723.html>.
It also makes the test for avoiding setuid files a little more tolerant: with libostree 2017.7, the setuid file gets its setuid permission masked out before Flatpak's check even sees it, so instead of asserting that the app fails to install, we have to assert that either the app fails to install or the setuid file loses its setuid bit. See the commit message for further details.
> [0.8.x] Compatibility with libostree 2017.7

- doc/flatpak-build.xml
This is not an option in flatpak-build; `flatpak build --version` prints
an unknown option error message.
> docs: Remove --version from flatpak-build docs

- builder/builder-manifest.c
- tests/Makefile.am.inc
- tests/test-builder.sh
- tests/test-runtime.json
Any build-args specified in the manifest should be used during the
cleanup and platform-cleanup stages. This is because if you are using
QEMU to build for another architecture, for example, you need to pass
--bind-mount in the build-args, and the bind mount also needs to be
present while running cleanup commands.
> builder: Use build-args during cleanup

- lib/flatpak-installation.c
The progress callback arguments in the Flatpak.Installation installation
and update methods are nullable, so we should annotate them as such.
> Add nullable annotations for progress callbacks

- dbus-proxy/dbus-proxy.c
- dbus-proxy/flatpak-proxy.c
*   dbus-proxy: Don't clear dbus_address twice
It's sufficient to g_free it, which we do further down finalize().
This is not a double-free, because we used g_clear_pointer(),
but it's redundant.
*    dbus-proxy: Make miscellaneous globals static
> Minor cleanup in dbus-proxy

- common/Makefile.am.inc
- document-portal/Makefile.am.inc
- permission-store/Makefile.am.inc
* build: Only run each instance of gdbus-codegen once
A rule of the form
foo.c foo.h: foo.in
some-generator --output=foo foo.in
is essentially equivalent to writing the same rule once for each target:
foo.c: foo.in
some-generator --output=foo foo.in
foo.h: foo.in
some-generator --output=foo foo.in
In a parallel build, this can result in some-generator being run more
than once with the same inputs and outputs, leading to unpredictable
results if the outputs are overwritten in-place by two parallel copies
(particularly if the generator does not use the standard atomic-writing
trick of writing out a temporary file and renaming it over the top of
the intended name, which gdbus-codegen does not).
gdbus-codegen happens to write the .h file before the .c file, so
use the real build rules to …
> Adjust gdbus-codegen Makefile rules

- common/flatpak-dir.c
This was accidentally introduced in a8ad3927 in advance of the LAN/USB
changes from PR #884 which will actually use it.
> common/dir: Drop unused variable

- tests/libtest.sh
- tests/testlibrary.c
The library test previously used the real ~/.cache, while the
library test and the shell-script tests would use the real ~/.config
to look up the XDG user-dirs.dirs. Other home-directory-related code
might have used the real $HOME.
As a general rule, build-time tests should not affect the real home
directory. Debian autobuilders run as a user whose home directory
does not exist, in order to catch packages whose build process could
affect or be affected by the contents of the home directory. This
caused testlibrary to fail when it tried to create that nonexistent
directory, which I think happened while trying to create ~/.cache.
> tests: Isolate tests from real home directory more thoroughly

- app/flatpak-builtins-build-export.c
Drop the spurious final argument.
> app/build-export: Fix gcc warning about too many arguments for printf

- app/flatpak-builtins-build-export.c
> app/build-export: Add missing N_() around a translatable option

- Makefile.am
- app/Makefile.am.inc
- app/flatpak-builtins-build-export.c
- app/flatpak-builtins-utils.c
- app/flatpak-main.c
- app/flatpak-transaction.c
- builder/Makefile.am.inc
- builder/builder-context.c
- builder/builder-git.c
- builder/builder-main.c
- builder/builder-manifest.c
- builder/builder-options.h
- builder/builder-source-archive.c
- builder/builder-utils.c
- common/Makefile.am.inc
- dbus-proxy/Makefile.am.inc
- dbus-proxy/flatpak-proxy.c
- document-portal/Makefile.am.inc
- document-portal/xdp-fuse.c
- document-portal/xdp-main.c
- lib/Makefile.am.inc
- permission-store/Makefile.am.inc
- session-helper/Makefile.am.inc
- tests/Makefile.am.inc
- tests/testlibrary.c
Turns out the warning flags in `$(WARN_CFLAGS)` were being used successfully in very few places in the code base. Fix that, and fix the resulting onslaught of compiler warnings.
This should hopefully get the warnings which people see locally inline with the warnings the CI system enables, so people don’t keep submitting broken-at-the-time-of-submission PRs.
> Fix compiler warning flags and (accordingly) quite a few compiler warnings

- builder/builder-module.c
- builder/builder-utils.c
- builder/builder-utils.h
Build systems such as `jhbuild` update the terminal title with some high-level status of the build progress. I suggest that `flatpak-builder` does the same.
Doing so not only updates the user of build progress when their terminal tab is not focused, but it also allows applications scripting flatpak-builder (using a PTY) to pass along status messages to users in their user interface. Doing this traditionally would require parsing all STDOUT content which is laborious, CPU expensive, and prone to breakages.
Another possible way to solve this for application scripting would be to pass in a "control FD". I think this solution is better because it solves to similar use-cases with one design.
> Update terminal title with build progress

- app/flatpak-builtins-build-finish.c
- app/flatpak-builtins-build.c
- builder/builder-manifest.c
- common/flatpak-dir.c
- common/flatpak-run.c
- common/flatpak-run.h
- common/flatpak-utils.c
- doc/flatpak-metadata.xml
- document-portal/xdp-main.c
While putting together a serialization for metadata as a GVariant in #890, I did some tidying up of the documentation and `#define`s for flatpak-metadata(5). Is this something people would like merged?
If you prefer the code to use string literals instead of `#define` constants but you do want the flatpak-metadata(5) documentation fixes, everything after the first commit should be cherry-pickable.
>  Document all metadata groups and keys

- lib/flatpak-installation.c
flatpak_installation_install_full takes FlatpakInstallFlags,
but it was checking for a FlatpakUpdateFlags field.
> Check the right flags

- common/flatpak-utils.c
We were checking the prefix twice here, instead of
checking prefix and suffix, which was obviously the
intention.
This caused extensions with non-matching architectures
to be reported as related refs.
> Fix flatpak_summary_match_subrefs

- builder/builder-main.c
flatpak-builder was running into an assertion when --run was
used after a non-option. Catch this and exit with a clear error
message. Same for --show-deps
> Catch some more errors in option parsing

- Makefile.am
It uses inline for loop initialisers, which are a C99 feature. Set
-std=gnu99 like ostree.git does for its libglnx submodule.
Based on a patch by Georges Basile Stavracas Neto
<georges.stavracas@gmail.com>.
> build: Add -std=gnu99 to libglnx CFLAGS

- app/flatpak-builtins-add-remote.c
Resolver errors are more likely in offline remote adds than IO
errors. Catch them first when we're downgrading metadata update
errors to a warning.
https://github.com/flatpak/flatpak/issues/917
> remote-add: also ignore resolver errors

- app/flatpak-builtins-enter.c
Currently, all conceivable configurations and installations of
flatpak require root to perform this operation. That may not be
the case in the future, but until then, we should warn when the
user is not root as the operation will fail.
Fixes https://github.com/flatpak/flatpak/issues/855
> flatpak-enter: warn when not running as root

- common/flatpak-utils.c
Fix the wrong position of ')' when use G_UNLIKELY.
> fix issues #942

- system-helper/Makefile.am.inc
Previously they weren’t getting distributed unless the system helper was
enabled at configure time for distcheck. They should be distributed
unconditionally so the user can choose whether to enable the system
helper when they call configure.
> system-helper: Ensure template files are always distributed

- common/flatpak-dir.c
- common/flatpak-dir.h
Read an xa.languages key from the [core] section of
the repo config to determine which subpaths to install
for Locales. This lets us maintain a list of system
languages without inventing a new file in /etc, and
will also work for alternative install locations.
> Allow setting the locale subpaths in repo config

- lib/flatpak-remote.c
- lib/test-lib.c
- tests/testlibrary.c
This was declared in the header for the P2P stuff, but the definition got lost somewhere. Oops.
People can currently work around this by using`g_object_get()` with the `type` property.
> Add missing flatpak_remote_get_remote_type() implementation

- common/flatpak-dir.c
Fixes issue #950
When xa.languages is not set in repo config, system installs will
get language list from AccountsService's dbus.
> Get language list from AccountsService's dbus

- buildutil/tap-test
- tests/libtest.sh
- tests/test-bundle.sh
- tests/test-extensions.sh
- tests/test-oci.sh
- tests/test-repo.sh
- tests/test-run.sh
- tests/test-unsigned-summaries.sh
- tests/test-update-remote-configuration.sh
- tests/testlibrary.c
Since Flatpak 0.9.6, the tests do not need user extended attributes any more, so we don't need to skip them when running on a deficient filesystem.
This means there is no longer any reason why we should prefer `/var/tmp` over `/tmp`, so use `/tmp`.
> Tests no longer require user xattrs

- buildutil/tap-test
- tests/libtest.sh
- tests/test-bundle.sh
- tests/test-extensions.sh
- tests/test-oci.sh
- tests/test-repo.sh
- tests/test-run.sh
- tests/test-unsigned-summaries.sh
- tests/test-update-remote-configuration.sh
- tests/testlibrary.c
#986 was a bit over-zealous and only worked because `flatpak_ensure_system_user_cache_dir_location()` is hard-coded to prefer `/var/tmp`, which is typically (although not always) not tmpfs. It appears the per-user system cache directory does need to be bare-user and not bare-user-only (I tried the latter and got test failures).
> Partially revert #986

- configure.ac
These were only used by flatpak-builder which has now gone away.
Signed-off-by: Simon McVittie <smcv@collabora.com>
> Drop configure checks for unused libelf, libdwarf

- common/flatpak-dir.c
When ret is NULL object_path is filled with garbage and causes a
segfault g_dbus_proxy_new_for_bus_sync.
```
Thread 1 "flatpak" received signal SIGSEGV, Segmentation fault.
0x00007ffff5c03221 in __strlen_avx2 () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff5c03221 in __strlen_avx2 () at /usr/lib/libc.so.6
#1  0x00007ffff678b6ff in g_variant_is_object_path (string=string@entry=0x1000000001 <error: Cannot access memory at address 0x1000000001>) at gvariant.c:1382
#2  0x00007ffff6d484b1 in g_dbus_proxy_new_for_bus_sync (bus_type=bus_type@entry=G_BUS_TYPE_SYSTEM, flags=flags@entry=G_DBUS_PROXY_FLAGS_NONE, info=info@entry=0x0, name=name@entry=0x5555555d3846 "org.freedesktop.Accounts", object_path=0x1000000001 <error: Cannot access memory at address 0x1000000001>, …
```
> Fix segfault on flatpak update

- common/flatpak-utils.c
Previously, it was possible to enter ‘ ’ (a space) at a number prompt,
and it would be stripped, passed to is_number() (which would erroneously
return TRUE), then passed to strtol() and the return value used
unconditionally.
Fix that by fixing is_number() to return FALSE for the empty string.
> common/utils: Fix is_number("") to return FALSE

- doc/flatpak-metadata.xml
This is useful for Flatpak runtime and app authors who want to know which features they can use when targeting a particular branch, or if they do not have a particular branch in mind, what value they should put in the `required-flatpak` field.
> flatpak-metadata(5): Document when each field was introduced

- configure.ac
Without the '[]', if the error sentence contains a comma, it will cause strange output or errors.
> add missing '[]' around AC_MSG_ERROR

- tests/libtest.sh
- tests/testlibrary.c
The kernel used on some autobuilders for the Debian PA-RISC port
can do "bwrap --ro-bind / / /bin/true", but not the bwrap invocations
made during the actual testing, which fail with "Creating new namespace
failed: Invalid argument". Make the trial bwrap invocation more like
what Flatpak actually does, so that these tests will hopefully be
skipped on such kernels.
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876743
Signed-off-by: Simon McVittie <smcv@debian.org>
> tests: Use a more realistic bwrap invocation to check for support

- po/es.po
GNU and GNOME use the “es” language code for Spanish.
> Fix Spanish language code

- configure.ac
- data/Makefile.am.inc
- document-portal/Makefile.am.inc
- permission-store/Makefile.am.inc
- tests/Makefile.am.inc
This disallows the installation of the document portal and
this option should be used when building the 0.10.x branch in
combination with the new xdg-desktop-portal release that contains
the document portal.
> Add --disable-document-portal configure option [0.10.x]

- configure.ac
This is a manual copy of
https://github.com/GNOME/libglnx/commit/4577dc826a923d976ad1a98b4ed5ecc36eac6efe
This way we don't have to update the libglnx dependency on the stable
branch.
> configure: Fix copy_file_range detection

- configure.ac
---
The document portal needs FUSE, but the build without it doesn't. This is the 0.10.x version of #1417.
> [0.10] Only require FUSE if we're still building the document portal

- common/flatpak-utils.c
Versions of glibc starting with 2.27 include support for memfd_create()
in sys/mman.h, and the included libglnx then drops its internal define.
> common: Include sys/mman.h for memfd_create()

- common/flatpak-context.c
flatpak_context_append_bwrap_filesystem() didn't actually return the
exports so callers crashed dereferencing NULL.
This fixes https://github.com/flatpak/flatpak/issues/1428
> Fix --file-forwarding

- app/flatpak-builtins-uninstall.c
- tests/libtest.sh
- tests/test-repo.sh
When uninstalling, if no specific installation was specified with e.g.
--user or --system, automatically chose any unique match, or error
out if there are multiple alternatives.
> uninstall: Pick installation automatically

- app/flatpak-builtins-search.c
- app/flatpak-builtins-update.c
- app/flatpak-builtins-utils.c
- app/flatpak-builtins-utils.h
- common/flatpak-dir.c
- common/flatpak-dir.h
When updating with no arch is specified we now update
appdata for all supported arches, and we don't look for
updates only of the primary arch.
> update: Fix updates of non-primary arches

- common/flatpak-dir.c
Installation will fail with some weird error later if this is not true.
> Verify that the system cache directory supports user xattrs

- app/flatpak-builtins-uninstall.c
- app/flatpak-transaction.c
- common/flatpak-dir.c
- lib/flatpak-installation.c
This moves the prune call out of flatpak_dir_update() and
flatpak_dir_uninstall() and instead does this manually at all call
sites. The advantage is that we now only call it *once* even if you
uninstall or update multiple apps.
This means update everything is much faster as we don't have to scan
over the entire local repo for each updated app.
> Batch prunes of the local repo

- common/flatpak-dir.c
Its always been allowed to own all subnames, but https://github.com/flatpak/flatpak/pull/1589 regressed
that as it meant apps were not allowed to export matching service files.
This fixes https://github.com/flatpak/flatpak/issues/1627
> dir: Fix prefix matching to allow all you to own all org.App.Id.* names

- common/flatpak-utils.c
Only complete to subrefs is fully matching real part.  For example,
only match org.foo.Bar.Sources for "org.foo.Bar", "org.foo.Bar." or
"org.foo.Bar.S", but not for "org.foo" or other shorter prefixes.
> completion: Don't list sub-refs unless fully matching

- app/flatpak-builtins-build-finish.c
- common/flatpak-common-types.h
- common/flatpak-context.h
- common/flatpak-dir.c
- common/flatpak-exports.h
- common/flatpak-utils.c
- common/flatpak-utils.h
The fix in 5122766284295c460320153c1213bccc7c8e3609 was not right.
First of all it didn't changethe regressing behaviour for build-finish, just install.
Secondly, it changed the prefix matches to always use flatpak_name_matches_one_wildcard_prefix() which had slight differences in behaviour that the previously used  flatpak_name_matches_one_prefix. For example, it always removed the extension, no matter what it was.
This has all been replaced with a shared (between install and build-finish) version that is more strict with extensions, and with what names can be exported as service files (these have to match exactly, with the wildcard and cannot have suffixes).
To test this i tried to install these apps from flathub that has some more complex exports:
org.sparkleshare.SparkleShare: …
> Re-fix export filename checks, this time also for build-finish

- configure.ac
ostree 2018.6 made the P2P API public that was previously experimental,
and added a "p2p" feature flag to replace "experimental". So this commit
updates the logic in flatpak's configure.ac so that we always enable P2P
support if ostree 2018.6 is available, and don't bother checking for a
feature flag or defining OSTREE_ENABLE_EXPERIMENTAL_API. This commit
also changes the behavior when flatpak is built against ostree <
2018.6. Specifically, P2P support is enabled if and only if we're
building against an ostree that has the relevant API, rather than
depending on the user to use `--enable-p2p` or `--disable-p2p`. This
way we can enable P2P by default (which will make it easier for Flathub
to enable P2P support) without breaking builds of flatpak
against versions of ostree without the …
> Fix P2P build against ostree 2018.6

- configure.ac
ostree 2018.6 made the P2P API public that was previously experimental,
and added a "p2p" feature flag to replace "experimental". So this commit
updates the logic in flatpak's configure.ac so that we always enable P2P
support if ostree 2018.6 is available, and don't bother checking for a
feature flag or defining OSTREE_ENABLE_EXPERIMENTAL_API. This commit
also changes the behavior when flatpak is built against ostree <
2018.6. Specifically, P2P support is enabled if and only if we're
building against an ostree that has the relevant API, rather than
depending on the user to use `--enable-p2p` or `--disable-p2p`. This
way we can enable P2P by default (which will make it easier for Flathub
to enable P2P support) without breaking builds of flatpak
against versions of ostree without the …
> Fix P2P build against ostree 2018.6 (backport to 0.10.x)

- common/flatpak-dir.c
The pop was missing, meaning that calling flatpak_dir_find_latest_rev()
corrupted the thread default main context stack of the caller.
> common: Pop the thread default main context in find_latest_rev()

- common/Makefile.am.inc
These headers were recently added to flatpak.h, so they need to be in
flatpakinclude_HEADERS so they are installed.
> common: Update flatpakinclude_HEADERS

- common/flatpak-context.c
We deleted the "filtered" policy, but forgot to delete it in one place.
This fixes https://github.com/flatpak/flatpak/issues/1761
> Fix regression with --own=name

- common/flatpak-utils-private.h
> build: work around guard changes in libsoup

- common/flatpak-dir.c
- data/org.freedesktop.Flatpak.xml
- system-helper/flatpak-system-helper.c
This is used to create the /var/lib/flatpak repo if
needed so that other later operations work. We have
some partial support for it not working in various
operations (using the allow_empty argument) but
this is in no way complete. For example, this
can easily happen if you have a per-user installation
but no system one and then you run flatpak install
with no --user, then it will try to figure out
which one to use and die.
> system-helper: Add EnsureRepo operation

- tests/flatpak.supp
The FICLONE ioctl suppression was hit via a different
codepath too, so tweak the callstack for the
suppression.
> tests: Fix up ioctl suppressions for tests

- common/flatpak-dir.c
Sometimes (for example in some test-repo-collections.sh test that broke) we
update from a remote with an older ostree-metadata branch, and the
check for downgrades broke in this case.
Its unclear exactly what it the best solution here, maybe to silently
disallow the update. However, this change instead just re-allows the
downgrade for this particular case so we get the old behaviour.
> Fix regression from #1961 which broke the tests

- common/flatpak-installation.c
Flatpak has API called flatpak_installation_list_remotes_by_type() which
can list dynamic (LAN/USB) remotes that mirror configured remotes in an
installation. It does this by searching them for the appstream/<arch>
ref, such as appstream/x86_64. But Flatpak now supports
appstream2/<arch> as a way to provide the appstream data as uncompressed
XML, and it's possible that a USB created with `flatpak create-usb` (or
a LAN peer) only has the appstream2 ref available for a certain
collection ID. So this commit changes
list_remotes_for_configured_remote() so that it looks for both
appstream/<arch> and appstream2/<arch>, which makes
flatpak_installation_list_remotes_by_type() robust to that scenario.
> common/installation: Search dynamic remotes for appstream2 also

- app/flatpak-builtins-ps.c
- common/Makefile.am.inc
- common/flatpak-instance-private.h
- common/flatpak-instance.c
- common/flatpak-run-private.h
- common/flatpak-run.c
This is made to let gnome-software enumerate all
running instances and get the same information
about them that flatpak ps provides.
We should probably hold this until we open a new devel branch, since it is new api.
Still to do: docs
> Add an instance api

- app/flatpak-builtins-repo.c
- common/flatpak-dir.c
- common/flatpak-utils.c
- tests/test-update-remote-configuration.sh
Currently Flatpak reads a repo metadata key called "xa.collection-id" to
decide whether to configure a collection ID on a remote. This commit
drops support for xa.collection-id and replaces it with
ostree.deploy-collection-id, which is a key defined by OSTree but so far
only implemented here.
The reason for the change is so that collection IDs can only be deployed
to users running recent versions of Flatpak and OSTree. The current
situation is that Endless wants to deploy collection IDs (and therefore
support for doing USB updates) to users, but servers such as Flathub
can't safely set xa.collection-id in their metadata, because many users
are still using old versions of Flatpak and OSTree[1] which would hit
various bugs[2][3][4] on the P2P code paths that are enabled by
collection IDs. …
> Replace xa.collection-id with ostree.deploy-collection-id

- doc/flatpak-repair.xml
Add a mention of ostree fsck to the flatpak repair man page,
so people know there are more alternatives.
> repair: Refer to ostree fsck

- app/flatpak-main.c
- common/flatpak-installation.c
- common/flatpak-run.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
- session-helper/flatpak-session-helper.c
It has been long enough. It is unlikely that we can still
find any xdg-app installations in the wild.
> Drop xdg-app migration support

- common/flatpak-dir.c
This patch came from https://github.com/endlessm/flatpak/pull/117
I don't know if we can upstream the rest of the patches related to renaming flatpaks, but I think we can at least upstream this one.
> dir: use G_KEY_FILE_DESKTOP_GROUP constant

- common/flatpak-dir.c
- common/flatpak-utils-private.h
Flatpak depends on OSTree 2018.7 now, so we don't need these.
> Remove old OSTree version checks

- tests/Makefile.am.inc
- tests/testlibrary.c
Currently `make distcheck` fails with:
PATH=$(cd . && pwd):${PATH} tests/make-test-runtime.sh
tests/runtime-repo org.test.Platform ""
/bin/bash: tests/make-test-runtime.sh: No such file or directory
This was caused by commit b5d86fe90 and is fixed by this commit.
> tests/Makefile.am.inc: Fix distcheck error

- common/flatpak-bwrap.c
- common/flatpak-run.c
We mistakenly bind-mounted the runtime /usr/etc files read-write in /etc, which means that application could modify some parts of the runtimes (at least when using a per-user installed runtime). Fix this by using a --ro-bind.
We also disallow writes to various configuration files generated specifically for the sandbox. The app modifying these will not cause any problems, but it is still unnecessary to even make this possible.
> Don't allow writes to runtime files in /etc

- app/flatpak-builtins-run.c
- common/flatpak-bwrap.c
- common/flatpak-run.c
A few backports, in particular the writable /etc one.
> 1.0.x backports

- system-helper/flatpak-system-helper.c
1ba30f7 introduced flags to system-helper methods
missing them, but some places were overlooked. This makes
the testsuite pass again.
> fix a few oversights in the recent system-helper change

- doc/flatpak-run.xml
When I made the list of overridden environment variables,
I forgot the 3 most important ones, XDG_{DATA,CACHE,CONFIG}_HOME.
> doc: Mention xdg vars

- common/flatpak-utils.c
It happens sometimes that the first processed total is 1, when this gets
downloaded we have 100% already and then the total changes making this
percentage faulty.
This makes the progress regress sometimes, but I'd say it's better than
a permanent, ficticious number.
Fixes #2428
> Don't use the last percentage if the total size changed

- tests/testlibrary.c
clang was complaining about a number of unused
variables in testlibrary.c. Drop them
> Silence compiler warnings

- tests/Makefile.am.inc
The generated DBus permission header is included by an header in under
app/ that we include from testcommon.c. We already added the app/
directory under the source directory, but we need to include the same
directory under the build directory in order for the compiler to find
the generated header.
Fixes the build in GNOME Continuous, which is failing with:
```
In file included from ../tests/testcommon.c:10:0:
../app/flatpak-builtins-utils.h:28:47: fatal error: flatpak-permission-dbus-generated.h: No such file or directory
compilation terminated.
```
> Fix non-srcdir builds

- app/flatpak-builtins-utils.c
- app/flatpak-builtins-utils.h
- app/flatpak-main.c
When you install flatpak and don't restart your session, the environment will not be set up properly for the desktop to find installed flatpak apps. Warn if we detect this situation.
The warning looks like this:
> XDG_DATA_DIRS= ./flatpak list
> 
> Note that the directories 
> 
>  '/var/lib/flatpak/exports/share'
>  '/home/mclasen/.local/share/flatpak/exports/share'
> 
> are not in the search path set by the XDG_DATA_DIRS
> environment variable, so applications installed by
> flatpak may not work until the session is restarted.
We are careful to only emit the warning when an actual flatpak command is used, so we don't disturb the output of e.g. `flatpak --installations`, which is used to set up the very environment variable that we are complaining about here.
We also back off if we are …
> Add a first-run warning

- app/flatpak-builtins-update.c
Allow refs to be added to the update operation in "flatpak update" even if some
of the matching group have a missing remote. In the case this leaves the
transaction empty, the "nothing to do" error will be printed after the
transaction is run.
> app/flatpak-builtins-update: skip refs from unreachable remotes

- doc/flatpak-list.xml
Its --columns, not --column.
Closes: #2568
> list: Fix a typo in the docs

- common/flatpak-dir.c
I spotted this line in the output from `flatpak history`:
Jun  4 16:17:20	deploy install	com.discordapp.Discord	x86_64	stable	system	flathub	8a0fc700c701		Installed %s from %s	root (test)	flatpak-system-helper (gnome-software)	1.3.3
This is because the format string is passed as the 'url' parameter, the
first format parameter (the ref) is passed as the 'format' parameter,
and 'origin' is ignored because (fortunately) as far as I know, no
character significant to printf (like '%') is permitted in ref names.
Fix this by passing a NULL 'url', like the neighbouring call in
flatpak_dir_deploy_update().
> dir: include NULL url in flatpak_dir_log() call

- .github/workflows/block-autosquash-commits.yml
We want to block merging for these, to ensure that you autosquash
before merging.
Ideally we'd like automatic (or at least via a bot) autosquashing, but
that is not currently possible.
> Add action that checks for autosquash commits in pull requests

- common/flatpak-installation.c
If the installation contains 1 or more installed refs, but none of those refs have a remote with a collection ID, then 'results' will be NULL but 'installed' will be non-NULL. Since c29e686246086fa24a9cf9ba291d0e2f43420e06, 'results[0]' is used in this situation – a NULL pointer dereference. There is an existing 'results != NULL' check inside the body of this loop, but this is too late.
Check whether 'results' is NULL before dereferencing it.
It would of course be nice to cook up a test for this, but I don't fully understand the preconditions, and I don't have time to dig deeper at the moment. Apologies!
Fixes #3134.
> installation: don't dereference possibly-NULL array

- doc/flatpak-create-usb.xml
Update the man page to clarify that you have to configure relevant
remotes on the destination computer for "flatpak install" to work. E.g.
flathub must have been added if the refs are from flathub.
> doc/flatpak-create-usb: Clarify that remotes must be configured

- app/flatpak-builtins-install.c
- doc/flatpak-install.xml
- tests/test-run.sh
This allows you to ensure that a particular app/runtime is installed
and with the latest version in a single operation, which is useful
for instance in automatic use, like CI systems.
> Add flatpak install --or-update operation

- common/flatpak-transaction.c
This allows the introspection data to be generated with the correct type for each of these properties, instead of just `int`. This should improve the quality of the documentation as well as bindings generated from the introspection data.
> transaction: Annotate enums with their type

- common/flatpak-bwrap.c
- common/flatpak-dir.c
- common/flatpak-run.c
- common/flatpak-utils-base-private.h
- common/flatpak-utils-base.c
- portal/Makefile.am.inc
- portal/flatpak-portal.c
- system-helper/flatpak-system-helper.c
As per https://gitlab.gnome.org/GNOME/glib/merge_requests/490
there is a bug in glib < 2.60 where g_spawn_* can sometimes deadlock
due to using malloc in the child func to close fds.
We work around this in places where the code is (potentially) threaded
by passing glib flags to leave fds alone and then do a very naive
(but safe) fd cloexec loop ourselves.
I got this when trying to get the CI running on an ubuntu 18.08 (github actions) vm, which has an older glib, but in the end I fixed that by picking up glib 2.60 from a custom ppa. I'm not 100% sure this is enough to fix all issues though because I think some hangs were from elsewhere. For example, ostree uses g_spawn to spawn gpg. So, if this is not a full solution, and if the race condition is pretty small and fixed in later versions, …
> Work around deadlocks in g_spawn by manually clo-exec:ing fds

- common/flatpak-dir-private.h
- common/flatpak-dir.c
For example, if org.the.App or org.the.Platform is masked that means we don't want to get any updates to it. Its very likely that we also don't want updates to extensions of this app or runtime. For example, we definately don't want to update the .Locale or .Debug extensions.
> Update: Don't update an extension if it is an extension and the base is masked

- app/flatpak-cli-transaction.c
We were using the old ref here, instead of the new
one, when asking whether to go ahead.
Closes: https://github.com/flatpak/flatpak/issues/3139
> eol: Use the right ref in the confirmation message

- doc/flatpak.xml
The docs refer to flatpakref files in /etc/flatpak/remotes.d,
but the code is looking for flatpakrepo files there.
> Fix a doc typo

- po/id.po
- po/pt_BR.po
These are from paid-for translations from Endless’ downstream copy of
flatpak. I don’t know the original authors, and don’t know if the
translations are correct. (They should be though.)
Probably better than having no translations for these strings in
upstream flatpak, for the moment.
---
cc @cho2, @rffontenelle
> po: Add some translations for parental controls strings

- .github/workflows/check.yml
- tests/http-utils-test-server.py
- tests/libtest.sh
- tests/oci-registry-server.py
- tests/test-http-utils.sh
- tests/test-oci-registry.sh
- tests/test-repo.sh
- tests/test-unsigned-summaries.sh
- tests/test-webserver.sh
- tests/web-server.py
Rather than this weird shell loop with a timeout and polling we
move the httpd spawning entirely into the python code, and use
a pipe to synchronize the spawning. This way we can also use
the shell job control to properly clean up any running processes
from the test suite.
Additionally, this adds some (lame) support for token handling in the
test webserver, where you for any file foo can create a foo.need_token
containing a token that is needed for that file.
> tests: Redo httpd server setup

- data/org.freedesktop.Flatpak.xml
- session-helper/flatpak-session-helper.c
This fixes compilation with GLib 2.63’s `gdbus-codegen`, which
automatically enables Unix FD support for D-Bus APIs which use the `h`
type, even if the `org.gtk.GDBus.C.UnixFD` annotation is missing.
By adding the annotation, the generated header whether using
`gdbus-codegen` 2.63 or < 2.63.
This is a slight API break in GLib, but it’s questionable about whether
flatpak should have always had the annotation.
> session-helper: Correctly annotate use of Unix FDs in D-Bus API

- tests/Makefile.am.inc
Files in the srcdir need to be explicitly prefixed as such in rule
commands. This fixes `make install` when installed-tests are enabled.
> build: Fix the path to some installed-tests files

- common/flatpak-transaction.c
- tests/testlibrary.c
This ensures that when the operation to install the app completes, the
app is ready to run — rather than having to wait for subsequent
operations to install extensions which the app depends on (such as
content, or locales).
This fits in with the current ordering for *un*installing apps, where
the main app is uninstalled first, followed by its extensions.
https://github.com/flatpak/flatpak/issues/3017
> transaction: Install extensions before apps

- common/flatpak-run.c
This fixes issues seen by @matthiasclasen with flatpak run while low on diskspace.
> Use /tmp for flatpak run

- tests/Makefile.am.inc
There's no need for this file to be executable. If it was executed,
shells would typically try to execute it as a shell script (because it
isn't an ELF executable and doesn't start with #!), which isn't going
to work.
> build: Don't install test.portal as executable

- app/flatpak-builtins-config.c
- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-installation.c
- common/flatpak-installation.h
- doc/flatpak-config.xml
- tests/testlibrary.c
Make the languages key more relevant for different regions than just
the language code adopting full locales to the core keys.
> app: Change xa.extra-languages to accept locales

- doc/flatpak-spawn.xml
Adds documentation for the new flatpak-spawn option added in https://github.com/flatpak/flatpak-xdg-utils/pull/22
Signed-off-by: Mat Booth <mat.booth@redhat.com>
> Adds documentation for the new flatpak-spawn option

- app/flatpak-builtins-config.c
- common/flatpak-dir.c
- common/flatpak-installation.c
- doc/flatpak-config.xml
- tests/testlibrary.c
Also update the tests to use the same format, and make sure to include
coverage of all forms of locale (language-only, with locale, with
codeset, and with modifier).
> config: Rework handling of extra-languages to change locale format

- app/flatpak-builtins-list.c
- app/flatpak-builtins-remote-ls.c
Currently, if you run:
flatpak remote-ls flathub --app-runtime=com.endlessm.Platform//eos3.2
you see no apps (correct) but hundreds of runtimes. This is inconsistent
with the documentation for the '--app-runtime' option, which says:
> List applications that use the given runtime
To fix this, default to not showing runtimes if '--app-runtime' is
given. This is consistent with the behaviour if just '--app' is
specified. If you run 'flatpak list --app-runtime=com.example.Foo
--runtime' then you get apps using that runtime, plus all other
runtimes, which seems fair enough to me.
> builtins: hide runtimes with [list|remote-ls] --app-runtime

- common/flatpak-dir.c
If building with --disable-system-helper, common/flatpak-dir.c might
still try to use polkit APIs. A check for libmalcontent was already in
place but not enough.
> common: Add missing check for USE_SYSTEM_HELPER

- app/flatpak-cli-transaction.c
Replace "in preference of" with "in favor of," as the former is not widely used, but the latter is (see https://books.google.com/ngrams/graph?content=in+favor+of%2Cin+preference+of&year_start=1800&year_end=2000&corpus=15&smoothing=3). 
This problem was mentioned in issue #3139.
> Make deprecation warning notice less confusing

- common/flatpak-parental-controls.c
If `content_rating == NULL`, then no value will be assigned to
`appdata_value`, but its value will be used anyway – if it happens to be
non-`NULL`, it will be dereferenced.
common/flatpak-parental-controls.c: In function ‘flatpak_oars_check_rating’:
common/flatpak-parental-controls.c:121:10: warning: ‘appdata_value’ may be used uninitialized in this function [-Wmaybe-uninitialized]
if (appdata_value != NULL)
^
> parental-controls: fix read of uninitialized variable

- app/flatpak-quiet-transaction.c
In commit 0772ab6c9 we changed "in preference of" to "in favor of" in an
informational message produced by FlatpakCliTransaction for clarity. Do
the same for FlatpakQuietTransaction.
> app/flatpak-quiet-transaction: Use "in favor of" phrasing

- system-helper/flatpak-system-helper.c
After an unprivileged client calls GetRevokefsFd(), the `revokefs-fuse
--backend` process busyloops as follows:
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}], 2, -1) = 1 ([{fd=4, revents=POLLIN}])
Here is the command line for this process:
revokefs-fuse --backend --socket=3 --exit-with-fd=4 /var/lib/flatpak/repo/tmp/flatpak-cache-JBUHB0
The intention here is to poll() until fd 3 is readable (at which
point the writer process serves a client request and writes back a
response, synchronously) or fd 4 encounters an error. fd 4 is meant to
be one side of a pipe that the system helper holds the other end of;
when the pipe is broken, the system helper must have gone away, and the
`revokefs-fuse --backend` process treats this as a signal to exit.
However, fd 4 is not a pipe. In fact, it is …
> system-helper: fix busyloop in revokefs writer process

- common/flatpak-dir.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
It's a common idiom in this codebase to push a temporary GMainContext as
the thread default context in order to run an async operation as if it
were sync. If we are not expecting progress callbacks this isn't a
problem, but it becomes a problem if we pass in an OstreeAsyncProgress
object that was created under a different GMainContext. The reason for
this is that OstreeAsyncProgress creates an idle source and attaches it
to the thread default context, so if we are iterating a temporary
context then the OstreeAsyncProgress's context never gets iterated, and
so no progress signals are fired.
To fix this, we introduce flatpak_progress_chain() and a RAII helper
FlatpakAsyncProgressChained which creates a new OstreeAsyncProgress
under the temporary GMainContext, but forwards all its state and …
> utils: Allow chaining OstreeAsyncProgress when pushing GMainContext

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-installation.c
- tests/testlibrary.c
installation: Return main app as updatable if related extensions are missing
While updating, if the related extension is missing on
the installation and the main app is installed, FlatpakTransaction
tends to "repair" the main app by automatically downloading
the related extension again and restoring the overall functionality
of the app.
The related extension concerned that are the ones associated with
"should-download" to TRUE only.
Hence, teach the libflatpak API to do that same, so that clients
like gnome-software can mark those apps as updatable, if their
related extensions is missing.
__________________
This PR also contains a commit that introduces a more strict checking of main ref and related ref when there is  "previous-ids"  mentioned in the deploy file.
> installation: Return main app as updatable if related extensions are missing

- common/flatpak-run.c
Mount ~/.local/share/icons at /run/host/user-share/icons in
the sandbox, so runtimes can add /run/host/user-share to
their XDG_DATA_DIRS and get access to locally-installed
icon themes.
> Make per-user icon themes available in the sandbox

- doc/flatpak-spawn.xml
This was missing from the man page.
> Document the flatpak-spawn --watch-bus option

- common/flatpak-transaction.c
These were added so that extra-data would work in #2954, however that
was a bit broad. We only need extension deps for extensions that:
1) Uses extra data (so we can run apply-extra)
2) Doesn't specify NoRuntime=true (because the apply-extra is static)
Fixes https://github.com/flatpak/flatpak/issues/3173
> Don't pull dependencies for extension points unless strictly needed

- tests/make-test-app.sh
- tests/test-run.sh
2ebf67286660f5111baac379fd44a401f57b40bb introduced special handling to
mark exported GNOME Shell search provider .ini files as disabled by
default. This functionality was not previously tested.
> tests: test search-provider DefaultDisabled logic

- doc/flatpak-permission-remove.xml
- doc/flatpak-permission-reset.xml
- doc/flatpak-permission-set.xml
- doc/flatpak-permission-show.xml
- doc/flatpak-permissions.xml
- doc/flatpak-ps.xml
- doc/flatpak.xml
This new command was missing from flatpak(1) and
from the references in other permission commands.
> docs: Add flatpak permissions-set to command list

- common/flatpak-context.c
The --persist option makes a subpath in the user's home directory
available in the sandbox. Make the description more clear accordingly.
> context: Improve description of --persist

- app/flatpak-builtins-enter.c
The COMMAND is not optional, so don't put it in brackets.
Closes: https://github.com/flatpak/flatpak/issues/2881
> enter: Correct the help output

- doc/flatpak-info.xml
Show an example for how to list the files that are
part of an installed app.
Related: https://github.com/flatpak/flatpak/issues/3079
> info: Add an example to the man page

- app/flatpak-builtins-ps.c
We were unconditionally adding the instance column,
which causes table headers to be off-by-one when
instance is not among the requested columns.
Change things to only add the instance column
when requested.
> ps: Don't hardcode instance column

- app/flatpak-builtins-run.c
- doc/flatpak-run.xml
Show a placeholder to indicate that this option
takes an argument. Update docs to match.
> run: Improve help output for --parent-pid

- common/flatpak-utils-http.c
G_input_stream_read_finish returns a gssize,
which we must not store in a gsize, since it
may be -1.
Closes: https://github.com/flatpak/flatpak/issues/2885
> Fix a case of signed/unsigned confusion

- app/flatpak-cli-transaction.c
These show up as ^M in test logs, and that is irritating.
Just use \n when producing plain output.
Closes: https://github.com/flatpak/flatpak/issues/3226
> cli: Don't use \r in plain output

- app/flatpak-builtins-ps.c
- doc/flatpak-ps.xml
Show active and background state, based on information obtained from the background portal backend about which apps have (active) windows.
This currently tries all known portal backends in turn. It might be nicer to have a portal frontend api to query this, or to find out which backend to talk to.
> ps: Allow showing compositor info

- portal/flatpak-portal.h
This was accidentally left out of the FLAGS_ALL define so it was denied.
> portal: Allow the ALLOW_A11Y flag

- common/flatpak-installation.c
Here we're using the same GError pointer multiple times without clearing
it, which is an error.
> installation: Don't re-use a GError pointer

- app/flatpak-builtins-permission-list.c
- app/flatpak-builtins-permission-set.c
- doc/flatpak-permission-set.xml
Add a way to set data in the permission store via the permission-set command.
While working on this, I ran into the `data wrapping` issue again, and noticed that Set and SetValue treat their data argument differently:
Set:
``` 
data_child = g_variant_get_child_value (data, 0);
new_entry = permission_db_entry_new (data_child);
```
SetValue:
```
new_entry = permission_db_entry_new (data);
```
The permission store interface requires a GVariant of type v for the data argument of both, so i have to add an extra level of wrapping to my argument: `<{'ask':true}>` instead of `{'ask':true}`. But then handle_set_value fails to remove that extra wrapping before stuffing the data into the store :(
> Permission set data

- app/flatpak-builtins-permission-set.c
It is confusing if we explicitly have to specify
the <> GVariant wrapping with --data, but
flatpak permissions strips it when displaying the
result.
Make it transparent by auto-applying the wrapping,
so what you need to pass to --data is the same
as what flatpak permissions shows you.
> permission-set: Auto-apply wrapping for data

- common/flatpak-bwrap-private.h
- common/flatpak-bwrap.c
- common/flatpak-run.c
- portal/flatpak-portal.c
In the start of child_setup_func we set CLOEXEC on everything > 3, so
we need to undo this for the things we actually want to pass in.
> portal: Make sure we inherit the passed thought fds in Spawn()

- common/flatpak-utils-base.c
flatpak_get_timezone () tries to access /etc/timezone if /etc/localtime
isn't a valid symlink, but gets the name wrong. Fix it.
Found by code inspection. Not actually tested.
> Fix typo in /etc/timezone filename

- app/flatpak-builtins-build-bundle.c
- app/flatpak-builtins-build-import-bundle.c
- common/flatpak-json-oci-private.h
- common/flatpak-json-oci.c
- common/flatpak-oci-registry.c
- common/flatpak-utils.c
- tests/test-oci.sh
This is a slightly incompatible change, as we now only support
oci images generated with (what was before) build-export --oci-use-labels.
However, there are not a lot of OCI implementations in the wild, and
we can modify the ones in use to ensure there are labels (and
annotations if needed for older flatpak clients).
This also removes the --oci-use-label option from build-bundle --oci as
this is now the default.
> OCI: Only use labels, never annotations

- tests/flatpak.supp
This is deliberately allocated once per process and never freed.
---
Noticed while testing #3307.
> flatpak.supp: Silence GFile leak in flatpak_get_user_base_dir_location()

- common/flatpak-transaction.c
- data/org.freedesktop.Flatpak.Authenticator.xml
- oci-authenticator/flatpak-oci-authenticator.c
This is primary useful to disable the authenticator doing native windows for apps that run in the background, however it can also avoid doing unnecessary webflow or basic auth flows.
As requested by @pwithnall on the list.
> Add flag for non-interaction to authenticator request

- common/flatpak-utils-private.h
- common/flatpak-utils.c
With the latest ostree that enables the chaining of progress the
testsuite broke because we were not getting changed events. Looking
into this the reason seems to be that when we run the
ostree_async_progress_finish() on the chained progress it is marked
as dead, which causes ostree_async_progress_copy_state() to not copy
any data when called from handle_chained_progress().
The fix is to copy the content manually before calling the finish().
Also, the entire callback chaining system seems wildly
overcomplicated, so I simplified it by relying on the existing change
notification of OstreeAsyncProgress.
> utils: Fix chaining of progress

- common/flatpak-dir.c
Immediately return the error instead of saving the error and
continuing on an optional codepath if _flatpak_dir_get_remote_state
is cancelled.
This is extracted from https://github.com/flatpak/flatpak/pull/2932
> dir: Immediately return if getting remote state is cancelled

- app/flatpak-builtins-utils.c
It often happens that people use --user or --system or --installation
and get a "Remote not found" error message, because they don't
understand that remotes have to be defined separately in each
installation. Make the error message more helpful by pointing out when
one of those options was used.
Fixes https://github.com/flatpak/flatpak/issues/3296
> app: Improve "remote not found" error message

- app/flatpak-main.c
This warning is meant for interactive use, and as per #3316 it often
breaks non-interactive stuff like scripts. So, we only warn on ttys,
and only on normally interactive operations like run, install and update
to avoid warnings in cases like building (where XDG_DATA_DIRS is not
needed) or information gathering things like e.g. flatpak info.
> CLI: Limit where we warn about unset XDG_DATA_DIRS

- common/flatpak-dir.c
- common/flatpak-utils.c
Don't use G_VARIANT_BUILDER_INIT() which is glib 2.50 only
> Fix build on older glib

- flatpak.pc.in
While flatpak carefully doesn’t expose any OSTree symbols in its C API,
it does sometimes return GErrors with the domain `OSTREE_GPG_ERROR`.
Applications can happily link against flatpak and receive such errors,
but won’t be able to understand them without also linking against
OSTree.
OSTree is a hard dependency of flatpak, so we might as well move it to
`Requires` rather than `Requires.private` to ensure that clients link
against it.
See https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/336/diffs#note_650999
> flatpak.pc: Move ostree-1 from Requires.private to Requires

- portal/flatpak-portal.c
This fixes https://github.com/flatpak/flatpak/issues/3330
> Sandbox: Allow share-gpu also if caller has device=all

- common/flatpak-dir.c
After installing a locally built bundle, gnome-software started to crash due the changes introduced in https://github.com/flatpak/flatpak/pull/3204
> Fix a gnome-software crash 

- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-run.c
- doc/flatpak-build-finish.xml
- doc/flatpak-build.xml
- doc/flatpak-metadata.xml
- doc/flatpak-override.xml
- doc/flatpak-run.xml
This new permission exposes the host /dev, which is normally not visible
even with --device=all, as it is not really a device node but rather
a bunch of shared memory blocks available on the host.
This access is needed by jack, as explained at:
https://github.com/flatpak/flatpak/issues/1509
Long term I think a better solution for pro audio (like pipewire) is
a better solution, but for now we should at least allow jack apps to work.
> Add --device=shm permission

- common/flatpak-utils.c
In flatpak-builtins-build-commit-from.c we call flatpak_repo_collect_sizes()
without initializing the passed in download size to zero, which mean
we sum with sizes with some random value as the start.
This is fixed by having flatpak_repo_collect_sizes() always initialize
the counters to 0 at the start.
Fixes https://github.com/flatpak/flatpak/issues/3362
> build-commit-from: Fix generation of download-size

- common/flatpak-context.c
Don't allow adding access to things like ~/foo xdg-foo/bar or similar
things just because you used to have home access, because such files
may be outside the homedir (for instance, if they are symlinks or configured
via xdg-user-dirs).
> update-portal: Limit which filesystem access additions we allow

- doc/flatpak-build-finish.xml
- doc/flatpak-build.xml
- doc/flatpak-override.xml
- doc/flatpak-run.xml
Taken from #3373, but useful to merge separately.
> doc: Point to flatpak-metadata(5) for the meanings of filesystem keywords

- app/Makefile.am.inc
Fixes the missing 'app' directory:
```
Traceback (most recent call last):
File "/data/dwrobel1/rdkv/rpi-flutter-3/build-raspberrypirdkhybrefapp/tmp/sysroots/x86_64-linux/usr/bin/gdbus-codegen", line 39, in <module>
sys.exit(codegen_main.codegen_main())
File "/data/dwrobel1/rdkv/rpi-flutter-3/build-raspberrypirdkhybrefapp/tmp/sysroots/x86_64-linux/usr/share/glib-2.0/codegen/codegen_main.py", line 186, in codegen_main
h = open(c_code + '.h', 'w')
FileNotFoundError: [Errno 2] No such file or directory: './app/flatpak-permission-dbus-generated.h'
make: *** [app/flatpak-permission-dbus-generated.c] Error 1
make: *** Waiting for unfinished jobs....
```
> Fix out-of-tree build error

- common/flatpak-context.c
- common/flatpak-exports-private.h
- common/flatpak-exports.c
It was called flatpak_exports_add_home_expose(), but it actually
exposed the entire host filesystem, to the extent possible.
Rename it to flatpak_exports_add_host_expose() to reflect that.
---
Taken from #3373, but mergeable separately (and fairly trivial tbh).
> exports: Fix a confusingly-named method

- common/flatpak-run.c
Fixes #2641
Fixes flathub/org.electronjs.Electron2.BaseApp#4
> run: Fix TMPDIR env var not being passed through suid bwrap

- portal/flatpak-portal.c
We don't need to check for GLib 2.44 (the first release with g_autoptr()
support) since Flatpak requires that version in configure.ac.
Fixes https://github.com/flatpak/flatpak/issues/3403
> portal: Add g_autoptr() defines for old GLib versions

- app/flatpak-builtins-info.c
- app/flatpak-cli-transaction.c
Don't imply a download or install uses a negative number of bytes.
> app: Don't print "< 0 bytes"

- app/flatpak-builtins-run.c
- common/flatpak-dir.c
- system-helper/flatpak-system-helper.c
As noticed in https://github.com/flatpak/flatpak/issues/3412 we
regressed at some point and are no longer using from-scratch deltas.
This is caused by an optimization in ostree where it decides to not
use a from-scratch deltas if theres is *some* version of the ref
locally available.
This conflicts with some code in flatpak that pulls *only* the commit
object in order to look for extra data size information so that we can
get the progress reporting right. Unfortunately the existance of
just the object triggers the above causing us to *never* use from-scratch
deltas.
We fix this by throwing away the partial pull in an aborted ostree
transaction.
> Actually use from-scratch deltas

- common/flatpak-dir.c
- tests/http-utils-test-server.py
- tests/oci-registry-client.py
- tests/test-http-utils.sh
- tests/test-oci-registry.sh
- tests/test-webserver.sh
This is a backport of fix to use static-deltas to the 1.4 branch.
Additionally it also has some fixes to make the tests pass on python3-by-default distros and a backport of a p2p mirror-ref fix that is needed for the static-delta fix.
> Backport scratch-delta support

- common/flatpak-context.c
- common/flatpak-exports-private.h
- common/flatpak-exports.c
- common/flatpak-run-private.h
- common/flatpak-run.c
- doc/flatpak-build-finish.xml
- doc/flatpak-build.xml
- doc/flatpak-metadata.xml
- doc/flatpak-override.xml
- doc/flatpak-run.xml
- icon-validator/validate-icon.c
* exports: Fix a confusingly-named method (#3374)
It was called flatpak_exports_add_home_expose(), but it actually
exposed the entire host filesystem, to the extent possible.
Rename it to flatpak_exports_add_host_expose() to reflect that.
* doc: Point to flatpak-metadata(5) for the meanings of filesystem keywords (#3375)
* exports: Only choose bwrap --bind/--ro-bind for host FS once
We can choose this once and use it repeatedly, which will be simpler
when we add more directories that work this way.
* icon-validator: Add lib32 to usrmerged_dirs, for completeness
This syncs it up with our other lists of /usr-merged directories.
In particular, this could matter on Arch Linux, which uses /usr/lib
and /usr/lib32 for 64- and 32-bit libraries (respectively), instead
of the more common /usr/lib64 …
> Add host-etc, host-os exports

- .github/workflows/check.yml
- common/Makefile.am.inc
* build: Fix out-of-tree build with variant-schema-compiler
The variant-schema-compiler and its input are in the $(srcdir).
* CI: Do one build out-of-tree
With the gcc build out-of-tree and the clang build in-tree, we're
testing both ways.
> Fix (and test) out-of-tree builds

- common/flatpak-run.c
This is continuation of https://github.com/flatpak/flatpak/commit/ad9599d3e31050d07d782267038cc2f316af0235 and should complete coverage of read-only bind-mounts of sockets.
> Mount systemd sockets as read-only

- common/flatpak-run.c
If it's an opaque integer on the host system, it might as well be an
opaque integer in the container too.
Fixes: #3416
> run: Cope with the primary gid not being in the nsswitch database

- .lgtm.yml
- README.md
Without this, lgtm.com can't successfully build the C code in Flatpak.
> Add .lgtm.yml

- common/flatpak-oci-registry.c
- oci-authenticator/flatpak-oci-authenticator.c
Some registries require getting a token even to download an image
anonymously. So, if no auth has been configured, before prompting
the user for username/password, try without a BasicAuth header.
Signed-off-by: Owen W. Taylor <otaylor@fishsoup.net>
<hr>
Another approach would be to handle this without going to the authenticator at all - if we get UNAUTHORIZED response with a WWW-Authenticate and don't have a token, try to get one anonymously. This patch posits that maybe we'll change things so that OCI remotes always have the OCI authenticator configured by default, and always try to get a token for every image.
> flatpak-oci-authenticator: try getting a token without credentials

- common/flatpak-oci-registry.c
If no scope parameter is supplied in the WWW-Authenticate header,
docker and libpod will make up their own of the form
repository:<reponame>:pull when requesting a bearer token. Match that.
Signed-off-by: Owen W. Taylor <otaylor@fishsoup.net>
> flatpak-oci-registry.c: supply a default scope when getting a token

- doc/flatpak-build-init.xml
New users who jump directly into this command might think this command is to init a project or application dictionary but it actually creates somehow a directory as target of  `flatpak build `
plus, fix the not working example
Sorry for such minor and boring commit.
> Better `build-init` explanation & fix example

- common/flatpak-bwrap.c
flatpak_bwrap_bundle_args() for some reasons does:
data = g_new (gchar, data_len);
*data = 0;
And then it starts copying in the data into the allocation, overwriting
the initial 0. If data_len is 0 this causes a write past end of
allocation, so just drop the second line above.
> common: Don't potentially write outside allocation

- common/flatpak-dir.c
If no remotes are configured, ostree_repo_remote_list returns NULL
so don't dereference it.
Fixes: https://github.com/flatpak/flatpak/issues/3436
> repair: Don't crash if no remotes are configured

- tests/libtest.sh
- tests/test-repo.sh
It seems recent ostree reports a different error string for signature
check failures.
> tests: Fix gpg signature failure checks

- oci-authenticator/flatpak-oci-authenticator.c
When we already have a token for the first repository after probing
for no-auth authenticator or testing user-entered credentials, just
use that, don't request it again in the loop over repositories.
This gives a significant optimization of the prompted-credentials
case for registry.redhat.io, which takes 4-5 seconds to generate a
token, hopefully avoiding the user thinking something has gone wrong.
Signed-off-by: Owen W. Taylor <otaylor@fishsoup.net>
> oci-authenticator: reuse token results when we already have them

- app/flatpak-builtins-build-commit-from.c
- app/flatpak-builtins-build-export.c
- common/flatpak-dir.c
- common/flatpak-transaction.c
- common/flatpak-utils.c
When storing the token-type in the commit and the summary cache we
hardcode it to little-endian.
In theory this breaks the "ABI", but in practice this change is a
no-op on little-endian systems which is what most are. Additionally as most
servers are little-endian this also fixes using big-endian clients with
such servers.
This fixes:
https://github.com/flatpak/flatpak/issues/3434
> Enforce little endian for token-type

- oci-authenticator/flatpak-oci-authenticator.c
Fix problems overwriting a GError when we retry multiple times.
One of these was introduced with the recent change
e3f17a89a flatpak-oci-authenticator: try getting a token without credentials
but the other was existing.
Signed-off-by: Owen W. Taylor <otaylor@fishsoup.net>
<hr>
I added a g_debug in the prompted-auth-retry-loop to add debugging information in the "something else is going wrong" case, but decided to skip it for the initial try-without-credentials attempt, since a failure there is expected.
> oci-authenticator: fix failures to clear GError

- common/flatpak-utils-http.c
- tests/test-http-utils.sh
Like https://github.com/ostreedev/ostree/pull/1594 but for Flatpak.
> Retry network requests on transient errors

- common/flatpak-utils.c
- tests/testcommon.c
Allow the app-id or the DConf path to finish with a digit and still be
considered similar enough for DConf migration purposes.
This allows the org.gnome.Rhythmbox3 app-id to migrate its
/org/gnome/rhythmbox DConf path.
See https://github.com/flathub/org.gnome.Rhythmbox3/pull/26
> common: Allow version numbers in app-id for DConf migration

- common/flatpak-dir.c
%ld is only 32 bits long on ILP32 (32-bit) platforms.
This partially addresses #3499.
> dir: Format 64-bit ints correctly

- app/flatpak-cli-transaction.c
it's irritating to have it this way when everything else uses a comma as
a decimal separator
> cli-transaction: properly format '1.0 kB'

- .github/workflows/check.yml
- .lgtm.yml
- common/flatpak-dir.c
This is a bug introduced in b03916f5bdf878ba42af7ccf569233b839d4b3d2
where we check the extra_data refs against app/ or runtime/ prefix with
arguments in the wrong order.
(cherry picked from commit ed3ba39a06d47d384a50e3a6264d411f3bf20a5d)
This is a backport of the fix noticed in https://github.com/flatpak/flatpak/pull/3482
> Fix calculation of extra-data total size (1.6.x backport)

- app/flatpak-builtins-install.c
- app/flatpak-builtins-remote-add.c
- app/flatpak-builtins-remote-info.c
- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-oci-registry.c
- common/flatpak-transaction.c
- common/flatpak-utils-http-private.h
- common/flatpak-utils-http.c
- tests/test-auth.sh
We need to get the commit object to setup the extra-data progress information,
and this is currently done using a complex pull operation to a temporary
repo. According to https://github.com/flatpak/flatpak/issues/3515 it
even causes an unecessary download of the summary in some cases.
Now that we don't need to support p2p we can instead directly download
the commit object using a simple http operation (or from the sideload
repos), as we know the commit id at this point anyway.
> extra-data: Simplify extra-data progress setup

- common/flatpak-dir.c
This reverts commit 6deb23a32231e1d88d45532130f4ffeb7d71cd54.
This commit has two unintended side effects:
1. It breaks progress bars
(https://github.com/flatpak/flatpak/issues/3448)
2. It causes us not to use static deltas
> Revert "extra-data: Simplify extra-data progress setup"

- common/flatpak-dir.c
- common/flatpak-utils.c
A fix for https://github.com/flatpak/flatpak/issues/3496
> Fix "Can't pull from untrusted non-gpg verified remote" error

- doc/flatpak-create-usb.xml
`flatpak remote-modify --collection-id= ` can be use to set the collection ID of the remote server.
I spent quite a while trying to find how to set it, until I found this blog post:
https://blogs.gnome.org/mclasen/2018/08/26/about-flatpak-installations/
> Added flatpak remote-modify reference

- common/flatpak-dir.c
- common/flatpak-progress.c
As documented in https://github.com/flatpak/flatpak/pull/3524 the recent change to flatpak_dir_setup_extra_data broke progress reporting and was reverted. This PR reverts the reverts and then fixes the underlying issue, which was a combination of flatpak using partial commit states when it was not needed and a bug in ostree when deltas and partial commits were combined (https://github.com/ostreedev/ostree/issues/2053).
The fix is twofold, first, avoid commitpartials when not needed. Secondly, limit progress to 100% in case we get erroneous behaviour from ostree.
> Re-fix progress

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
- data/flatpak-variants.gv
Avoid the extra commit download by storing the extra-data download size in the summary.
> Extra data size in summary

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-installation.c
- common/flatpak-transaction.c
- common/flatpak-transaction.h
- common/flatpak-utils-private.h
- tests/Makefile.am.inc
- tests/libtest.sh
- tests/make-test-runtime.sh
- tests/test-extensions.sh
- tests/testlibrary.c
This re-implements flatpak_installation_list_installed_refs_for_update() using FlatpakTransaction, which ensures it behaves consistently with the CLI. The impetus is that gnome-software uses this API, and tends to not show the same updates as `flatpak update`.
> Re-implement list_installed_refs_for_update() again

- configure.ac
- system-helper/Makefile.am.inc
- system-helper/flatpak.conf.in
This will make systemd create the system-helper user if it is missing.
> Add sysusers.d configuration file

- common/flatpak-transaction.c
- common/flatpak-transaction.h
I’ve been working on improving the installation progress reporting in gnome-software, using `flatpak_transaction_operation_get_related_to_op()`, and could do with access to the `skip` field to be able to skip related-to ops.
This PR adds that, and contains a few unrelated misc tweaks.
> Add API to allow improved progress reporting in gnome-software

- po/de.po
When we add significant new source strings downstream, Endless adds
projects to our Transifex instance to get translations from paid
translators and community contributors.
Since we no longer add new source strings to Flatpak, we're removing it
from our infrastructure. I checked which strings we have translations
for downstream that are not present (if perhaps different) upstream, and
these German translations from a community member are it.
(I speak only very rudimentary German so cannot vouch personally for these translations.)
> Import German translations from Endless OS

- common/flatpak-installation.c
- common/flatpak-transaction.c
- common/flatpak-transaction.h
- common/flatpak-utils-private.h
Since a single runtime (for example) can be related-to several apps,
that needs to be representable in the data format.
This is an API break, but only of API which has not been released yet.
See https://github.com/flatpak/flatpak/pull/3568#issuecomment-618251958
> flatpak-transaction: Change related_to_op to related_to_ops

- common/flatpak-run.c
The newly added https://systemd.io/DESKTOP_ENVIRONMENTS/ lists an XDG
defined specification for how cgroups for applications should be named.
This will allow flatpak's to correctly follow any drop-in's set for
applications on the system as well as help next-gen system monitor's
treat flatpaks as applications.
flatpak-session-helper.service is unaffected.
> Rename registered cgroups to have app- prefix

- app/flatpak-builtins-update.c
Currently if you run "flatpak update --commit=XYZ", we try to use that
commit for every installed thing, which doesn't make much sense. Make it
an error not to specify a ref with --commit.
> update: Restrict --commit to one app/runtime

- app/flatpak-builtins-remote-info.c
Logically, the SDK should be listed with the app info right after the
runtime, not in the commit section.
> remote-info: Move newline

- common/flatpak-auth.c
- common/flatpak-dir.c
- common/flatpak-oci-registry.c
- oci-authenticator/flatpak-oci-authenticator.c
- tests/Makefile.am.inc
- tests/oci-registry-server.py
Unless otherwise specified use the oci authenticator with default token type 1 for all OCI remotes.
This makes a lot of sense as it allows e.g. use of docker hub (with anonymous login, which we default too if it works).
@owtaylor Opinions?
> Use oci authenticator by default

- common/flatpak-dir.c
- common/flatpak-oci-registry-private.h
- common/flatpak-oci-registry.c
- common/flatpak-transaction.c
- common/flatpak-utils-http-private.h
- common/flatpak-utils-http.c
If downloading a specific commit (or oci manifest) we may get a 401 back.
If so, request a token and try again. In this case we don't yet know the
token type, so pass MAXINT32 for "don't know".
> tokens: Request tokens during resolve if we get 401 status

- README.md
We don't have a separate discourse for Flatpak; it seems fine to link to
the Flathub one.
Fixes https://github.com/flatpak/flatpak/issues/3602
> README: Link to Flathub discourse

- common/flatpak-run.c
The systemd app prefix has changed from `apps-` to `app-` (https://github.com/systemd/systemd/pull/15647) (following https://github.com/flatpak/flatpak/pull/3589)
Also, special characters need to be escaped in systemd unit names, especially `-` which has a special meaning.
> Systemd unit name

- selinux/flatpak.te
Hi,
I am part of SELinux team and I fixed bug where disabling unconfined module fails:
`# semodule -d unconfined`
`Failed to resolve typeattributeset statement at /var/lib/selinux/targeted/tmp/modules/200/flatpak/cil:29`
`semodule : Failed !`
It was because macro unconfined_domain(flatpak_helper_t) wasn't in optional_policy block, so I added it.
> Add unconfined_domain(flatpak_helper_t) to optional_policy block

- common/flatpak-run.c
This makes flatpak respects XDG_DATA_HOME and XDG_CACHE_HOME for binding
user's fonts and icons into the sandbox.
> common/flatpak-run: respect user's XDG base directories

- common/flatpak-instance-private.h
- common/flatpak-instance.c
- common/flatpak-run.c
It was completely identical in flatpak-run.c and flatpak-instance.c.
This is something I noticed while working on #3617 and figured I might as well clean it up a bit...
> Clean up duplicated instance collection code

- app/flatpak-cli-transaction.c
- common/flatpak-dir.c
flatpak_dir_install was returning FALSE but leaving error to NULL, which
would crash when printing the error.
Fixes #3634
> Fix segfault when reporting error during install

- app/flatpak-builtins-remote-add.c
A repository needs to exist for a remote to be written inside,
otherwise the OstreeRepo instance will be NULL and a crash will
occur once the instance is accessed.
Fixes #3612.
> remote-add: Don't make the repo existence optional

- app/flatpak-builtins-remote-add.c
- app/flatpak-builtins-remote-modify.c
- doc/flatpak-remote-add.xml
- doc/flatpak-remote-modify.xml
Assume that if user explicitly modifies the URL, they want to keep
using that URL instead of having it overwritten by xa.redirect-url.
Add switches to remote-add and remote-modify for uniformity.
> Make xa.redirect-url handling configurable

- common/flatpak-run.c
- doc/flatpak-remote-add.xml
- doc/flatpak-run.xml
The terms whitelist and blacklist are hurtful to some people, and per
our code of conduct Flatpak is an inclusive community. Replace them with
allowlist and blocklist which are also more clear. This terminology
change is being implemented more broadly in the software industry; see
e.g. https://go-review.googlesource.com/c/go/+/236857/
> tree-wide: Replace usages of whitelist/blacklist

- app/flatpak-cli-transaction.c
- app/flatpak-quiet-transaction.c
- common/flatpak-transaction.c
- common/flatpak-transaction.h
This is useful if to avoid changing the no-interaction of the whole
FlatpakInstallation. Also, having this per transaction lets us
clean up the code in FlatpakQuietTransaction a bit.
Replaces https://github.com/flatpak/flatpak/pull/3571
> Add and use per-transaction no-interaction option

- common/flatpak-run.c
Alternative fix to https://github.com/flatpak/flatpak/pull/3389
If an app has PulseAudio access, also allow direct ALSA device access.
The practical permissions of ALSA and PulseAudio access are
essentially the same (in fact, its possibly less damaging to have
direct device access as bugs in pulseaudio could allow sandbox
breakout that wouldn't be possible with deivce access).
We could add a separate option for this, but since they are
essentially the same, and since both are not the end goal (which is
using portals and PipeWire for audio), seems like unnecessary churn in
apps and code.
> Allow ALSA device access if app has pulseaudio access

- app/flatpak-builtins-build.c
- app/flatpak-builtins-run.c
- common/flatpak-installation.c
- common/flatpak-run-private.h
- common/flatpak-run.c
- data/org.freedesktop.portal.Flatpak.xml
- doc/flatpak-run.xml
- portal/flatpak-portal.c
- portal/flatpak-portal.h
Now we can see PIDs of spawned processes...but there's no way to actually know what spawned processes they correspond to. This adds the ability to see that.
> Add the SpawnStarted signal

- app/flatpak-cli-transaction.c
- common/flatpak-error.h
- common/flatpak-oci-registry.c
- common/flatpak-transaction.c
- oci-authenticator/flatpak-oci-authenticator.c
This adds `FLATPAK_ERROR_AUTHENTICATION_FAILED` and `FLATPAK_ERROR_NOT_AUTHORIZED` to FlatpakErrors, and extends the authenticator protocol to handle the `error-code` key to pass a FlatpakError code to the client (used instead of G_IO_ERROR_FAILED).
Additionally the oci authenticator is updated to use this (and with some tweaks to its error handling).
> Add auth specific errors and allow authenticators to report them

- common/flatpak-json-oci.c
We handle both types, so look for both.
> OCI: Also look for the docker media type when looking manifests

- common/flatpak-auth.c
- common/flatpak-dir.c
- common/flatpak-json-oci.c
- common/flatpak-oci-registry-private.h
- common/flatpak-oci-registry.c
- tests/Makefile.am.inc
- tests/oci-registry-server.py
This backports:
* Always use authenticator for OCI
* Also use token when pulling oci in system-helper
* Handle docker media types
This should be enough to make e.g. docker hub and redhat infra work.
@owtaylor wanna check this?
> Backport oci changes to 1.6.x

- common/flatpak-transaction.c
In theory we should be able to assert that the error pointer is set
after calling flatpak_transaction_run() because otherwise there is a
programmer error somewhere, but in practice programmers do err pretty
often and it's nice not to crash in that case. For the motivating case
see https://github.com/endlessm/flatpak/pull/224
> common: Make list_installed_refs_for_update() more robust

- common/flatpak-dir.c
GError conventions require we set the error pointer on error code paths.
> dir: Fix an error path in pull_untrusted_local

- common/flatpak-transaction.c
- doc/flatpak-install.xml
- doc/flatpak-update.xml
It is no longer a config option; it was changed to be a directory.
> Update documentation for sideload-repos

- common/flatpak-dir.c
These patches apply only to the flatpak-1.6.x branch since the relevant code has been removed from master.
> Fix two issues in P2P code (flatpak-1.6.x backport)

- Makefile.am
- configure.ac
As mentioned in https://github.com/flatpak/flatpak/pull/3679 and
https://github.com/flatpak/flatpak/issues/3678 it is causing issues,
and the systemd generators we have should be fine for most uses
anyway.
If a distros need it the gdm file can easily be re-enabled with
--enable-gdm-env-file.
> Don't install gdm env file by default

- app/flatpak-cli-transaction.c
- app/flatpak-quiet-transaction.c
- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-transaction.c
- common/flatpak-transaction.h
- tests/libtest.sh
- tests/make-test-app.sh
- tests/test-auth.sh
This is an alternative version of https://github.com/flatpak/flatpak/pull/3510
It has a different API as mentioned there. Instead of changing how FlatpakTransaction works it adds a single transaction signal which you need to connect to and install the authenticator via a separate transaction.
> Auto install authenticator

- common/flatpak-transaction.c
- tests/test-oci-registry.sh
This is making the flatpakref file less portable,
so we should warn to give developers a hint that
this is a possible problem.
> Warn if RuntimeRepo is missing

- .gitignore
- Makefile.am
- common/flatpak-dir.c
- configure.ac
- doc/flatpak.xml
- sideload-repos-systemd/Makefile.am.inc
- sideload-repos-systemd/flatpak-create-sideload-symlinks.sh
- sideload-repos-systemd/flatpak-sideload-repos-dir.service
- sideload-repos-systemd/flatpak-sideload-usb-repo.path.in
- sideload-repos-systemd/flatpak-sideload-usb-repo.service.in
- system-helper/Makefile.am.inc
Fixes https://github.com/flatpak/flatpak/issues/3490
> Automatically sideload from inserted USB drives

- common/flatpak-run.c
- common/flatpak-utils-base.c
Instead of relying on the runtime tzdate we now always expose the host
/usr/share/zoneinfo in that location and make /etc/localtime a regular
symlink to it. This means applications that parse the content of the
localtime symlink will work, and additionally it means that we're
guaranteed that the host configure timezone exists (and works with)
the tzdata in the app.
This unfortunately means we no longer make the localtime an indirect
file via the session helper, and thus that localtime configurations
are static over the lifetime of an app sandbox. However, I don't
think there is a workable solution to this.
This fixes https://github.com/flatpak/flatpak/issues/3338
> run: Always expose host /usr/share/zoneinfo (if possible)

- common/flatpak-dir.c
Currently Flatpak only supports extensions which come from the same
remote as the thing being extended; for discussion on this see
https://github.com/flatpak/flatpak/issues/861
However in general it isn't clear from the metadata what remote provides
an extension. For example com.endlessm.apps.Platform//5 defines the
extension org.freedesktop.Platform.VAAPI.Intel (inherited from
org.freedesktop.Platform) which can be found on flathub not eos-sdk. So
we don't want to add an extension refspec to the transaction if the
current remote is not the one that actually provides it. In
flatpak_dir_find_remote_related_for_metadata() this invariant is
maintained because we check if the ref exists in the remote before
adding it with add_related(). However in
flatpak_dir_find_local_related_for_metadata() …
> dir: Fix wrong extension refspecs

- common/flatpak-transaction.c
If a ref doesn't actually change in an update transaction we need not authenticate it, so avoid that by
moving where we detect the no-op update earlier.
> Avoid authentication of no-op updates

- common/flatpak-transaction.c
This is a simpler version of https://github.com/flatpak/flatpak/pull/3718 for 1.6
>  Avoid authentication of no-op updates for 1.6.x branch

- common/flatpak-transaction.c
Document that operations are executed in the same order they are
returned because gnome-software is depending on that:
https://gitlab.gnome.org/GNOME/gnome-software/-/blob/cf5656031f0d25c9c36e2ad0e6e6cfd4b4f2c718/plugins/flatpak/gs-flatpak-transaction.c#L279
> transaction: Update get_operations() docs

- common/flatpak-remote.c
- tests/testlibrary.c
Don't leave options set on the remote in one of the unit tests. If
something should be set for every test it should be done in
global_setup(). This commit also changes the FlatpakRemote
implementation to allow unsetting title and default branch.
> More fully reset remote in unit tests

- .gitignore
I mistakenly omitted these in 9caf664fabc911419cc483125bf543c4550604c7
> gitignore: Add built units in sideload-repos-systemd

- common/flatpak-exports.c
- doc/flatpak-run.xml
- tests/test-run.sh
If available, always read-only bind-mount /etc/os-release as
/run/host/os-release (or /usr/lib/os-release as fallback)
as suggested by the os-release specification:
https://www.freedesktop.org/software/systemd/man/os-release.html
> run: implement sandbox host os-release interface

- common/flatpak-run.c
Otherwise it just bounces you to the Google Groups home page.
(Side note: As a Sandstorm.io contributor, it was exciting to hear that we share code with something!)
> Fix libseccomp Google Groups link

- common/flatpak-run.c
From: @julian-klode
clone() is a mad syscall with about 4 different argument orders. While
most of them agree that argument 0 is flags, s390 and s390x have the
flags argument second - A0 is the child stack pointer there.
[smcv: Add an explanatory comment; also test `__CRIS__` for completeness]
Bug-Debian: https://bugs.debian.org/964541  
Bug-Ubuntu: https://launchpad.net/bugs/1886814
---
For reference see clone(2), https://github.com/systemd/systemd/blob/master/src/basic/raw-clone.h and kernel source.
I'm told that this change is necessary and sufficient to make flatpak-builder work on s390x, for everyone who wants to be able to build desktop applications for their non-GUI-capable IBM mainframe (if such users even exist).
This is currently considered to be a release-critical bug in Debian …
> Fix argument order of clone() for s390x in seccomp filter

- README.md
The libflatpak API reference link was broken. Let's just link to
docs.flatpak.org
> README: Adjust links to docs

- tests/Makefile.am.inc
Otherwise the installed tests will fail:
SUMMARY: total=32; passed=30; skipped=0; failed=2; user=820.8s; system=589.3s; maxrss=445132
FAIL: flatpak/test-oci-registry@user.wrap.test (Child process exited with code 1)
FAIL: flatpak/test-oci-registry@system.wrap.test (Child process exited with code 1)
due to:
error: The name org.flatpak.Authenticator.Oci was not provided by any .service files
> tests: install org.flatpak.Authenticator.Oci.service

- Makefile.am
So that we can use the same sequence of commands for building flatpak out of the repository and the tarball.
> build: Distribute autogen.sh

- common/flatpak-utils-http-private.h
This made its way into the Debian symbols file, but looks like it was
never supposed to be exported.
> http-utils: Stop exporting an internal error quark

- doc/flatpak-create-usb.xml
Update the create-usb man page to reflect the re-worked implementation
that landed in 1.7.1.
> doc: Update create-usb for sideloading

- common/flatpak-exports.c
In applications with --filesystem=host or --filesystem=host-os, the
library directories in /run/host/usr and /run/host/lib* can be used
like a sysroot to inspect the host's library stack, regardless of
whether the host system has undergone the "/usr merge" or not. This is
particularly relevant for Steam's pressure-vessel container tool,
which imports graphics drivers from the host system, or for potential
future work on using host graphics drivers via libcapsule in Flatpak
apps.
The original implementation of this feature assumed that the /usr merge
always creates symbolic links /foo -> /usr/foo or /foo -> usr/foo, for
some value of foo. However, Arch Linux uses a variation of multilib
in which /usr/lib contains 64-bit libraries, and has a non-matching
symbolic link /lib64 -> usr/lib …
> exports: Try harder to export usrmerge symlinks as symlinks

- sideload-repos-systemd/Makefile.am.inc
Add flatpak-sideload-usb-repo.service.in to EXTRA_DIST regardless of if
the --enable-auto-sideloading configure option was passed. This allows
building a tarball without that option and then building from the
tarball with the option.
This matches what is done in system-helper/Makefile.am.inc with
flatpak-system-helper.service.in.
Picked from https://github.com/endlessm/flatpak/pull/228
> sideload-repos-systemd: Dist service unconditionally

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-transaction.c
- doc/flatpak-flatpakref.xml
- doc/flatpak-remote-add.xml
- doc/flatpak-remote-modify.xml
- doc/flatpak-remote.xml
- tests/test-authenticator.c
- tests/test-portal-impl.c
- tests/testcommon.c
- tests/testlibrary.c
Currently when searching for a remote to provide the runtime for an app,
we search remotes in priority order. This commit makes it so we search
the remote providing the app first, then search the rest in priority
order. This behavior just seems logical, but the impetus for this change
was also to keep a unit test passing in eos-updater[1] after a port to
FlatpakTransaction.
In practice it's usually true that only one remote provides a runtime
and priorities aren't set at all, so this is an edge case that probably
doesn't come up much.
A unit test is included.
[1] https://github.com/endlessm/eos-updater/blob/eede0a8b9cb7c9cbb8539cfcaad9ce18913dcdd8/tests/test-update-install-flatpaks.c#L1919
> Check an app's origin first for its runtime

- common/flatpak-dir.c
These are system dbus calls that could potentially be somewhat slow
and its unlikely that the local config changes during runtime of the
session (because the desktop really needs a restart to pick up a new
locale). Also, if there are any issues with these (such as #3755) each
call will be the 25sec dbus timeout, which is not great.
Fixes https://github.com/flatpak/flatpak/issues/3792
> dir: Cache responses from localed and account service

- common/flatpak-run.c
Discovered this by accident, in particular it meshes badly with the new `SpawnStarted` system because if the portal fails to start, but flatpak hangs, the portal will forever be waiting for the process and running a timer every 100ms.
> run: Avoid hanging if xdg-dbus-proxy startup fails

- common/flatpak-run.c
We were returning a g_autofree:d string and it was then also freed
by the parent.
> run: Fix double free in the cups config file parser

- common/flatpak-dir.c
Some things could need to run e.g. i386 code in apply_extra (for
example #3742).  In this very limited context (almost everything is
read-only) this seems pretty secure.
We could require the app to specify a multiarch pemission to allow
this, but such permissions only really make sense for an app, and
extra data is often used for other things like runtimes and
extensions, that seems a bit weird.  Lets just enable it always.
Fixes #3742
> Allow multiarch in the apply_extra for extra-data

- common/flatpak-dir.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
This commit is a follow-up for the commit "dir: Validate locally
configured collection IDs". Whereas in that commit we validate the
collection ID in flatpak_remote_state_fetch_commit_object(), here we do
it in _flatpak_dir_get_remote_state(), since fetch_commit_object() is
not called on the code path normally taken for a transaction (only if
try_resolve_op_from_metadata() fails and in other niche scenarios).
This should ensure that if someone erroneously sets a collection ID on a
remote, the error will be caught quickly. It also helps the eos-updater
unit tests pass.
> Properly validate configured collection IDs

- .github/workflows/check.yml
Reverts flatpak/flatpak#3811
This seems to make CI hang, like https://github.com/flatpak/flatpak/pull/3809/checks?check_run_id=1012991662
> Revert "CI: Run make check in parallel (-j NCPU)"

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-transaction.c
This is a subset of #3781 with review comments fixed.
I’ve dropped the changes to the on-disk cache code for now. The commits in this PR are the seemingly-simple and seemingly-uncontroversial changes from #3781, so they can get merged first.
I’ll update #3781 after further thinking/testing.
> Improve in-memory caching to reduce unnecessary network requests

- .github/workflows/check.yml
- tests/flatpak.supp
This takes a long time, but doesn't have to be mandatory.
Additionally the new test uses ubuntu-latest so we get more wider testing.
Also removes some old no-longer needed ci config workaround.
> CI: Add a valgrind check

- common/flatpak-run.c
- tests/test-run.sh
* run: Tell processes in container that the container manager is Flatpak
https://systemd.io/CONTAINER_INTERFACE/ describes a generic way to tell
programs and libraries that they are running in a container: set
pid 1's ${container} to the name of the container manager in lower case,
and populate /run/host/container-manager with the same string followed
by a newline. Let's be nice to application code by doing that, instead
of requiring it to look at /.flatpak-info.
* tests: Test container-manager interface
> Implement more of systemd's container interface

- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-exports-private.h
- common/flatpak-exports.c
- doc/flatpak-metadata.xml
- tests/Makefile.am.inc
- tests/test-exports.c
* context: Only parse filesystem/mode strings in one place
This gives us the ability for the parse function (the former verify
function) to carry out a normalization step as well.
* exports: Add assertions to distinguish between mode representations
When we're talking about a "mode", sometimes we mean a
FlatpakFilesystemMode, sometimes we mean a FlatpakFilesystemMode that
must be strictly greater than NONE, and sometimes we're willing to
accept the FAKE_MODE constants too.
* context: Expose flatpak_context_parse_filesystem for testing
* tests: Add basic unit tests for FlatpakExports, FlatpakContext
There's a limit to how many assertions we can make here right now,
because what we do here is very dependent on the "shape" of the host
filesystem. This could be extended in future by using a …
> Normalize --filesystem arguments

- common/flatpak-context.c
- tests/test-exports.c
* tests: Exercise flatpak_context_save_metadata
* context: Implement MODE_NONE in unparse_filesystem_flags
flatpak doesn't yet use -Wswitch-enum, but perhaps it should at some
point. Now that FLATPAK_FILESYSTEM_MODE_NONE is a member of the enum,
it should be handled; and if we're doing that, we might as well make
the same function fully responsible for it.
> Add basic test coverage for saving a context, and slightly improve the code under test

- app/flatpak-builtins-enter.c
Fixes #3820.
This makes it much easier to test things in `flatpak enter`, for example it makes `flatpak enter your.apps.id xdg-open http://flathub.org/` actually work.
> Fix DBUS_*_BUS_ADDRESS in flatpak enter

- common/flatpak-oci-registry.c
Runtimes also have appstream data - with description, license information,
and so forth, so we should extract the appstream data from the index
for refs that start with runtime/ as well.
> OCI: extract appstream data for runtimes

- common/flatpak-progress.c
Somewhere during the progress reporting cleanup we lost the progress
for OCI pulls, this puts it back.
> OCI: Fix progress reporting

- common/flatpak-transaction.c
In case we need to authenticate for updates (in my test case i was
doing an OCI downgrade) we might need to download a commit object (or
in the OCI case a manifest json), so it did a request_required_tokens(),
but that noticed during the flatpak_transaction_normalize_ops() call
that the partial resolve to a particular commit actually was the
same as the local installed commit and marked op->skip = TRUE.
However, when we got back to resolving the op again we didn't actually
look at the skip, so it kept looping wanting (but never doing) auth.
The fix is to just directly resolve ops marked as skipped.
> Don't loop authentincating if updating to the current version

- common/flatpak-dir.c
Without this patch, the remote-info command will sometimes emit a
critical error "g_utf8_strlen: assertion 'p != NULL || max == 0' failed"
and print (null) for the "Commit:" field, since the commit doesn't get
initialized properly.
> Avoid critical error in remote-info command

- common/flatpak-exports-private.h
- common/flatpak-exports.c
- tests/test-exports.c
Follow-up from #3283.
* exports: Allow redirecting /etc, /usr from the host to an alternative
This is primarily for test coverage ("design for test"): it will let us
pretend a temporary directory is the host for the purposes of testing
--filesystem=host-etc, --filesystem=host-os, and the os-release handling
from #3733.
It can also be used to build a bwrap command-line that will be used on
the host, while already inside a container, which will be useful for
Steam's pressure-vessel tool (which copies some of the Flatpak code).
* tests: Allow asserting that a bind-mount has a different target
* tests: Assert that symlinks point to the right place
The previous implementation was rather simplistic, and assumed that
all symlinks that get exported are in /tmp/something/test_full/.
Tighten up the …
> Add test coverage for FlatpakExports implementation of host-os, host-etc

- portal/flatpak-portal.c
Fix lookup_installation_for_path() to not leave the GError pointer unset
on its error code path. This error is only used by the caller for a
debug message, and shouldn't be hit normally, but it could mean a NULL
pointer dereference when we try to print error->message.
> portal: Fix unset GError issue

- common/flatpak-utils.c
- tests/testcommon.c
Allow a snake-case in the app-id to convert to a '-' or '_' in the
DConf path to be considered similar enough for DConf migration purposes.
This allows the org.gnome.SoundJuicer app-id to migrate its
/org/gnome/sound-juicer DConf path.
`F: Ignoring D-Conf migrate-path setting /org/gnome/sound-juicer/`
> common: Allow skewering when converting in app-id for DConf migration

- sideload-repos-systemd/flatpak-create-sideload-symlinks.sh
- sideload-repos-systemd/flatpak-sideload-usb-repo.path.in
- sideload-repos-systemd/flatpak-sideload-usb-repo.service.in
Previously, if there were no existing symlinks, this script would fail:
wjt@camille:~$ LANG=en_GB.utf8 bash -x /usr/libexec/flatpak-create-sideload-symlinks.sh /run/media/wjt
+ test 1 -eq 1
+ test -d /run/media/wjt
+ for f in "$1"/*
+ test -d '/run/media/wjt/*'
+ continue
+ for f in /run/flatpak/sideload-repos/automount-*
+ test -e '/run/flatpak/sideload-repos/automount-*'
+ rm '/run/flatpak/sideload-repos/automount-*'
rm: cannot remove '/run/flatpak/sideload-repos/automount-*': No such file or directory
This is due to the surprising POSIX shell behaviour that a glob that
matches no files expands to itself, rather than to the empty list.
http://mywiki.wooledge.org/BashFAQ/004
The POSIX solution is to add 'test -L $f' inside the loop to check if
the variable actually exists.  The first …
> sideload-repo-systemd: Various fixes

- sideload-repos-systemd/flatpak-create-sideload-symlinks.sh
When launched when the session starts, /run/media/%u may not exist if
the user has never mounted any removable storage devices. This causes
the unit to fail on login.
Relax the check to just validate that the argument has been provided.
Since we use shopt -s nullglob, the "$media_dir"/* glob will expand to
the empty list if $media_dir does not exist.
(The other option is to add a condition check to the .service, but the
script might conceivably want to clean up some stale symlinks.)
> sideload-repo-systemd: Don't require media dir to exist

- data/org.freedesktop.Flatpak.xml
- data/org.freedesktop.portal.Flatpak.xml
- doc/reference/Makefile.am
- doc/reference/libflatpak-docs.xml
* portal: Fix typos in documentation
* portal: This is the flatpak portal, not the documentation portal
Also specify that it's on the session bus, not some other bus.
* portal: Document forwards-compatibility for flags and options
Flags are assumed to be critical, similar to the convention for modern
Linux syscalls: if an unknown flag is given, the call will fail.
Callers are expected to guard their use of flags with a version check
or a fallback.
Conversely, options are assumed to be non-critical "hints", similar
to org.freedesktop.Notifications: if an unknown option is given, the
call will succeed as though the option had not been present. Callers
are expected to carry out an explicit version check if they need to
know whether an option is going to be respected or not.
* portal: …
> Document D-Bus APIs

- common/flatpak-utils.c
- tests/testcommon.c
commit 6b46d9a0ede99dca99737fa3d4e55200cb9336e3 that added DConf path
skewering to camelcase conversion only allowed it in one direction
(skewered path1 and camelcase path2).
That turned out to be not enough to allow /org/gnome/sound-juicer/ to
/org/gnome/SoundJuicer/ conversion as the caller had the
flatpak_dconf_path_is_similar() arguments the other way around.
This commit implements it both ways to avoid confusion which way it
should be called.
F: Ignoring D-Conf migrate-path setting /org/gnome/sound-juicer/
> common: Allow skewered to camelcase DConf path conversion both ways
