- app/flatpak-builtins-build-finish.c
- app/flatpak-builtins-build-init.c
- common/flatpak-transaction.c
This fixes two issues from #3887:
- It's possible to create extensions with invalid ref names.
- Invalid ref names cause the transaction code to segfault.
> Fix issues from lack of extension name validation

- app/flatpak-cli-transaction.c
- common/flatpak-installation.c
- common/flatpak-transaction.c
- common/flatpak-transaction.h
- oci-authenticator/flatpak-oci-authenticator.c
It turns out that out flatpak_installation_list_installed_refs_for_update() implementation using transactions doesn't handle the case where authentication is needed for a particular ref as it doesn't install an auth handler. To avoid this problem we add and use a new ready-pre-auth signal that gets emitted when we're ready with everything except auth.
Once we have this we also make the CLI ask for transaction confirmaion before authentication, as that seems to be a nicer behaviour.
> Fix update detection if authentication is needed and ask for confirmation before auth

- common/flatpak-utils-http.c
Sometimes a server might return a HTTP error 500 (this seems to happen
sometimes with Microsoft’s VSCode server, for example). Map this to
`G_IO_ERROR_HOST_UNREACHABLE` for now, which is a bit more specific than
returning `G_IO_ERROR_FAILED`, but without the hassle of introducing a
new public error domain which could give more detail.
In particular, this should allow gnome-software to show an error message
to the user for such failed downloads, rather than hiding the error and
logging the following:
```
not handling error failed for action download: While downloading http://packages.microsoft.com/repos/vscode/pool/main/c/code/code_1.45.1-1589445302_amd64.deb: Server returned status 500: Internal Server Error
```
> http: Return HOST_UNREACHABLE on error 500

- common/flatpak-dir.c
- common/flatpak-run.c
* Skip parental controls checks on ServiceUnknown or NameHasNoOwner
If accountsservice isn't available on the system bus, then we can't
ask it for the user's parental controls settings, and we also can't
ask it whether it even has the malcontent extension. Since this is
not a real security boundary, fail open.
This can be dropped if we depend on a version of libmalcontent that maps
these errors to MCT_APP_FILTER_ERROR_DISABLED
(https://gitlab.freedesktop.org/pwithnall/malcontent/-/merge_requests/89).
Resolves: #3902 (aka Debian bug https://bugs.debian.org/972138)
cc @pwithnall, @bigon
> parental controls: Fail open if accountsservice is missing

- .github/workflows/check.yml
No need to waste resources running every test after the README
changes.
> CI: Ignore some paths that don't affect build

- tests/testlibrary.c
It seems cleaner to use library API than the CLI here.
> testlibrary: Tweak one of the tests to avoid CLI

- common/flatpak-progress.c
We were never calling the progress callback for extra-data downloaded
bytes.
> Fix extra-data progress reporting

- common/flatpak-dir.c
- common/flatpak-utils-http.c
- common/flatpak-utils.c
- system-helper/flatpak-system-helper.c
This fixes various issues I had with using ostree master that relies on the mtime of the summary cache to be up-to date.
Note: I didn't get it fully working without https://github.com/ostreedev/ostree/pull/2230
> Fix mtime issues

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-transaction.c
This moves a bunch of code from FlatpakDir to FlatpakTransaction which was
only used to find dependencies. This allows us to reuse the existing
cache of FlatpakRemoteState objects in the transaction.
> transaction: Reuse FlatpakRemoteState when finding dependencies

- common/flatpak-dir.c
Backport the patch from #3854 in response to https://github.com/flatpak/flatpak/pull/3854#issuecomment-722355060
> Backport fix for remote-info command to 1.8.x

- common/flatpak-installation.c
- tests/testlibrary.c
Currently if an app has been renamed and you run "flatpak update" you
will be prompted to decide whether to install the new name of the app
(and uninstall the existing one). However, in such a situation
flatpak_installation_list_installed_refs_for_update() does not return
the app, and therefore gnome-software doesn't see any updates available.
So include end-of-life-rebased apps in the returned list. Patches to
make gnome-software update such apps properly are forthcoming.
> installation: Include renamed apps when listing updates

- app/flatpak-builtins-build-commit-from.c
- app/flatpak-builtins-build-export.c
- app/flatpak-builtins-remote-add.c
- app/flatpak-builtins-remote-list.c
- app/flatpak-builtins-remote-modify.c
- app/flatpak-builtins-repo.c
- app/flatpak-table-printer.c
- app/flatpak-table-printer.h
- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-utils.c
- doc/flatpak-build-commit-from.xml
- doc/flatpak-build-export.xml
- doc/flatpak-flatpakrepo.xml
- doc/flatpak-remote-add.xml
- doc/flatpak-remote-modify.xml
- system-helper/flatpak-system-helper.c
- tests/Makefile-test-matrix.am.inc
- tests/Makefile.am.inc
- tests/libtest.sh
- tests/test-subset.sh
When you create a commit (i.e. `build-export` or `build-commit-from`) you can add `--subset=foobar`, which will mark that commit as part of the subset named "foobar".  When we generate summaries we create an extra set of subsummaries (one per arch) that only contains the refs marked with that subset, and we also generate a subset of the appstream data (named `appstream2/foobar-x86_64` etc). 
On the client you can `remote-add` or `remote-modify` with `--subset=foobar`, or have a flatpakrepo file with `Summary=foobar`. This sets the `xa.subset` config option on the remote, and if this is set, then flatpak will only use the summaries with that subset, and will use the per-subset appstream branch. 
The goal here is to allow for instance flathub to have a "free" subset which only contains …
> Add support for repo subsets

- app/flatpak-builtins-repo.c
The subset column is typically short, while for eol options the
options column can be very long. So, it makes more sense to have the
options at the end.
> build-repo: Switch order of subset and options columns

- app/flatpak-cli-transaction.c
- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-ref-utils-private.h
- common/flatpak-ref-utils.c
- tests/test-repo.sh
- tests/testcommon.c
We remember what action we took for EOLs, and for sub-refs (ie .Locale)  we reuse that.
Also, we show if eol:ed refs are pinned (as that makes them not be auto-uninstalled), and we list the apps that use the eol:ed runtime ref.
Example run:
```
Looking for updates…
Info: (pinned) org.gnome.Sdk.Compat.i386 is end-of-life, with reason:
The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform is end-of-life, with reason:
The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
org.gnome.HexGL
```
> Better eol handling in CLI

- common/flatpak-context.c
Building with Clang 11 shows a warning for the cast of the 'gpointer' to
'FlatpakFilesystemMode'.
This is due to '-Wpointer-to-int-cast' being now enabled by default.
```
common/flatpak-context.c:2144:13: warning: cast to smaller integer type
'FlatpakFilesystemMode' from 'gpointer' (aka 'void *')
[-Wvoid-pointer-to-enum-cast]
fs_mode = (FlatpakFilesystemMode) g_hash_table_lookup (context->filesystems, "host");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> context: do not use a cast to convert a pointer to an integer

- common/flatpak-utils.c
There was a bug in the extension point matcher which made it
install `org.gnome.Totem.Videosite.YouTubeDl.Sources` (in addition to
`org.gnome.Totem.Videosite.YouTubeDl`) for the `org.gnome.Totem.Videosite`
extension.
We just need to make sure we only match the extension prefix if there
is a single element in the extension name following the extension
name (i.e. '.YouTubeDl', not '.YouTubeDl.Sources').
This fixes https://github.com/flatpak/flatpak/issues/3973
> Don't auto-install sources for extensions

- common/flatpak-transaction.c
This is reported when we reported an error to the user via
::operation-error signal and the app told us to not continue.
If this happens in some weird case and we see the results its nice
to have access to the original error message.
> transaction: Add more details to the ABORTED error

- common/flatpak-run.c
A typo was causing us to pass the app id as arch, breaking (at least)
multiarch support.
> Fix multiarch support

- common/flatpak-dir.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
The old summary had a ostree.commit.timestamp in the per-ref metadata
dict. However, since this was not used anymore by flatpak I removed it.
However, it turns out that flathub has infra that depends on this,
so I'm adding it back.
We reuse the data in the old summary for unchanged refs when
rebuilding the summary, to avoid having to read all the commits. In
the new world the new format summaries are used for this, which means
we have to keep the timestamp in that too. However, to not be
unnecessary large its now using a shorter key name, as this is
duplicated for each ref in the summary.
> Add back the ostree.commit.timestamp per-ref metadata for summary

- doc/flatpak-search.xml
The title for the `branch` column description says `version`.
> docs: Fix typo in flatpak-search usage

- common/flatpak-exports.c
As /usr/local points to ../var/usrlocal on Silverblue,  /run/host/usr/local was previously a broken link inside the
sandbox. This patch checks if /var/usrlocal exists and bind-mounts it to /run/host/var/usrlocal.
See bug #4010.
> Expose /var/usrlocal if "--filesystem=host" is specified.

- common/flatpak-utils-base-private.h
- oci-authenticator/flatpak-oci-authenticator.c
- portal/flatpak-portal.c
- session-helper/flatpak-session-helper.c
- system-helper/flatpak-system-helper.c
- tests/test-authenticator.c
This is syntactic sugar added in GLib 2.67.0, which makes it more clearly
correct when we return TRUE after a GDBus error.
I've included a backport so that we don't depend on GLib 2.67.0 for this.
> Use G_DBUS_METHOD_INVOCATION_HANDLED

- common/flatpak-utils-base-private.h
- portal/flatpak-portal.c
Includes part of #4015, so you might want to review that first. I'm happy to drop those commits and rebase a version that uses TRUE/FALSE if maintainers don't consider #4015 to be a clarity improvement.
* common: Add a backport of G_DBUS_METHOD_INVOCATION_HANDLED (from #4015)
* portal: Return G_DBUS_METHOD_INVOCATION_HANDLED where appropriate (from #4015)
* portal: Raise an error if fds are out of range
Previously, we'd silently ignore remapped or sandbox-exposed fds that
were not included with the D-Bus message, which seems unlikely to
work as intended.
* portal: Negative handles are an error
Always treat a negative handle as being out-of-range.
* portal: Log a message when a fd cannot be exposed in the sandbox
> portal: Improve error handling

- app/flatpak-cli-transaction.c
- app/flatpak-quiet-transaction.c
In case the second of these two fails, the first will still have been
added to the transaction. And since it's better to install the renamed
app but not uninstall the old one, than to uninstall the old one but not
install the new one, swap the order.
See also https://github.com/flatpak/flatpak/issues/3991
> app: Swap order of rebase/uninstall calls

- common/flatpak-installation.c
It seems that all `FlatpakTransaction`s add the default dep sources, so
the internal transaction used to list installed refs for updates should
do the same.
This fixes a bug where
`flatpak_installation_list_installed_refs_for_update()` would return an
error saying “The application x requires the runtime y which was not
found” if the app was installed in the user repo, the runtime was
installed in the system repo, and no remote was configured (or one was
configured `xa.noenumerate=true`) in the user repo to provide the
runtime. If a remote was configured, the error wouldn’t be returned, but
the app would be spuriously listed for an update as its runtime couldn’t
be found.
> flatpak-installation: Add default dep sources to list installed refs

- app/flatpak-builtins-build-init.c
- app/flatpak-builtins-build.c
- common/flatpak-dir.c
- common/flatpak-run.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
When installing to an installation we need to find the runtime to use
for the apply-extra-data script from the installation we're targeting,
because that is the one that FlatpakTransaction guaranteed has the
required dependencies (although its possible they came from the
default dependency source too, i.e. the system repos).
In particular, we run into this issue if nothing is installed
anywhere, and then we install an extra-data app into a custom
directory. The transaction will download the runtime, and it
will not be anywhere else. Without this change flatpak only
looked for the dependency in the systam an regular user dirs
where it isn't.
> extra-data: Resolve runtime from the target installation

- .github/workflows/check.yml
There’s no need to fetch the entire git history for OSTree or malcontent
for each CI job. Do shallow clones and don’t fetch tags. This should
reduce the bandwidth requirement for clones in a CI job by potentially a
factor of 10
(https://tecnocode.co.uk/2020/07/09/easily-speed-up-ci-by-reducing-download-size/).
This is slightly complicated by the fact that OSTree is currently being
built from a relatively-recent git commit. Once the flatpak CI can
depend on a tagged OSTree release (say, 2020.8),
```
--branch master --shallow-since 2020-10-27
```
can be changed to
```
--branch v2020.8 --depth 1
```
> check: Limit clone depth for clones done as part of CI builds

- common/flatpak-transaction.c
It seems it's possible for `commit` to be null in the case of uninstallations as the signal is emitted after the ref has been uninstalled and hence it's not possible to get the deploy data and commit:
https://github.com/flatpak/flatpak/blob/09b470c0fd8a5392173b16009c90c51e4582cb4b/common/flatpak-transaction.c#L2890-L2901
If this is supposed to be the case, we need to ensure that this is marked as nullable in the introspection data as the Vala compiler generates null checks that throw assertions if things aren't ever supposed to be null.
> flatpak-transaction: Mark commit param on operation_done nullable

- app/flatpak-builtins-enter.c
- app/flatpak-builtins-kill.c
- app/flatpak-builtins-ps.c
- common/flatpak-instance.c
This commit fixes the crash that happens when trying to kill a container without a name (which is usually started through `flatpak run --command=sh org.freedesktop.Platform`).
> app: fix crash when killing a process without a name

- common/flatpak-dir.c
In elementary OS, we're building our images with some flatpaks pre-installed. To do this, we run noninteractive `flatpak install` commands in the chroot as part of the build scripts. We've bumped into some build failures recently after switching to a version of flatpak with malcontent support built in.
After some debugging, it turns out installations are failing the parental controls checks with errors like `Failed to install org.gnome.Epiphany: Could not connect: No such file or directory` message. I'm assuming this is a failure to connect to the system bus in this method (since there isn't one in the chroot).
Is it reasonable to assume that UID 0 should be allowed to install whatever they want regardless of parental controls? I believe this would fix our issue too.
> flatpak-dir: Allow root to bypass parental controls

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-transaction.c
- common/flatpak-utils.c
Currently we use the deploy data to decide if a runtime is end-of-life,
when calculating which refs are unused and should therefore be removed.
In most cases this works fine. However, it is possible for the
end-of-life metadata to be set on the commit without it being set in the
deploy data. You can diagnose this scenario by comparing "ostree show
--print-metadata-key=ostree.endoflife ...", "ostree show
--print-metadata-key=ostree.endoflife-rebase ...", and "flatpak info
..." since the info command normally prints EOL info from the deploy
data.
I am testing the unused runtimes removal code using an installation of
Endless OS 3.3.16 that has been upgraded, and that OS version included
Flatpak 0.10.1, which was before we started including EOL info in the
deploy data. So I believe that's why …
> Ensure deploy files have complete metadata

- Makefile.am
- app/flatpak-main.c
- configure.ac
- doc/flatpak.xml
- env.d/60-flatpak
- env.d/60-flatpak-system-only
- tests/test-basic.sh
- tests/test-completion.sh
See the commit messages. This installs the existing user-environment-generator as a system-environment-generator too, so that listing flatpaks can work when setting up the parental controls in gnome-initial-setup (which is done outside of a user session).
> Install systemd system-environment-generator

- tests/testlibrary.c
fusermount requires /etc/mtab, but not all Debian buildd chroots
have that file, either as a regular file or as a symlink to
/proc/self/mounts.
(This is similar to commit b07b48e2, but for C code.)
> Skip a test-case if /etc/mtab doesn't exist

- env.d/60-flatpak
- env.d/60-flatpak-system-only
- profile/flatpak.csh
- profile/flatpak.sh
Patch from Mourad De Clerck, via Debian bug <https://bugs.debian.org/975710>.
This avoids gvfs-daemon being started when logging in as root via ssh.
> profile.d: Disable gvfs plugins when listing flatpak installations

- common/flatpak-run.c
If network access is allowed, then we should probably allow name
resolution too.
This should be enough to make nss-resolve work inside flatpak. However,
it cannot be tested with GNOME runtimes, because GNOME runtimes do not
contain systemd. It also cannot be tested with the Fedora 33 flatpak
runtime, because this runtime contains systemd 246, where nss-resolve
uses D-Bus rather than varlink to communicate with systemd-resolved. And
there is no rawhide runtime, and will be no Fedora 34 runtime until F34
is branched. So currently it's not possible to actually test this
without building a custom runtime, which I have not attempted to do. I
have built flatpak myself and verified the resolved socket is mounted
properly inside the sandbox, but it would be better to test if it
actually works …
> WIP: Mount resolved varlink socket in sandbox if network access is allowed

- app/flatpak-builtins-run.c
- common/flatpak-common-types-private.h
- common/flatpak-run.c
- data/org.freedesktop.portal.Flatpak.xml
- doc/flatpak-run.xml
- portal/flatpak-portal.c
- portal/flatpak-portal.h
As with `flatpak run --parent-expose-pids`, this will only work if we have
a working, non-setuid `bwrap`. Systems where user namespace creation is
restricted and `bwrap` needs to be setuid (Debian 10, RHEL/CentOS 7,
Arch Linux `linux-hardened` kernel) will have degraded functionality.
This option is similar to `--expose-pids`, except that instead of making
the subsandbox use a nested pid namespace inside the parent's, it makes
the subsandbox share the parent's pid namespace as-is, so that process
IDs in the parent and the subsandbox are interchangeable. This will
be useful if the parent and the subsandbox communicate via protocols
that assume a global view of the process ID namespace, for example
passing process IDs across an AF_UNIX socket or in shared memory.
In particular, this will be …
> Add an option to share the pid namespace with the parent flatpak

- tests/Makefile.am.inc
From: Alexander Larsson
We need a different rpath for libpreload in this case, because
installed_testdir is not set.
> [1.2.x] Fix tests when installed tests are not enabled

- common/flatpak-dir.c
If an app had no deploy data, and `flatpak_dir_update()` was called with
`opt_subpaths == NULL`, then `arg_subpaths` passed to
`flatpak_dir_system_helper_call_deploy()` would be `NULL`, which causes
an assertion failure from an internal `g_variant_new()` call:
```
g_variant_new_strv: assertion 'length == 0 || strv != NULL' failed
```
Fix that by setting the `subpaths` to an empty array if nothing else is
specified.
> flatpak-dir: Fix crash on updating app with no deploy data or subpaths

- app/flatpak-builtins-build.c
- common/flatpak-dir.c
- common/flatpak-run.c
This is one of two possible approaches to solving #4080, a regression caused by my fixes for CVE-2021-21261. The other option is #4082, but I think I prefer this one.
Of the uses of bwrap listed in https://github.com/flatpak/flatpak/issues/4080#issuecomment-762400524, this fixes `app/flatpak-builtins-build.c` (tested and confirmed to work), `apply_extra_data()` (untested), and `regenerate_ld_cache()` (untested). If this approach is the preferred one, then I would suggest only backporting the first two commits to older branches.
---
* build: Convert environment into a sequence of bwrap arguments
This means we can systematically pass the environment variables
through bwrap(1), even if it is setuid and thus is filtering out
security-sensitive environment variables. bwrap itself ends up being …
> More consistently convert bwrap->envp into --setenv arguments

- app/flatpak-builtins-build.c
- common/flatpak-dir.c
Backport some fixes from #4081
This fixes a regression on systems with setuid bwrap, so they can run e.g. flatpak build.
> Backport LD_LIBRARY_PATH vs setuid bwrap fixes

- common/flatpak-installation.c
`flatpak_deploy_data_get_appdata_content_rating()` returns ownership of
the container.
> flatpak-installation: Fix a leak of the content rating hash table

- doc/flatpak-pin.xml
- doc/reference/Makefile.am
Fixes a regression in version monoculture that occurred since the first attempt in https://github.com/flatpak/flatpak/pull/3760
> doc: Unify DocBook versions again

- tests/Makefile.am.inc
- tests/can-use-fuse.c
- tests/can-use-fuse.h
- tests/testlibrary.c
There are various reasons why distro autobuilder environments might not be able to use FUSE in build-time tests: they might not have fusermount(1), they might be locked-down to be unable to load the FUSE kernel module as a result of security hardening, they might not have the /etc/mtab symlink, they might not have CAP_SYS_ADMIN in their capability bounding set, or they might not have write access to /dev/fuse. Try to check for all of these conditions.
Heavily based on code that I previously contributed to xdg-desktop-portal (flatpak/xdg-desktop-portal#345), as updated by flatpak/xdg-desktop-portal#560.
---
This fixes builds of Flatpak 1.10.1 in Debian's `pbuilder` tool, and I'm hoping it will also fix builds of 1.10.1 on Ubuntu/Canonical Launchpad.
> tests: Disable revokefs if FUSE doesn't work

- common/flatpak-error.h
FLATPAK_ERROR_ALREADY_INSTALLED can be returned from, for example,
flatpak_installation_add_remote(), so document that it applies to
remotes not just apps and runtimes.
> common: Tweak error code docs

- app/flatpak-builtins-build.c
- common/flatpak-dir.c
Backported because I need to maintain 1.2.x in Debian 10, and anyone else still stuck on the same branch might as well be able to share them. I've proposed these patches for inclusion in an updated package via security.debian.org.
---
* build: Convert environment into a sequence of bwrap arguments
This means we can systematically pass the environment variables
through bwrap(1), even if it is setuid and thus is filtering out
security-sensitive environment variables. bwrap itself ends up being
run with an empty environment instead.
This fixes a regression when CVE-2021-21261 was fixed: before the
CVE fixes, LD_LIBRARY_PATH would have been passed through like this
and appeared in the `flatpak build` shell, but during the CVE fixes,
the special case that protected LD_LIBRARY_PATH was removed …
> Backport #4081 for 1.2.x

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-installation.c
- common/flatpak-installation.h
- tests/make-test-app.sh
- tests/test-repo.sh
- tests/testlibrary.c
Currently if a user of libflatpak wants to list the related refs (such
as extensions and plugins) of something, they have three options:
1. They can parse the metadata manually with e.g.
flatpak_remote_ref_get_metadata() and then key-file operations, but
this means re-implementing parts of libflatpak and using key file
strings that are not actually public (FLATPAK_METADATA_KEY_...).
2. They can use flatpak_installation_list_installed_related_refs_sync()
but this only works for installed related refs not remote ones.
3. They can use flatpak_installation_list_remote_related_refs_sync() but
this lists all remotely available related refs, including ones that
may not be compatible with the installed version of the main ref
(because they don't match any of the values in the "versions"
metadata …
> common: Add API for listing related refs of installed ref

- common/flatpak-bundle-ref.h
- common/flatpak-installation.h
- common/flatpak-installed-ref.h
- common/flatpak-instance.h
- common/flatpak-ref.h
- common/flatpak-related-ref.h
- common/flatpak-remote-ref.h
- common/flatpak-remote.h
- common/flatpak-transaction.h
This ensures that we correctly specify C linkage when including flatpak
headers from C++ code.
This should fix fallout from glib's change to include C++ code in its
headers, see https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1935
for discussion.
Fixes https://github.com/flatpak/flatpak/issues/4117
> Add G_BEGIN_DECLS/G_END_DECLS to public headers

- common/flatpak-dir.c
- common/flatpak-run.c
This is a trivial PR that removes two variables that were declared but never actually used.
It was spotted by clang `-Wunused-variable` warning.
> Remove unused variables

- NEWS
In the NEWS file, it says that versions 1.10.1 and 1.10.1 were released in 2020. Shouldn't that read 2021?
> Update dates in NEWS file

- app/flatpak-main.c
- doc/flatpak.xml
Use present tense consistently rather than gerunds for some headings in
"flatpak --help". Also tweak flatpak(1) to use similar wording but with
gerunds.
> Make flatpak --help output use consistent verbiage

- app/flatpak-builtins-enter.c
Otherwise when running software that handles SIGINT, such as gdb or python, pressing ^C would kill flatpak-enter and return control to the shell.
> Let child process handle SIGINT in flatpak enter

- app/flatpak-builtins-enter.c
This is necessary to be able to use ncurses-based programs, such as nano or gdb TUI.
> Expose TERM to flatpak enter

- tests/test-oci.sh
- tests/test-unused.sh
Distributions run these tests on other architectures, but hard-coding
x86_64 to look for in output dooms that to failure.
> tests: Remove hard-coded references to x86_64

- common/flatpak-dir.c
* Disallow `@@` and `@@u` usage in desktop files
From: @refi64 
Fixes #4146.
* dir: Reserve the whole `@@` prefix
If we add new features analogous to file forwarding later, we might
find that we need a different magic token. Let's reserve the whole
`@@*` namespace so we can call it `@@something-else`.
* dir: Refuse to export .desktop files with suspicious uses of `@@` tokens
This is either a malicious/compromised app trying to do an attack, or
a mistake that will break handling of %f, %u and so on. Either way,
if we refuse to export the .desktop file, resulting in installation
failing, then it makes the rejection more obvious than quietly
removing the magic tokens.
---
This is a revised version of #4148, incorporating my suggestions. With this version, installing the app fails:
```
Error: …
```
> Disallow @@ and @@u magic tokens in desktop files

- SECURITY.md
If we can get people to report security issues privately, then we can do coordinated disclosure instead of having to rush to fix issues that are already known to the public.
> Add an initial security policy

- tests/web-server.py
On a decently fast system, some files may be fetched, modified and then
fetched again within the same second. In that case, the web server
replies with a code 304 ("Not modified") to the 2nd query, causing some
tests to fail.
This commit forces the web server to ignore `If-Modified-Since` HTTP
headers, effectively disabling caching in order to mitigate the problem.
> Fix an issue with the test webserver cache

- common/flatpak-oci-registry.c
For reasons unknown, libarchive appears to generate broken gnutar format
tar archives when the archive contains files that are larger than 2 GB.
This commit switches to the pax format to work this around.
This should be a better default as it also removes 256 char filename
length limitation and matches what other libraries are doing, e.g.
Python 3.8 switched to the pax format by default as well.
See https://pagure.io/fedora-infrastructure/issue/9840
> OCI: Switch to pax format for tar archives

- system-helper/flatpak-system-helper.c
The system helper was already correctly using the `NO_INTERACTION` flag
in the D-Bus call flags to determine whether polkit calls from
`flatpak_authorize_method_handler()` should allow interactivity.
However, the system helper was not setting the no-interaction property
on the `FlatpakDir` used in the subsequent operation. When parental
controls are enabled, this sometimes results in polkit allowing
interaction when prompting for the `override-parental-controls` action,
even if the D-Bus call which activated the system helper specified the
`NO_INTERACTION` flag.
> system-helper: Set interactivity on the FlatpakDir from D-Bus call flags

- app/flatpak-builtins-history.c
This checks that the value of the REF field is not an empty string
before calling `flatpak_decomposed_new_from_ref`.  Attempting to
decompose an empty string leads to a validation error and prevents
any history from being printed.
Fixes https://github.com/flatpak/flatpak/issues/4121
> history: Handle transaction log entry with empty REF field

- portal/flatpak-portal.c
Running Flatpak Chromium on NixOS fails with the following error:
> Error calling Spawn(): org.freedesktop.DBus.Error.FileNotFound: Failed to start command: Failed to execute child process “flatpak” (No such file or directory)
Presumably, Chromium calls portal’s `Spawn` method with `FLATPAK_SPAWN_FLAGS_CLEAR_ENV` flag, which also removes `PATH`.
Since NixOS does not install programs to global `/usr/bin` and relies solely on `PATH`, this is probably what prevents `flatpak` command itself from being found.
There is a relevant TODO note in the code about `LD_LIBRARY_PATH` but at least for `PATH`, we can solve the issue by hardcoding the path to the binary.
Fixes: https://github.com/flathub/org.chromium.Chromium/issues/81
cc @JoshuaFern @refi64
> portal: fix flatpak-spawn --clear-env on NixOS

- common/flatpak-instance-private.h
- common/flatpak-instance.c
- common/flatpak-run.c
- tests/Makefile.am.inc
- tests/hold-lock.c
- tests/test-exports.c
- tests/test-instance.c
- tests/testlib.c
- tests/testlib.h
* common: Move flatpak_run_allocate_id() to flatpak-instance
This localizes knowledge of the internal structure of
$XDG_RUNTIME_DIR/.flatpak into the flatpak-instance module.
* instance: Factor out flatpak_instance_get_instances_directory
The only functional change here is that we consistently use
flatpak_get_real_xdg_runtime_dir(), instead of a mixture of
the versions with and without realpath().
* tests: Factor out test setup from test-exports
* tests: Improve error handling for isolated directory setup
If these simple libc function wrappers fail during setup, we want to
crash out.
* tests: Add basic test coverage for GC'ing unused instance directories
---
Required by #4126 and #4093.
> Refactor common/flatpak-instance, add test coverage

- common/flatpak-bwrap-private.h
- common/flatpak-bwrap.c
- common/flatpak-run.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
- tests/testcommon.c
* utils: Display bundled bwrap arguments one per line
This makes them easier to deal with when debugging. Otherwise, it's easy
for the bundled arguments to wrap across 50 or more lines, and with
linebreaks in arbitrary positions that becomes very hard to read.
* run: Sort environment before serializing it into bwrap arguments
This has no practical effect (assuming environment variables are unique),
but it makes it easier to find an environment variable of interest
in a very long bwrap command-line.
---
I think this is perhaps more readable, although still not great. Example output:
```
(flatpak run:107875): flatpak2-DEBUG: 20:32:13.169: bwrap --args 35 = ... 
(flatpak run:107875): flatpak2-DEBUG: 20:32:13.169:     --fd=34
(flatpak run:107875): flatpak2-DEBUG: 20:32:13.169: …
```
> WIP: Make bwrap commands more debuggable

- tests/test-basic.sh
* test-basic: Don't fail if head -2 exits before flatpak does
The output might be written to the pipe by `flatpak --help` and/or read
from the pipe by `head -2` in more than one batch. If `head -2` reads
the first two lines before `flatpak --help` has written everything, it
will exit, causing the pipe to have no process at the read end. This
results in `flatpak --help` being killed by `SIGPIPE` next time it tries
to write to the pipe, because it has not opted out of this behaviour
(as shell tools usually shouldn't).
We're running under `set -o pipefail`, so this causes a nonzero exit
status that makes the test fail. Worse, this failure is intermittent,
because `head -2` *usually* doesn't exit until `flatpak --help` has
already written out everything it is going to write - it depends on …
> Fix an intermittent test failure when head -2 exits before flatpak does

- common/flatpak-utils.c
- tests/testcommon.c
* utils: Quote empty strings when debug-logging argv
If an argument takes a value, and the value is empty, then it's
misleading to quote `{"--foo", "--empty", "", "--bar"}` as
`--foo --empty  --bar`. It's better to get `--foo --empty '' --bar`.
* tests: Test flatpak_quote_argv and flatpak_argument_needs_quoting
> utils: Quote empty strings when debug-logging argv, and add a test

- app/flatpak-builtins-build.c
- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-dir.c
- common/flatpak-instance-private.h
- common/flatpak-instance.c
- common/flatpak-run-private.h
- common/flatpak-run.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
- tests/test-exports.c
- tests/test-instance.c
- tests/testcommon.c
Part of #4091.
This no longer depends on #4126, and instead contains the parts of #4126 that it needs, so that we can try to land this feature without being blocked by the concerns about symlink attacks in the `XDG_RUNTIME_DIR`.
The `g_get_user_runtime_dir()` on the host now looks like this:
```
real host g_get_user_runtime_dir()
\- app
\- com.example.App (gets mounted as XDG_RUNTIME_DIR/app/com.example.App as before)
\- .flatpak
\- 123 (instance-specific directory, already used)
\- 456 (instance-specific directory, already used)
\- com.example.App (per-app directory, not visible in sandbox, new)
\- .ref (locked non-exclusively by app, new)
\- tmp (gets mounted as /tmp in app sandbox, new)
```
The shared `/tmp` is only used for `flatpak run`, not for `flatpak build` (which reinvents a lot …
> Share /tmp between instances of the same app

- common/flatpak-dir.c
- common/flatpak-run.c
- portal/flatpak-portal.c
- portal/flatpak-portal.h
- session-helper/Makefile.am.inc
- session-helper/flatpak-session-helper.c
- session-helper/flatpak-session-helper.h
- system-helper/Makefile.am.inc
- system-helper/flatpak-system-helper.c
- system-helper/flatpak-system-helper.h
- tests/test-update-portal.c
* session-helper: Move D-Bus names and paths to a header file
* system-helper: Move D-Bus names and paths to a header file
* portal: Define constants for the D-Bus names and path
---
This mitigates any typos in these names that might otherwise creep in, and also provides a somewhat canonical name to use for these strings in other projects.
The new headers are not (yet?) installed or part of the API, but they're self-contained and can be copied into dependent projects.
> Define macros for various D-Bus names

- .github/workflows/check.yml
- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-instance-private.h
- common/flatpak-instance.c
- common/flatpak-run.c
- doc/flatpak-build-finish.xml
- doc/flatpak-build.xml
- doc/flatpak-metadata.xml
- doc/flatpak-override.xml
- tests/Makefile.am.inc
- tests/test-completion.sh
- tests/test-exports.c
- tests/test-instance.c
Fixes #4091.
The interesting subset of the host filesystem is now:
```
real host g_get_user_runtime_dir()
\- app
\- com.example.App (gets mounted as XDG_RUNTIME_DIR/app/com.example.App as before)
\- .flatpak
\- 123 (instance-specific directory, already used)
\- 456 (instance-specific directory, already used)
\- com.example.App (per-app directory, new in #4093)
\- .ref (locked non-exclusively by app, new in #4093)
\- tmp (gets mounted as /tmp in app sandbox, new in #4093)
\- dev-shm (symlink to /dev/shm/flatpak-com.example.App-abcdef, new)
real host /dev/shm
\- flatpak-com.example.App-abcdef (or similar unpredictable name, new)
\- .flatpak-tmpdir
```
As with #4093, the shared `/dev/shm` is only used for `flatpak run`, not for `flatpak build` (which reinvents a lot of `flatpak_run_app()`), …
> Make /dev/shm shareable between app instances

- app/flatpak-builtins-build.c
- common/flatpak-bwrap-private.h
- common/flatpak-bwrap.c
- common/flatpak-context.c
- common/flatpak-dir.c
- common/flatpak-instance-private.h
- common/flatpak-instance.c
- common/flatpak-run.c
Fixes #4120.
The `XDG_RUNTIME_DIR` on the host now looks like this:
```
real host XDG_RUNTIME_DIR
\- app
\- com.example.App (gets mounted as XDG_RUNTIME_DIR/app/com.example.App as before)
\- .flatpak
\- 123 (instance-specific directory, already used)
\- 456 (instance-specific directory, already used)
\- com.example.App (per-app directory, from #4093)
\- tmp (gets mounted as /tmp in app sandbox, from #4093)
\- xdg-run (gets mounted as XDG_RUNTIME_DIR in app sandbox, new)
```
In this implementation, we never garbage-collect `xdg-run`, just like the pre-existing `$XDG_RUNTIME_DIR/app/$FLATPAK_ID`. If we wanted to GC it, the procedure would be the same as for `/tmp` (#4093).
I have not removed the special handling of `$XDG_RUNTIME_DIR/app/$FLATPAK_ID`. Those are slightly redundant now, but …
> Create a shared XDG_RUNTIME_DIR for each app-ID

- portal/flatpak-portal.c
In D-Bus, handles are defined to be unsigned, but in GVariant, for some
reason they're signed. Make sure they aren't negative, which could
result in a NULL dereference for fds.
A handle used in the conventional way will never legitimately be
negative (in GVariant's interpretation) or have its high bit set
(in D-Bus' interpretation), because file descriptors are signed 32-bit
integers, so an array of distinct file descriptors can never be long
enough for the distinction between signed and unsigned to matter.
In practice fds are limited by the kernel to several orders of
magnitude fewer than that anyway.
Fixes: 3ebf371f "run: Allow caller to replace /app and/or /usr"
> portal: Reject negative handle numbers

- common/flatpak-oci-registry.c
The intention here seems to have been that failing to close the http
stream provokes a warning but does not make the function fail, but we
were setting the wrong error, resulting in a NULL dereference if closing
the http stream somehow fails.
> oci-registry: Fix error reporting

- revokefs/writer.c
scan-build detected that response_size is uninitialized here, presumably
a typo for response_data_size.
> revokefs: Use the right variable name in an error message

- common/flatpak-transaction.c
scan-build detected that mark_op_resolved() can be called with
op->resolved_commit == commit, in which case we incorrectly freed the
string before allocating the new copy.
> transaction: Avoid a possible use-after-free

- app/flatpak-builtins-document-list.c
- app/flatpak-builtins-history.c
- app/flatpak-builtins-list.c
- app/flatpak-builtins-permission-list.c
- app/flatpak-builtins-permission-show.c
- app/flatpak-builtins-ps.c
- app/flatpak-builtins-remote-list.c
- app/flatpak-builtins-remote-ls.c
- app/flatpak-builtins-repo.c
- app/flatpak-builtins-search.c
- app/flatpak-cli-transaction.c
- app/flatpak-table-printer.h
Fixes: https://github.com/flatpak/flatpak/issues/4223  
Fixes: https://github.com/flatpak/flatpak/issues/4224
---
@setharnold, you can probably ignore any memory leaks where a FlatpakTablePrinter is leaked: this should fix all of them, and in any case I think they're all in contexts where O(1) bytes get leaked by a non-long-running process.
> app: Use autocleanup for FlatpakTablePrinter

- common/flatpak-dir.c
Fixes #4234
I tested this against the 1.10.2 tag and master branch with my test case.
Let me know if you have questions or I need to do anything else.
I can also submit a PR for the 1.10.x branch if you want (in addition or instead)
> flatpak_dir_find_local_related_for_metadata: Skip invalid branch

- app/flatpak-builtins-enter.c
- app/flatpak-builtins-repair.c
- app/flatpak-builtins-search.c
- app/flatpak-builtins-utils.c
- app/flatpak-quiet-transaction.c
- common/flatpak-dir.c
- common/flatpak-ref-utils.c
- tests/test-instance.c
- tests/testcommon.c
- tests/testlibrary.c
scan-build has a lot of false positives for this codebase because it doesn't understand [`__attribute__((__cleanup__))`](https://bugs.llvm.org/show_bug.cgi?id=3888) or GLib's GError conventions, so we can't make Flatpak fully scan-build-clean or blindly believe what scan-build says - but some of the things it reports are meaningful.
For issues that can actually matter, I've opened separate MRs #4226, #4227, #4228 and #4229. This lower-priority MR collects changes that don't have any actual effect, mostly removal of dead code.
Any commit here can be cherry-picked if there's some problem that prevents merging the whole branch.
---
* Fix various unused variables detected by scan-build
scan-build has a lot of false positives for this codebase because it
doesn't understand …
> Fix cosmetic issues detected by scan-build

- app/flatpak-builtins-build-update-repo.c
- common/Makefile.am.inc
- common/flatpak-prune-private.h
- common/flatpak-prune.c
- data/flatpak-variants.gv
- tests/Makefile-test-matrix.am.inc
- tests/Makefile.am.inc
- tests/test-prune.sh
This is an optimized version of ostree_repo_prune() specialized for archive mode repos. It is faster and uses less memory so that we can prune larger repos (like flathub) in a realistic timeframe.
The primary reason it is faster is that it creates and uses a `.commitmeta2` file for each commit, containing information about what objects are reachable from that commit. This means incremental prunes need only traverse over newly created commits.
Secondly, it uses the variant parser compiled accessors for the various GVariants that are involved in the prune which is quite a bit faster, especially if the repo is very large.
It also merges the scan-for-all-objects and prune-unreachable objects phases, which means that we don't have to allocate a hashtable for all the objects in the entire repo …
> Improve performance of prune

- tests/libtest.sh
If the tests are run as root, the system helper is not used even when
commands are run with `--system`. This means a different cache path is
used (see `_flatpak_dir_ensure_repo()`). The tests did not accommodate
for that.
> tests: Fix test-summaries.sh when running tests as root

- app/flatpak-builtins-install.c
- app/flatpak-builtins-run.c
- app/flatpak-builtins-utils.c
- app/flatpak-cli-transaction.c
- app/flatpak-table-printer.c
- app/flatpak-table-printer.h
- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-installation.c
- common/flatpak-installation.h
- common/flatpak-transaction-private.h
- common/flatpak-transaction.c
This allows flatpak_installation_list_remote_refs_sync_full() to list
refs for all arches on remotes that use the new subsummary format.
Fixess #4252
> Add FLATPAK_QUERY_FLAGS_ALL_ARCHES for list_remote_refs()

- tests/testcommon.c
If we use x86_64 and i386 in places where any architecture would do,
it's harder to recognise whether the test is assuming every machine
is x86 and would fail elsewhere (e.g. as fixed in #4142). When just
parsing abstract strings where any syntactically valid architecture
would do, let's use rare/niche architectures that none of the maintainers
are running on, so that hard-coding x86_64 or i386 stands out more.
I've used mips64 and m68k because they happen to be the same length as
x86_64 and i386, avoiding re-indentation.
> testcommon: Use unusual architectures where it doesn't matter

- app/flatpak-complete.c
- app/flatpak-complete.h
- app/flatpak-table-printer.c
- app/flatpak-table-printer.h
- common/flatpak-dir.c
- common/flatpak-utils.c
* completion: Always pass a format string to flatpak_completion_debug
In principle this could have been subject to a format string attack
via an argument containing %n, although in practice the code that uses
this format string is #if 0.
* Add missing G_GNUC_PRINTF attributes
This allows callers to be checked for mismatches between format string
and arguments, and also means gcc can assume that the format string and
the arguments match up correctly when forwarding them to functions
like g_strdup_vprintf, removing the need to suppress -Wformat-nonliteral
warnings.
* Don't disable -Wformat-nonliteral unnecessarily
These functions were already annotated with G_GNUC_PRINTF, so gcc
can assume that the format string and arguments match up.
---
Noticed while looking into unrelated issue #4286.
> Make better use of G_GNUC_PRINTF

- common/flatpak-context-private.h
- common/flatpak-context.c
- portal/flatpak-portal.c
- portal/flatpak-portal.h
- tests/Makefile.am.inc
- tests/mock-flatpak.c
- tests/test-context.c
- tests/test-portal.c
- tests/testlib.c
- tests/testlib.h
* portal: Don't leak fd used for serialized environment
Otherwise we'll run out of file descriptors eventually, when starting
a sufficiently large number of subsandboxes.
Resolves: flatpak/flatpak#4285  
Fixes: aeb6a7ab "portal: Convert --env in extra-args into --env-fd"
* portal: Use a GArray to store fds
This will allow us to add additional mapping entries for fds to be
used internally by `flatpak run`, in particular --env-fd.
Defer the second pass through the fd array until the last possible
moment, so that any extra fds we want to add (like the --env-fd) have
already been added by then.
Helps: flatpak/flatpak#4286
* portal: Remap --env-fd into child process's fd space
Just because we can allocate a new, unused fd in the portal's fd space,
that doesn't mean that fd number is going to …
> portal: Fix --env-fd regressions

- README.md
We've moved from Freenode to Matrix, see:
https://discourse.flathub.org/t/should-flathub-flatpak-move-to-another-communication-channel-if-so-where-and-why/1443
https://lists.freedesktop.org/archives/flatpak/2021-May/002127.html
> README: Update chat room link

- common/flatpak-transaction.c
If the deploy metadata is missing for the locale runtime of an app which
is being uninstalled, flatpak will currently abort on an assertion
failure.
Prevent that abort, at the expense of not uninstalling the locale
runtime. A better fix could be found for this in future.
Fixes: #3943
> transaction: Don’t abort on uninstall if deploy metadata is missing

- .github/workflows/check.yml
For whatever reason parts of mono is installed, but the repo is not
configured so there is a version conflict on update:
libglib2.0-cil is already the newest version (2.12.45-0xamarin19+ubuntu1604b1).
libglib2.0-cil set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
libglib2.0-cil-dev : Depends: libglib2.0-cil (= 2.12.10-6) but 2.12.45-0xamarin19+ubuntu1604b1 is to be installed
E: Unable to correct problems, you have held broken packages.
> CI: Add mono apt repo to fix build

- data/org.freedesktop.portal.Flatpak.xml
The client-side proposed for flatpak-spawn (flatpak/flatpak-xdg-utils#39) uses `--app-path`, but the actual implementation on D-Bus uses file descriptor passing and an option named `app-fd`, so the documentation of the D-Bus interface should be written in terms of `app-fd`.
Fixes: 3ebf371f "run: Allow caller to replace /app and/or /usr"
> portal: Fix a typo in D-Bus API documentation

- .github/workflows/check.yml
Originally from @alexlarsson.
---
For whatever reason parts of mono is installed, but the repo is not
configured so there is a version conflict on update:
libglib2.0-cil is already the newest version (2.12.45-0xamarin19+ubuntu1604b1).
libglib2.0-cil set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
libglib2.0-cil-dev : Depends: libglib2.0-cil (= 2.12.10-6) but 2.12.45-0xamarin19+ubuntu1604b1 is to be installed
E: Unable to correct problems, you have held broken packages. …
> [1.10.x] CI: Add mono apt repo to fix build

- app/flatpak-builtins-document-export.c
- common/flatpak-dir.c
- common/flatpak-utils.c
- portal/flatpak-portal.c
Cherry-picked from commit 404d7c6941baf63d1b3ccbe9ee9d34f3ff12f35f by @mwleeds, originally part of #4254.
Some (all?) of the other leak fixes in #4254 should probably go to 1.10, but fast-tracking this one avoids conflicts in a backport of #4283. It applies cleanly and I've checked that the changes are correct.
> [1.10.x] Fix several memory leaks

- common/flatpak-transaction.c
Fix an “The application foo requires the runtime bla which was not
found” error when using libflatpak (not the CLI) to install an
application whose runtime is provided by a different repo, and which is
for a non-default architecture.
This is a follow-up to commit f2ff664ff.
> flatpak-transaction: Fix finding runtime with non-default remote+arch

- portal/flatpak-portal.c
This fixes two related bugs in the Flatpak portal, which I introduced while fixing CVE-2021-21261:
* The temporary file descriptor used to transfer environment variables was leaked. If enough apps start a subsandbox with `flatpak-spawn --env=...` or equivalent D-Bus calls, the portal will run out of file descriptors and become unusable. (#4285)
* The file descriptor used for the serialized environment was not correctly remapped into the child process's fd space. If the subsandbox was started with `flatpak-spawn --forward-fd=...` then this could result in the forwarded fd and the serialized environment getting mixed up; if it does, `flatpak run` will try to read environment variables from one of the fds from `--forward-fd` instead of from the intended temporary file, resulting in failure …
> [1.10.x] Fix portal --env-fd regressions in 1.10.0

- tests/Makefile.am.inc
To be excluded from tarball releases, generated files need to be in
nodist_ lists of sources every time they appear.
Fixes: 412c1577 "portal: Add some test coverage"
> build: Don't include gdbus-codegen-generated files in tarball

- tests/test-oci.sh
- tests/test-unused.sh
Distributions run these tests on other architectures, but hard-coding
x86_64 to look for in output dooms that to failure.
(cherry picked from commit ba381ae9368c0e6e233c52254e698f5f64903036)
---
Backported from 1.11.x. I've been applying this to 1.10.x in Debian for a while, since failing tests are a release blocker there.
> [1.10] tests: Remove hard-coded references to x86_64

- system-helper/flatpak-system-helper.c
* system-helper: Fix deploys of local remotes
For updates in remotes with a local (file:) uri we just do a deploy
with a LOCAL_PULL flag set and an empty arg_repo_path. However, our
arg_repo_path checking at some point seemed to stop properly handling
the case where it is empty. I got it to report "No such file" wich
broke the tests.
(cherry picked from commit 49e8bfcea516e96eb950109d0fa45811a352a517)
Fixes: #4339
Tested-by: [Milan Crha](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1204#note_1204340)
> Backport 49e8bfce "system-helper: Fix deploys of local remotes" to 1.10.x

- .github/FUNDING.yml
Flatpak can now accept donations on the OpenCollective platform, which can then be used to fund development, or to further the project's goals in other ways. I plan to send an email to the mailing list soon to announce this and solicit feedback on how best to go about raising and distributing funds.
This idea was discussed on the Matrix channel and via email already, and well received.
> .github: Add Sponsor button

- common/flatpak-exports-private.h
- common/flatpak-exports.c
- common/flatpak-utils-base.c
- tests/test-exports.c
This branch makes `exports->host_fd` more consistently used (hence more realistic), and uses it to expand test coverage.
My ulterior motive for this is that I want to use the more realistic `exports->host_fd` to [unit-test Steam's pressure-vessel tool](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/337), which contains a fork of various bits of Flatpak, including FlatpakExports; but I think this extra coverage is an improvement for Flatpak too, so everyone wins.
---
* tests: Add test coverage for a mock Fedora-like system
In particular this tests commit 3aaea7d2 "Expose /var/usrlocal if
"--filesystem=host" is specified" and checks that /var/usrlocal is
counted as part of --filesystem=host-usr.
* exports: Close mock host fd when destroyed
Previously this was …
> Improve exports test coverage

- common/flatpak-run.c
- tests/test-run.sh
We use `bwrap --setenv XDG_RUNTIME_DIR` to set it to `/run/user/UID`,
regardless of what it is on the host system, but the changes made
to resolve CVE-2021-21261 unintentionally broke this by overwriting it
with the user's XDG_RUNTIME_DIR.
In practice this worked for most people, who either have
XDG_RUNTIME_DIR set to the same value we use (which is the conventional
setup from systemd-logind and elogind), or entirely unset (if they do not
have systemd-logind or elogind). However, it broke Wayland and other
XDG_RUNTIME_DIR-based protocols for people who intentionally set up an
XDG_RUNTIME_DIR that is different.
Resolves: https://github.com/flatpak/flatpak/issues/4372
> run: Don't let XDG_RUNTIME_DIR from user override the value we set

- common/flatpak-run.c
- tests/test-run.sh
We use `bwrap --setenv XDG_RUNTIME_DIR` to set it to `/run/user/UID`,
regardless of what it is on the host system, but the changes made
to resolve CVE-2021-21261 unintentionally broke this by overwriting it
with the user's XDG_RUNTIME_DIR.
In practice this worked for most people, who either have
XDG_RUNTIME_DIR set to the same value we use (which is the conventional
setup from systemd-logind and elogind), or entirely unset (if they do not
have systemd-logind or elogind). However, it broke Wayland and other
XDG_RUNTIME_DIR-based protocols for people who intentionally set up an
XDG_RUNTIME_DIR that is different.
Fixes: 6d1773d2 "run: Convert all environment variables into bwrap arguments"  
Resolves: https://github.com/flatpak/flatpak/issues/4372
---
Should not be merged until after #4373 …
> [1.10.x] run: Don't let XDG_RUNTIME_DIR from user override the value we set

- app/flatpak-builtins-install.c
- app/flatpak-builtins-utils.c
- app/flatpak-builtins-utils.h
The install command can search available remotes for a specified flatpak
when a remote wasn't specified. In case only one remote is configured,
or in case only one of the configured remotes matches the ref specified,
we currently prompt the user to confirm use of the remote anyway (unless
-y/--assumeyes was used). Skip this prompt even when -y/--assumeyes was
not used, since the remote to use will still effectively be confirmed
when the list of refs to be installed is presented for confirmation.
Fixes https://github.com/flatpak/flatpak/issues/4364
> install: Avoid a superfluous prompt to choose the only remote

- common/flatpak-dir.c
This is part of fix to https://github.com/flathub/org.flatpak.Builder/issues/5 which involves org.flatpak.Builder to allow flatpak-builder running in flatpak to tell flatpak which paths to write into export files
> Support dynamic export path into scripts

- common/flatpak-dir.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
g_get_language_names() only returns the language names for the
LC_MESSAGES category, so mixed locale scenarios would result in missing
languages. Now, the languages are listed for each individual category.
Note that this issue was only present with the user installation. For
the system installation, the locales were queried from localed, and all
categories were checked.
Fixes #3712.
> Retrieve user languages for all locale categories

- common/flatpak-exports.c
- tests/test-exports.c
In Yocto systems /var/tmp is a symlink to /var/volatile/tmp
because in its implementation of read-only rootfs /var is read-only
so /var/volatile is mounted as a tmpfs
and a subset of the paths point into it.
This would result in flatpak emitting mount arguments of
`--symlink ../var/volatile/tmp /var/tmp --bind /var/volatile/tmp /var/volatile/tmp`
which fails because flatpak has already added `--dir /var/tmp`
and the call to symlink fails with EEXIST.
This is fixed by blacklisting /var/tmp from symlink exports
in the same way /tmp is, so the bind is emitted as
`--bind /var/tmp /var/tmp`, which results in /var/volatile/tmp
being mounted into /var/tmp.
> Handle /var/tmp mounts when it is a symlink

- common/flatpak-run.c
- session-helper/flatpak-session-helper.c
Fixes #4419.
Since the file should only affect networking, it makes sense to bind-mount it only if network is shared.
> run: Bind-mount gai.conf from host if present

- common/flatpak-oci-registry.c
For reasons unknown, libarchive appears to generate broken gnutar format
tar archives when the archive contains files that are larger than 2 GB.
This commit switches to the pax format to work this around.
This should be a better default as it also removes 256 char filename
length limitation and matches what other libraries are doing, e.g.
Python 3.8 switched to the pax format by default as well.
See https://pagure.io/fedora-infrastructure/issue/9840
(cherry picked from commit b90d638601f6331e689482fe67552b82de71d135)
> [flatpak-1.10.x] OCI: Switch to pax format for tar archives

- .github/workflows/check.yml
As per https://github.com/actions/virtual-environments/issues/3287 the support for ubuntu-16.04 stopped working on september 20:th, so our CI job stopped starting.
This test was useful to detect changes that made flatpak no longer build with ancient glib versions. However, at some point maybe we no longer care about glib versions that old? Should we just drop this, or do we try to find some kind of replacement? 
Maybe we even bump the glib req to something we test.  We currently require 2.44, but both ubuntu 18.08 and rhel8 seems to have 2.56.4, whereas ubuntu 16.04 has 2.48.2, and rhel7.9 has  2.56.1.
I wouldn't mind bumping this to 2.56.0, released march 2018?
@debarshiray  @smcv @mwleeds opinions?
> Drop old-glib ci test as ubuntu 16.04 is no longer available

- common/flatpak-dir.c
These checks were broken in commit d762a2f, as the commit failed to
consider the fact that `flatpak_dir_check_parental_controls()` is run
both in the `flatpak` CLI process run by the user, but also in the
`flatpak-system-helper` process which always runs as root, and which
handles any installations done on the system repository.
As a result, parental controls were not working for the system
repository.
Fix that by limiting the scope of the check to only pass if running
without the system helper. flatpak calls from root never go through the
system helper.
Fixes: #4418
> flatpak-dir: Fix parental controls checks for root

- icon-validator/validate-icon.c
On musl-based systems, /etc/ld.so.cache does not exist, causing icon validation to fail.
This has been improperly reported at [1] instead of Flatpak repo.
[1] https://github.com/flathub/com.valvesoftware.Steam/issues/638
> icon-validator: Mount ld.so.cache only if it exists

- env.d/60-flatpak
- profile/flatpak.sh
This is meant to be applied after https://github.com/flatpak/flatpak/pull/4448
The second patch was practically re-written and is not a straight cherry-pick of commit afe7f2bf78b97579c652989d2577d05229f56256 It might be good to take a close look at it. :)
> [flatpak-1.8.x] profile.d: Disable gvfs plugins when listing flatpak installations

- tests/test-sideload.sh
The soup backend and the curl backend give slightly different error
messages, so we need to tweak the 404 assert check to match both.
> tests: Fix test-sideload.sh if ostree is built with curl backend

- common/flatpak-dir.c
I know 1.2.x is unsupported upstream, but I have to maintain a fork of 1.2.x for about 1 more year for Debian 10, so I might as well have these upstream.
---
* Disallow @@ and @@u usage in desktop files
From: Ryan Gonzalez
(cherry picked from commit 652a28ffab67cb6cd7d12dc3a93979bcd3731c7f)
* dir: Reserve the whole @@ prefix
(cherry picked from commit 1e7e8fdb24b51078f4c48e0711e24a14930ba1f0)
* dir: Refuse to export .desktop files with suspicious uses of @@ tokens
(cherry picked from commit 46b3ede5241561c7d588951048c687c5075a3eac)
> Backport CVE-2021-21381 fixes to 1.2.x

- tests/test-bundle.sh
- tests/test-run.sh
https://github.com/flatpak/flatpak/commit/a99b748931e6444dadb0d0c8c1565da23f755800 introduced an environment variable for changing the flatpak path for exports. On NixOS, we do not have a stable path we could use so we used to patch Flatpak to use `flatpak` program from `PATH`. With the recent change, we drop our downstream patch in favour of setting the environment variable to `flatpak` but the tests do not expect that.
This is the test part of our former downstream patch so that tests can pass with exports using `flatpak` instead of an absolute path. It still expects the binary path to end with `flatpak` so arbitrary `$FLATPAK_BINARY` will not work but we do not pass the environment variable to tests so we cannot do much better.
> tests: Allow FLATPAK_BINARY=flatpak for exports

- tests/Makefile.am.inc
Files that are generated manually by a maintainer and committed to git
should be in the srcdir, not the builddir.
> tests: Generate Makefile-test-matrix.am.inc in $(srcdir)

- session-helper/flatpak-session-helper.c
- session-helper/flatpak-session-helper.h
* session-helper: Move FlatpakHostCommandFlags to header file
* session-helper: Add FLATPAK_HOST_COMMAND_FLAGS_NONE
---
This is similar to how the portal has behaved since e196efbf6b. I intend to make use of this in `flatpak-xdg-utils` and Steam's `pressure-vessel`.
> session-helper: Move FlatpakHostCommandFlags to header file

- common/flatpak-dir.c
- tests/testlibrary.c
When we create origin remotes for apps installed via .flatpakref files,
we set xa.noenumerate=true and
xa.main-ref=app/com.example.App/arch/branch so that the remote is only
used for the app it was intended for. This is implemented in
flatpak_dir_list_remote_refs() by only listing refs in the remote which
are already installed. This works fine after the ref is installed but in
the short timespan between when the origin remote is created and the app
is installed from it, it means that the remote appears as empty.
The use case where I ran into this is in attempting to use
flatpak_installation_fetch_remote_ref_sync() in the gnome-software
flatpak plugin, in the handling of flatpakref files, which is intended
to just display information to the user and let them decide whether to
install the …
> dir: Don't mask the main ref of a noenumerate remote

- common/flatpak-run.c
https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/ServerStrings/ says:
> If the string starts with / or unix: the remaining address string is taken as UNIX socket name.
but previously the string was only taken to be a UNIX socket name if it began with "unix:". This is an issue in practice with [WSLg](https://github.com/microsoft/wslg) which sets `$PULSE_SERVER` to `/mnt/wslg/PulseServer`, without a `unix:` prefix.
The first patch in this series addresses this problem. Without this patch, the `$PULSE_SERVER` environment variable is ignored and Flatpak falls back to the default socket paths. With this patch, the `$PULSE_SERVER` environment variable is respected and Flatpak apps with `--socket=pulseaudio` can talk to the miraculous WSLg PulseAudio daemon (which forwards …
> Support PulseAudio socket path without unix: prefix

- common/flatpak-dir.c
This commit is a follow-up to "Fix implementation of xa.noenumerate
remote option" since that turned out to break
flatpak_installation_fetch_remote_ref_sync() in some cases. I didn't see
it at the time, but flatpak_decomposed_get_collection_id() explains that
the collection ID shouldn't be set on FlatpakDecomposed objects, even
when the remote has a collection ID set, unless they are being used to
enumerate refs from a file:// URI rather than a configured remote. So
this commit changes list_remote_refs() and list_all_remote_refs() to
keep the xa.noenumerate implementation working and to get
fetch_remote_ref_sync() working again (since the latter uses
flatpak_decomposed_new_from_parts() and thus doesn't set a collection ID
on the FlatpakDecomposed object used for comparison).
> dir: Fix an issue with fetch_remote_ref_sync()

- app/flatpak-builtins-search.c
This commit changes the search command to properly output the app ID for
IDs that end in .desktop, e.g. to print org.telegram.desktop rather than
org.telegram.
Fixes https://github.com/flatpak/flatpak/issues/4535
> search: Don't strip .desktop suffix overzealously

- app/flatpak-cli-transaction.c
flatpak_fancy_output() determines whether the output we write is
intended for e.g. a tty or e.g. a log file, the latter being "not
fancy". Currently we write carriage return characters in the not fancy
case, but change that to new lines, which are interpreted correctly by
editors such as vim (whereas a carriage return shows up as ^M since it
is not the correct newline character on Unixy operating systems).
> app: Don't use carriage return for non-fancy output

- Makefile.am
- profile/flatpak.fish
Technically, Fish users can already make this work using
https://github.com/edc/bass, but it's also nice to have this working on
an out-of-the-box Flatpak installation.
Fixes #3109.
Signed-off-by: Ryan Gonzalez <ryan.gonzalez@collabora.com>
> Add a profile script for Fish

- app/flatpak-builtins-build-update-repo.c
Spotted this by code inspection. Ignoring such refs was clearly the
intended behavior based on the comment.
> build-update-repo: Don't try to generate deltas of unknown refs

- common/flatpak-run.c
- doc/flatpak-run.xml
- tests/libtest.sh
- tests/test-run.sh
- tests/testlib.c
- tests/testlibrary.c
This gives new support for the new XDG_STATE_HOME addition to XDG_BASE_DIRS which allows applications to use this without breaking because they would assume $HOME/.local/state which may be unavailable to the flatpak
This adds it as .local/state as to make --persist=.local/state the same behaviour as in new flatpak. This in turn means that the transition should be seamless between old and new flatpak.
This also has the benefit of working if the application doesn't follow XDG spec thanks to --persist=.local/state.
This fixes flatpak#4477
> Add XDG_STATE_HOME and HOST_XDG_STATE_HOME env variables

- common/flatpak-utils-http.c
The original commit (9865ed8989befe9653fb3cd919fb5518b09274d2) disabling
it claimed it fixed OCI downloads. This no longer seems to be a problem.
This has also exposed new bugs as some servers will send
gzip compressed data when the client does not send Accept-Encoding.
If we leave this enabled that issue goes away.
> Re-enable HTTP compression

- app/flatpak-cli-transaction.c
- app/flatpak-quiet-transaction.c
Currently if the user specifies a ref to install that has been renamed
via the end-of-life-rebased mechanism, for example "flatpak install
com.visualstudio.code.oss", Flatpak erroneously tries to install both
the old and new versions of the app. This happens because the code
handling end-of-life-rebase conditions is written assuming the rebased
app is being updated rather than installed for the first time.
Specifically, in FlatpakCliTransaction and FlatpakQuietTransaction, in
end_of_lifed_with_rebase(), we treat a failure of
flatpak_transaction_add_uninstall() as fatal and return FALSE from the
signal handler, which means that the install operation that triggered
the signal will not be skipped (see the docs for
FlatpakTransaction::end-of-lifed-with-rebase).
So, instead check for the …
> app: Fix behavior when installing end-of-life-rebased ref

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-installation.c
- common/flatpak-transaction.c
- tests/testlibrary.c
It can happen that a related ref is installed from a different remote
than the thing it's related to. We always want to update things from
their origin remote. However as of now FlatpakTransaction resolves the
commit of a related ref to the one available from the main ref origin,
and later sets the remote for the operation to the installed origin (see
commit 6793d90b8). In case there is a newer commit in the main ref
origin than the installed origin, this leads to an update operation
being erroneously created, only to then error out with an HTTP 404
error, because the commit from the main ref origin is being pulled from
the installed ref origin. For specific steps to reproduce see
https://github.com/flatpak/flatpak/issues/3128#issuecomment-948948040
So, ensure that when a …
> Ensure refs are updated from their origin

- common/flatpak-dir.c
- common/flatpak-transaction.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
- tests/test-repo.sh
Many of the fields allowed in flatpakrepo files are not allowed in
flatpakref files, e.g. Comment, Description, Homepage, etc. So there is
no straightforward way to ensure those are set correctly when the user
installs something with a flatpakref file. However in most cases the
repo specified by the RuntimeRepo key is also the repo providing the
main ref, so in those cases it makes sense to utilize all the metadata
provided in the flatpakrepo file when creating a remote to provide
updates for the app being installed. We were already doing this when the
SuggestRemoteName key was unset; this commit makes it so that we utilize
that metadata also when SuggestRemoteName is present.
> transaction: Utilize runtime repo info for origin remote

- app/flatpak-builtins-build-finish.c
- common/flatpak-dir.c
- common/flatpak-utils.c
- tests/make-test-app.sh
- tests/test-run.sh
build-finish: Export appstream metainfo into a single directory
This is similar to what is done for desktop files and allows
applications like desktop or mobile shell to use a flatpak's metainfo to retrieve e.g.  required
input controllers or the supported screen sizes. Similar to what can be
done for non-flatpak'ed apps by looking at `/usr/share/{metainfo,appdata}`.
This information is e.g. useful for desktop and mobile shells to figure out if an
application is currently usable (does meed the current input and screen 
requirements) and hence where it should be placed in a menu.
Since flatpak moves the metadata from `metainfo/` to `appdata/` during build
we only need to export files from that single directory.
> build-finish: Export appstream metainfo into a single directory

- common/flatpak-dir.c
- common/flatpak-utils.c
- tests/testlibrary.c
On two different code paths we were using the "Title" field in
flatpakref files as the title of a remote, which is incorrect. In most
cases, the remote added via the RuntimeRepo key will be the same as the
remote the app is from, so when the remote is added for the runtime, its
title will be correctly set using the Title value from the flatpakrepo
file and the app will therefore have an origin remote with a title set.
This is not currently true for flatpakref files that use
SuggestRemoteName=, see https://github.com/flatpak/flatpak/pull/4513
For flatpakref files that use a different remote than the RuntimeRepo,
we don't currently have a way for the title to be set automatically;
perhaps we should (https://github.com/flatpak/flatpak/issues/4512).
Fixes …
> Don't use app title from flatpakref as remote title

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-installation.c
- common/flatpak-transaction.c
- system-helper/flatpak-system-helper.c
This commit re-works how we automatically "pin" runtimes that are
explicitly installed, to prevent them from being removed automatically.
In this implementation we do the update to the config as part of the
deploy, which has the following advantages:
(1) It ensures that there's never a confusing polkit prompt about
configuring the software installation when the user asked for a runtime
to be installed (https://github.com/flatpak/flatpak/issues/4200)
(2) It means we don't have to rely on the code on the error path of
flatpak_transaction_real_run() to un-pin the runtime in case something
went wrong with the installation, since we pin it almost atomically with
the deploy.
Fixes #4200
> Change how automatic pinning is implemented (option 2)

- tests/test-repo.sh
- tests/test-run.sh
- tests/test-update-remote-configuration.sh
This way the flatpak command is more consistently run under valgrind
when that is enabled.
> tests: Use ${FLATPAK} not flatpak

- app/flatpak-cli-transaction.c
- tests/libtest.sh
This fixes a few issues with the unit test logs that make them ugly:
1. Currently some lines of output from a command will appear after the
line from xtrace which has the next command, since the command was
printing to stdout and xtrace uses stderr. E.g. "Installation complete."
will appear after "+ flatpak --user install -y ..." but it is from the
previous install command.
2. Lines of output have many spaces after them to pad them to the table
width but this is not needed for non-fancy output.
3. Lines of output are mixed with output from httpd since they don't end
with a newline character, e.g. "Installing… ▊
4%127.0.0.1 - - [16/Nov/2021 00:18:24] "GET /..."
> Make test suite logs prettier

- common/flatpak-dir.c
Currently we verify the checksum of indexed summary files (which have
.sub file names) before writing them to the on-disk cache, so in theory
as long as the disk I/O is successful the data integrity should be
intact when we use it via the flatpak-variant-impl-private.h helpers
generated by variant-schema-compiler. However in practice people
sometimes hit assertion failures which are what you would expect to see
if the data is corrupt, since GVariant stores some metadata such as the
"offset size" toward the end of the data, and if we read this from
serialized user data instead it will obviously be incorrect. In one case
I was able to acquire the flathub.idx, flathub.idx.sig, and
flathub-x86_64-fad08cfb10713e749f02a0e894b5d577b7e9c4931fdf9d2fdc50364c002bc925.sub
files which reproduce one of …
> dir: Verify subsummary checksum from disk cache

- Makefile.am
Caught by @gasinvein on #4575 post-merge: I didn't realize fish has a
separate folder for config files provided by the vendor vs added by the
user. This changes the install directory to match the vendor config dir.
Signed-off-by: Ryan Gonzalez <ryan.gonzalez@collabora.com>
> Fix fish profile script install directory

- README.md
From the [Readme of Souk](https://gitlab.gnome.org/haecker-felix/souk/-/blob/e479e6cc3add76dee83fcba455f5e9b59a9a1201/README.md):
> _Souk is currently no longer being actively developed due to [technical limitations](https://github.com/flatpak/flatpak/issues/4046). Many [design elements](https://gitlab.gnome.org/Teams/Design/software-mockups/-/tree/master/adaptive) of Souk are currently being implemented in GNOME Software 41. More details are explained in [this issue](https://gitlab.gnome.org/haecker-felix/souk/-/issues/61#note_1270615)._
I think that a dead project should not be featured in the Readme.
> Remove Souk from Readme

- common/flatpak-run.c
It should not make any difference other than making it in sync with fontconfig
https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/9c46ef4aac87c42d013d0e7380b6aeb03e1a9949
> run: Use URN for fontconfig DTD

- tests/test-repo.sh
- tests/test-subset.sh
Maybe it's a bit pedantic but we shouldn't be matching
"org.test.Hello.Plugin.fun" when we're trying to match "org.test.Hello",
so add some trailing slashes to prevent that, and change the options on
a few commands so we're only parsing the columns we care about.
> tests: Make grep assertions more specific

- app/flatpak-main.c
- common/flatpak-run.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
Have heard of people running Flatpak commands with both sudo and --user,
and not expecting it work on the root user's installation. Let's just
not allow it since it's not something people ever do intentionally.
> app: Refuse to work with sudo and --user

- .gitignore
- app/flatpak-builtins-build-update-repo.c
- app/flatpak-builtins-search.c
- app/flatpak-cli-transaction.c
- app/flatpak-main.c
- common/flatpak-dir.c
- common/flatpak-run.c
- common/flatpak-utils-http.c
- po/en_GB.po
- tests/Makefile-test-matrix.am.inc
- tests/Makefile.am.inc
- tests/libtest.sh
- tests/test-bundle.sh
- tests/test-repo.sh
- tests/test-run.sh
- tests/test-seccomp.sh
- tests/test-update-remote-configuration.sh
- tests/testlibrary.c
- tests/try-syscall.c
* tests: Allow FLATPAK_BINARY=flatpak for exports
Author: @jtojnar, via #4496 
(cherry picked from commit 96dbe28cfa96e80b23fa1d8072eb36edad41279c)
* tests: Generate Makefile-test-matrix.am.inc in $(srcdir)
Author: me, via #4504
(cherry picked from commit 647c51380c13b72adbd67e0aa83b3a2979f5c6a8)
* testlibrary: Don't use g_assert()
Author: @mwleeds, via #4489  
(cherry picked from commit 0258fc82bb8eac176d45781b54920f0a27613890)
* .gitignore: Update for recent changes
Author: @mwleeds 
(cherry picked from commit 2181f4f171abf824d8e3c754e9e7415813460856)
* tests: Add try-syscall helper
Author: me, via #4505 
(cherry picked from commit 4ce251882c488953ca6e3734f00c5dbe2e1e3e7a)
* tests: Add basic test coverage for our seccomp filters
Author: me, via #4505 
(cherry picked from commit …
> [1.12.x] Cherry-pick misc bug fixes from master

- app/flatpak-builtins-run.c
This would incorrectly overwrite the a11y-bus option and not set the default session-bus options.
This change has a security implication that `--sandbox` will now disable session-bus access.
> run: Fix session-bus and a11y-bus args being incorrect

- app/flatpak-builtins-history.c
- app/flatpak-main.c
- common/flatpak-dir.c
- common/flatpak-ref-utils-private.h
- common/flatpak-utils.c
- doc/flatpak-history.xml
- tests/Makefile-test-matrix.am.inc
- tests/Makefile.am.inc
- tests/test-history.sh
Currently the `history` command is broken if any of the columns [ref, application, arch, branch] are used, as they are by default (see #4332 and #4121). This branch fixes that issue and makes a few other improvements to the history command.
Fixes #4332
> Various fixes for the history command

- tests/test-history.sh
The history test fails sometimes in the CI due to the remote add
operating being missing from the history command's output:
+ diff history-log -
0a1
> add remote			system (history-installation)	test-repo
Presumably this is due to that operation happening in the same second
that is passed to --since, so add another sleep statement to make sure a
second passes before we do anything.
> test-history.sh: Fix flakiness by adding a sleep

- app/flatpak-builtins-repair.c
- tests/Makefile-test-matrix.am.inc
- tests/Makefile.am.inc
- tests/test-repair.sh
Commits that are found to have missing or invalid objects need to be
marked partial so that when the thing referencing them is reinstalled,
the missing objects will be pulled. libostree treats non-partial commits
as complete even if they're not, since verifying their completeness is
an expensive operation.
This exactly mirrors what the "ostree fsck" command does when it finds
corruption in a commit.
This fix is especially important because corrupt repos have been an
issue lately so we at least need repair to work properly.
Relatedly, delete invalid commit objects to ensure they are
re-downloaded, though it's not clear that code path is almost ever
reachable.
Fixes https://github.com/flatpak/flatpak/issues/4618
> repair: Properly mark invalid commits as partial

- app/flatpak-builtins-build-finish.c
- common/flatpak-dir.c
- common/flatpak-utils.c
- doc/flatpak-build-finish.xml
- tests/make-test-app.sh
- tests/test-run.sh
The addition of share/appdata wasn't released yet so we don't need
backwards compat for it.
Fixes https://github.com/flatpak/flatpak/issues/4599
> Export share/metainfo not share/appdata

- common/flatpak-dir.c
Previously, the code would rescan the list of refs many, many times.
Now, it only scans once per flatpak_dir_find_local_related_for_metadata
invocation, and it also only parses each refspec once. On my local
system with a large number of refs (>200) installed, this reduces the
time for a `flatpak remove org.freedesktop.Platform//21.08` to start
from ~7s to ~2s.
This does result in dropping an optimization where ostree_repo_list_refs
is already given the ref kind, but IME the overall speed gains are still
worthwhile.
Fixes #4191.
Signed-off-by: Ryan Gonzalez <ryan.gonzalez@collabora.com>
> dir: Cache the refs set when finding related refs

- app/flatpak-builtins-repair.c
This backports  6fac58a9b90c128a28d028f8f60531513ad1498e (repair: Properly mark invalid commits as partial) to 1.12 branch.
> Flatpak 1.12 backports

- app/flatpak-builtins-search.c
The appstream-glib in Ubuntu 16.04 didn't have this.
---
Should be backported to 1.12.x if accepted.
The version in our official PPA has this included, but only for Ubuntu 16.04 'xenial' builds.
Alternatively, we can declare Ubuntu 16.04 to be unsupported and forget about this. Canonical still security-supports it, but only for subscribers (although a personal subscription can be had at no cost), so it's in a weird limbo between security support and EOL.
> Don't rely on AS_BUNDLE_KIND_FLATPAK existing

- tests/test-metadata-validation.sh
Our old adversary, 1-second timestamp resolution, strikes again!
---
This caused a test failure when I tried packaging flatpak 1.10.6 as a Debian security update: the test sometimes operated on a version of the test fixture (a mockup of a malicious app) from a previous iteration, and got the wrong error message as a result.
I'm *hoping* that changes elsewhere in Flatpak, or in some other component, make this unnecessary in newer branches... 1.12.3 passed tests on all of Debian 12, Debian 11, Ubuntu 20.04, Ubuntu 18.04 and Ubuntu 16.04.
> [1.10] test-metadata-validation.sh: Ensure that mtimes change between iterations

- tests/libtest.sh
- tests/test-override.sh
This is an enabler for the extra test coverage in #4678.
* test-override: Assert that only the expected term is negated
We weren't distinguishing here between overrides that should have been
negated (xdg-documents) and overrides that should not have been negated
(everything else).
* test-override: Assert that unimplemented suffix is ignored with a warning
> Improve overrides unit test

- common/flatpak-enum-types.c.template
* Fix build with GCC 11
From: @mcatanzaro 
See:
https://gitlab.gnome.org/GNOME/glib/-/commit/fab561f8d05794329184cd81f9ab9d9d77dcc22a
(cherry picked from commit 9b34768fa7fa24243439a815ece671a0b2b020dc)
(cherry picked from commit d5bca23eaa93209cd9e2a53cf7384bb983573242)
---
This would make it easier to do initial testing of backports for Debian 10 on a modern system, rather than having to use a Debian 10 VM for all development.
The 1.2.x branch is unmaintained upstream and will not have further releases, but I have to maintain it for Debian 10 (until its EOL date in August 2022) *anyway*, so it might as well be buildable.
> [1.2.x] Fix build with GCC 11

- Makefile.am
- common/flatpak-run.c
Normally, we want to save a process and get better signal handling
by replacing the `flatpak run` process with bubblewrap.
However, when we're doing profiling or measuring coverage, we want to
exit cleanly so that profiling data can be recorded, which is done in
an atexit() hook. In this situation, bypass the execve() optimization;
instead, start bubblewrap in the background, immediately wait for it,
and propagate its exit status.
---
This was useful when checking coverage for the new code in #4678.
> run: Avoid execve() when measuring test coverage

- tests/Makefile.am.inc
This follows the same logic as the system bwrap.
Otherwise, build-time tests will fail when we are using a system
xdg-dbus-proxy and not compiling our own (the symptom is that testlibrary
hangs).
Closes: #2823
Approved by: matthiasclasen
(cherry picked from commit 8115489116aa85ec848318782cdb6c49400aaaf9)
---
This is not *strictly* needed for backports of security fixes to 1.2.x for Debian 10, but it would make my life a lot easier, by letting me bisect builds in the configuration used in Debian.
> [1.2.x] Use system copy of xdg-dbus-proxy for build-time tests if configured

- tests/libtest.sh
- tests/test-override.sh
We'll want this in order to backport #4678, and also just on general principles for better test coverage.
> [1.12.x] Backport #4680

- tests/libtest.sh
- tests/test-override.sh
As with #4682, this is an enabler for backporting #4678 later.
> [1.10.x] Backport #4680

- common/flatpak-context-private.h
- common/flatpak-context.c
- doc/flatpak-build-finish.xml
- doc/flatpak-build.xml
- doc/flatpak-override.xml
- doc/flatpak-run.xml
- tests/test-context.c
- tests/test-exports.c
- tests/test-override.sh
This is an alternative to #4675, with a similar practical result, but resolving some of my comments on #4675, and hopefully structured in a way that is going to be easier to backport. I think this ends up looking better: @alexlarsson, WDYT?
I've also added some test coverage here, which I think is something this feature needs.
If @alexlarsson agrees with this approach, then we can either close #4675 in favour of this PR, or replace `new-home-host-all-perms` with my branch from this PR (so that it becomes the new implementation of #4675) and close this PR.
---
* Revert "manpages: Document the new details of --nofilesystem behaviour."
The new behaviour caused regressions in some situations that previously
worked, and will be reverted.
This reverts commit …
> Revise solution to CVE-2022-21682 to avoid behaviour changes

- common/flatpak-context.c
When generating flattened permissions (i.e. for --show-permissions or
for the /.flatpak-info file) we're currently flattening the permissions
(i.e. don't show things that would only affect layering the permissions).
However, the code doesn't currently do this for the filesystem key, so
implement that.
> flatpak-context: Properly flatten filesystem permissions

- NEWS
- common/flatpak-enum-types.c.template
- common/flatpak-run.c
- portal/flatpak-portal.c
- tests/test-oci.sh
- tests/test-run.sh
@debarshiray, you might want these if you are doing a new 1.8.x release for RHEL. They fix regressions that happened when we fixed CVE-2021-21261 in 1.8.5.
I haven't tested this, perhaps @debarshiray could take responsibility for that?
This branch is based on #4456, please review that first.
---
* Fix build with GCC 11
From: Michael Catanzaro
See:
https://gitlab.gnome.org/GNOME/glib/-/commit/fab561f8d05794329184cd81f9ab9d9d77dcc22a
(cherry picked from commit 9b34768fa7fa24243439a815ece671a0b2b020dc)
* portal: Don't leak fd used for serialized environment
Otherwise we'll run out of file descriptors eventually, when starting
a sufficiently large number of subsandboxes.
Resolves: flatpak/flatpak#4285
Fixes: aeb6a7ab "portal: Convert --env in extra-args into --env-fd"
(cherry picked from …
> Backport regression fixes from 1.10.3 into 1.8.x

- common/flatpak-utils.c
- doc/flatpak-metadata.xml
This is useful for extensions that only apply to nvidia. Specifically there is an nvidia-only VAAPI driver which can be packaged similar to the Intel one.
> Add have-kernel-module- conditional

- tests/test-sideload.sh
This fixes the test on Fedora 35, which I noticed when trying to help @alexlarsson [release 1.8.6](https://github.com/flatpak/flatpak/pull/4474).
Is it possible that the test suite was always broken when run on Fedora against the distribution's `ostree` RPM?  Fedora has been building OSTree against `libcurl` for a very long time (ie., from Fedora 26/27).
> [flatpak-1.8.x] tests: Fix test-sideload.sh if ostree is built with curl backend

- NEWS
- system-helper/flatpak-system-helper.c
This fixes the following failures from the `test-repo` test on Fedora 35:
```
...
ERROR: tests/test-repo@system.wrap - too few tests run (expected 37, got 3)
ERROR: tests/test-repo@system.wrap - exited with status 1
...
ERROR: tests/test-repo@system-norevokefs.wrap - too few tests run
(expected 37, got 3)
ERROR: tests/test-repo@system-norevokefs.wrap - exited with status 1
...
```
This should fix `make distcheck` for the upcoming [1.8.6 release](https://github.com/flatpak/flatpak/pull/4474).
> [flatpak-1.8.x] system-helper: Fix deploys of local remotes

- common/flatpak-transaction.c
- common/flatpak-transaction.h
This complements `flatpak_transaction_set_no_interaction()` and allows calling code to see if a given transaction is interactive.
Also includes a new property for it, and some property infra cleanup in the class.
> flatpak-transaction: Add get_no_interaction() method

- autogen.sh
- tests/make-test-runtime.sh
- triggers/desktop-database.trigger
- triggers/gtk-icon-cache.trigger
- triggers/mime-database.trigger
which(1) is not standardized by POSIX, has different implementations and behaviour on different distributions, and isn't a shell builtin. Replace it with `command -v` and `type -P` as appropriate.
* autogen.sh: Use command -v to check whether commands exist
which(1) is not standardized by POSIX, and has different implementations
and behaviour on different distributions. The behaviour and exit status
of command -v is standardized by POSIX.
* triggers: Quote more defensively
In the unlikely event that one of these paths contains spaces or other
special characters, we don't want to field splitting to take place.
* triggers: Use command -v in preference to which
which(1) is not standardized by POSIX, and has different implementations
and behaviour on different distributions. The behaviour and …
> Avoid using which(1)

- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-dir.c
- common/flatpak-exports-private.h
- common/flatpak-exports.c
- common/flatpak-transaction.c
- common/flatpak-utils.c
- doc/flatpak-metadata.xml
- doc/flatpak-override.xml
- doc/flatpak-run.xml
- tests/Makefile-test-matrix.am.inc
- tests/Makefile.am.inc
- tests/libtest.sh
- tests/test-context.c
- tests/test-exports.c
- tests/test-metadata-validation.sh
- tests/test-override.sh
These are the fixes for [CVE-2021-43860](https://github.com/flatpak/flatpak/security/advisories/GHSA-qpjc-vq3c-572j) and [CVE-2022-21682](https://github.com/flatpak/flatpak/security/advisories/GHSA-8ch7-5j3h-g4fx).  I am going to include them in RHEL 8.6, so I thought that I might as well submit them upstream.
---
* Fix metadata file contents after null terminators being ignored
(backported from commit 3c3dc554e744f0ce974e2051aa8cf94f9736c785)
* Transaction: Fail the resolve if xa.metadata invalid or missing
(backported from commit 10367bd7d2036d39bcd108d7ed81fee9c87685f3)
* Require metadata in commit also for OCI remotes
(backported from commit bd6948c375d50860ce891ead16040faf21839fc7)
* Ensure that bundles have metadata on install
(cherry picked from commit …
> [flatpak-1.8.x] Backport CVE-2021-43860 and CVE-2022-21682 fixes

- common/flatpak-run.c
Trying to run sandboxed GStreamer applications from within jhbuild, for
example, would make those applications fail to find their plugins.
```
$ LANG=C flatpak run org.gnome.Totem.Devel
** (totem:2): WARNING **: 19:32:06.406: Element 'gtkglsink' is missing, verify your installation
** (totem:2): WARNING **: 19:32:06.406: Element 'glsinkbin' is missing, verify your installation
```
Don't propagate those GStreamer environment variables to within the
sandbox to avoid that problem.
See https://gitlab.gnome.org/GNOME/totem/-/issues/504
> run: Don't propagate GStreamer variables to the sandbox

- common/flatpak-dir.c
SHA1 hashes are considered weak these days. Some distributions have
static analysis tools to detect the use of such weak hashes, and they
get triggered by flatpak. While this particular use of SHA1 in flatpak
is likely not security sensitive, it's also easy to move to SHA256 to
avoid any debate.
Here, the SHA1 hash of a named remote's filter file is used to generate
the name of the directory where the refs from that remote are cached.
One can reasonably assume that the cache is frequently invalidated
because the list of refs on the remote changes all the time. Hence,
it's not big problem if it gets invalidated once more because of this
change.
> dir: Use SHA256, not SHA1, to name the cache for a filtered remote

- common/flatpak-run-private.h
- common/flatpak-run.c
- tests/testcommon.c
This PR generalizes our support for parsing and remapping the X11 `DISPLAY` and `XAUTHORITY`, so that we can cope with two situations we previously didn't:
* Local connections where the path-based `AF_UNIX` socket has somehow been deleted: #4702 
* X11-over-ssh forwarding, traditional (insecure) remote X11 and other use-cases involving TCP: #397 
I had to do some refactoring to enable this, so it's probably easiest to review commit-by-commit.
---
* run: Avoid cast warning when built with -Wwrite-strings
We're not going to call XauDisposeAuth on local_xa, so it's OK to put
a "borrowed" constant string here.
* run: Improve const-correctness of Xauth code
* run: Avoid signed/unsigned comparison in Xauth handling
In practice, au_len comes from one of the length fields in an Xauth
struct, …
> Support non-filesystem-based X11 sockets

- common/flatpak-run.c
Put the configured server address string in PULSE_SERVER if it appears
to be remote. This should be enough for apps that already have network
access via --share=network.
If remote access to a PulseAudio server has been selected but the app
does not already have the --share=network permission, we don't want to
add --share=network automatically, because that would open up the app's
access to network resources, perhaps unexpectedly. However, users of
this non-default configuration can use `flatpak run --share=network` or
`flatpak override --share=network` to open up that access if they
consider it to be safe enough.
Resolves: https://github.com/flatpak/flatpak/issues/3908
> run: Interpret tcp: addresses for PulseAudio

- app/flatpak-builtins.h
- app/flatpak-main.c
- common/flatpak-dir.c
As noted in #4111, the Flatpak CLI is currently not very good at dealing with a `/var/lib/flatpak` that has been provisioned as an empty directory - perhaps by `systemd-tmpfiles` or equivalent, or while offloading `/var/lib/flatpak` from a small root filesystem to a larger "bulk data" partition using bind-mounts.
---
* dir: Pass cancellable through to remote EnsureRepo call
* dir: Factor out common code to call EnsureRepo on system helper
* dir: Factor out function to open the libostree repository
I'm about to add another caller for this.
* dir: Use system helper to create system repo if necessary
Previously, if /var/lib/flatpak didn't exist then we would use the
system helper to create and populate it, but if it existed and was empty,
we could only populate it if we had privileges. This …
> Cope better with /var/lib/flatpak existing but being empty

- common/flatpak-dir.c
- common/flatpak-run.c
The main fixes is the appstream deploy tmpdata leak, but I added the gstreamer env var propagation change too, as that seems useful and not very risky.
Do we need anything else?
> Some backports to 1.12.x

- NEWS
Disallowing "sudo flatpak run ..." is not a recent change.
> NEWS: Remove an inaccurate entry for 1.13.1

- app/flatpak-builtins-remote-info.c
- common/flatpak-dir.c
flatpak_remote_state_lookup_ref() always sets the error to
FLATPAK_ERROR_REF_NOT_FOUND when it returns FALSE.
Found by coverity CID 1514265
> Delete some unreachable ref-not-found code

- common/flatpak-dir.c
All the details of the bug are in:
https://github.com/ostreedev/ostree/pull/2549
https://github.com/flatpak/flatpak/issues/3479
This patch works around it by marking the commit we're about to pull
partial, so that if the .commit object exists in a staging directory
from a previous failed pull, it will not be erroneously considered a
complete commit, even by affected versions of libostree that don't have
the above patch. If for some reason the commit in the staging dir is
complete, libostree should harmlessly verify that and pull it in.
Usually the commit we are pulling does not already exist in the local
repo, but add a check anyway so we don't risk marking a complete commit
as partial, and so this works on the code path from
"flatpak install --reinstall ..."
Fixes #3479
> Fix "Failed to read commit" error messages on install/update operations

- tests/test-history.sh
In some OS configurations, unprivileged users cannot read back messages
that they have written to the system log. This test cannot succeed if that
happens, so skip it.
In particular, if the Journal is only in-memory rather than persisted
to disk (as it was by default in Debian 10), then there are no per-user
Journal files, only a single system-wide Journal which requires privileges
to read.
> test-history: Skip test if we cannot read from the Journal

- common/flatpak-dir.c
- common/flatpak-utils.c
- tests/test-history.sh
These are all clean cherry-picks of important patches so I don't think there's much to debate here. There are some other patches on the development branch such as https://github.com/flatpak/flatpak/pull/4752 that it might make sense to backport but I decided to be conservative here.
> [flatpak-1.12.x] 1.12.6 backports

- app/flatpak-complete.c
If the user hasn't typed a '-', don't offer options in the tab
autocompletion. This is consistent with other linux commands, and less
messy.
Fixes https://github.com/flatpak/flatpak/issues/4753
> app: Don't overzealously tab complete options

- tests/Makefile.am.inc
This is specifically for running build-time tests in the Autotools build
system, and is not used when running installed-tests.
> tests: Don't install tap-driver.sh in the installed-tests

- common/flatpak-run.c
Put the configured server address string in PULSE_SERVER if it appears
to be remote. This should be enough for apps that already have network
access via --share=network.
If remote access to a PulseAudio server has been selected but the app
does not already have the --share=network permission, we don't want to
add --share=network automatically, because that would open up the app's
access to network resources, perhaps unexpectedly. However, users of
this non-default configuration can use `flatpak run --share=network` or
`flatpak override --share=network` to open up that access if they
consider it to be safe enough.
Resolves: https://github.com/flatpak/flatpak/issues/3908
Signed-off-by: Simon McVittie <smcv@collabora.com>
(cherry picked from commit ee418c1f2010b0ffa5ad40c96a04d054eadce202) …
> [1.12] run: Interpret tcp: addresses for PulseAudio

- common/flatpak-run.c
If WAYLAND_DISPLAY starts with a '/', use it for the socket path as-is.
See [1].
[1]: https://gitlab.freedesktop.org/wayland/wayland/-/blob/d690712b7b83faeb8fca4015b296aece2fb30c65/src/wayland-client.c#L1064-1095
Signed-off-by: Julian Orth <ju.orth@gmail.com>
(cherry picked from commit aac1205d66e03facc965279d5825272597b305d0)
---
Backport of #4752 to 1.12.x
> [1.12] wayland: allow absolute path in WAYLAND_DISPLAY

- common/flatpak-dir.c
- common/flatpak-utils.c
This is a combination of these two commits from the main branch:
build-finish: Export appstream metainfo into a single directory
(cherry picked from commit 766bf5f08a256431cde8bca6228a4964a73ff6bc)
Export to share/metainfo not share/appdata
(cherry picked from commit 3c63cac8f9c0b45d6e6b8f4167845366a6bb34d9)
However this commit only allows the exports when deploying an
install/update, not when building a new Flatpak, so we avoid a warning
message but arguably don't add any new features to the stable branch.
Fixes https://github.com/flatpak/flatpak/issues/4800
> [1.12.x] Accept share/metainfo exports when installing

- app/flatpak-builtins.h
- app/flatpak-main.c
- common/flatpak-dir.c
Backport of #4732. This is complicated enough that it should have some testing in 1.13.x first, but I think it would be worth having in 1.12.x, since it removes a semi-frequently-fired footgun.
> [1.12] Cope better with /var/lib/flatpak existing but being empty

- common/flatpak-dir.c
The subpath is resolved relative to the root of the commit, so we can
use either an absolute or a relative path interchangeably. When using
libostree < 2021.6 with GLib >= 2.71, absolute paths cause an assertion
failure here; that was a libostree bug and was fixed in 2021.6, but we
can interoperate with more versions by sticking to relative paths, and
there's no real reason to prefer absolute.
Resolves: https://github.com/flatpak/flatpak/issues/4805
---
This is a more complete version of #4707. We don't really *need* this change, but it makes it more likely that people with a random assortment of Flatpak, libostree and GLib versions will avoid the bug.
> dir: Consistently use relative paths for libostree subpaths

- selinux/flatpak.te
The system-helper (ie., the `flatpak-system-helper` process) is
labelled with flatpak_helper_exec_t and runs in the flatpak_helper_t
domain, and needs to be able to read /etc/passwd.  This explicitly
permits it to do so to avoid running into SELinux denials.
https://bugzilla.redhat.com/show_bug.cgi?id=2070350
> selinux: Let system helper have read access to /etc/passwd

- tests/test-repo.sh
Typo correction has nothing to do with --no-pull or --no-deploy so it
doesn't make sense to test them together when we already test each
separately.
> tests: Remove a pointless test

- selinux/flatpak.te
It's clearly quite important to have read access to /var/lib/flatpak
and it's contents.  This explicitly permits that to avoid running
into SELinux denials.
https://bugzilla.redhat.com/show_bug.cgi?id=2070741
This goes on top of https://github.com/flatpak/flatpak/pull/4852 and https://github.com/flatpak/flatpak/pull/4853
> selinux: Permit read access to /var/lib/flatpak

- .github/workflows/check.yml
* workflows: Remove a TODO
We explicitly enable gtk-doc for one of our builds (the one that uses
clang on Ubuntu 18.04). There's no real need to enable it for more than
one build.
* workflows: Move gtk-doc enablement from clang to valgrind build
We want to have gtk-doc enabled in the build that will run
`make distcheck`, but the clang/CodeQL build seems like a poor fit for
that, since it runs twice (for C and Python) and has extra
instrumentation. Move it to the build where we will run tests under
valgrind, which is already somewhat slow.
* workflows: Explicitly enable/disable GObject-Introspection
For the build that uses --enable-asan, explicitly disable introspection,
since the GObject-Introspection scanner works poorly with libtool
and AddressSanitizer (see #4844); the only reason this …
> Github workflow improvements

- app/flatpak-builtins-install.c
- common/flatpak-transaction.c
- common/flatpak-transaction.h
- doc/flatpak-install.xml
This makes it a lot easier to give guidance on using `flatpak run -d` or
`flatpak-coredumpctl`, because there's an easy way to install the
relevant refs.
Signed-off-by: Ryan Gonzalez <ryan.gonzalez@collabora.com>
> Add --include-sdk/debug to install SDK/debuginfo along with a ref

- common/flatpak-oci-registry.c
> common: Fix a parenthesis typo in an error message

- app/flatpak-builtins-build.c
- common/flatpak-context.c
- common/flatpak-dir.c
- common/flatpak-instance.c
- common/flatpak-utils.c
Going through my downstream Coverity reports, I see that these are relevant for `main` as it stands today.
---
* utils: Avoid passing a potentially NULL pointer to strlen(3)
* dir: Don't ignore errors when deleting a file
* context, instance: Don't ignore errors when creating directories
* build: Don't leak the destination prefix
> Fixes for Coverity warnings

- selinux/flatpak.te
The systemd-userdbd service was added in systemd 245, which was
released in March 2020 and is available in RHEL 9.  Therefore, it's
safe to assume that the systemd_userdbd_stream_connect() SELinux
interface is also available on all relevant operating systems, unless
there's reason to believe otherwise.
https://bugzilla.redhat.com/show_bug.cgi?id=2071217
> selinux: Permit using systemd-userdbd

- app/flatpak-main.c
In the tests we don't use a systemwide helper anyway, so the polkit
stuff is unnecessary. Also, for some reason this was taking a very
long time for me, causing the tests to be super slow.
> main: Don't install polkit agent when running in tests, fixing slowness.

- common/flatpak-utils-http.c
- configure.ac
Since we switched to libappstream we really have an implicit dependency
on this, as there are no versions of it building with glib earlier
than 2.46.
This isn't dropping a lot of old code, but at least it is more truthful
about our actual dependencies.
> Bump glib requirement to 2.46 (from 2.44)

- app/flatpak-builtins-uninstall.c
- app/flatpak-builtins-update.c
- app/flatpak-cli-transaction.c
- common/flatpak-dir.c
- common/flatpak-transaction.c
- common/flatpak-transaction.h
- tests/testlibrary.c
Moving these to a separate PR from #4835 since these are ready to be merged whereas the other commits on that PR have performance issues.
There's one piece of un-addressed feedback for the commit "app: Improve end-of-life info message": https://github.com/flatpak/flatpak/pull/4835#discussion_r876429133
But it's not a new issue; the EOL messages we had before also didn't show the arch.
> Some patches from #4835

- .github/workflows/check.yml
This reverts commit ea879dc38c40770ad9324c50582a1f0de5478b45.
Folks say the issue is fixed on launchpad:
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1979579
> Revert "CI: Temporarily build without libsystemd"

- .github/workflows/check.yml
See:
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
> CI: Use CodeQL Action v2, not the deprecated v1

- .github/workflows/check.yml
See:
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
(cherry picked from commit 120322cb8f743a8f65c27c820a9310e4ee382df7)
> [flatpak-1.12.x] CI: Use CodeQL Action v2, not the deprecated v1

- app/flatpak-builtins-build-init.c
Adds arch and branch to the error message to help with locating the required
extension arch and branch.
Right now the message doesn't point to the exact version required. This can get confusing when a different version of the extension that does not fit to the current arch or branch is already installed.
> Increase verbosity of extension missing error messages

- app/flatpak-builtins-mask.c
- app/flatpak-builtins-pin.c
- app/flatpak-complete.c
- common/flatpak-ref-utils.c
There's no point reading data from disk on a code path that doesn't do
anything with it.
> app: Fix inefficiency in pin and mask commands

- selinux/flatpak.te
Commit 8617ab0ad0243f5a granted read and lock access to
/var/lib/flatpak but didn't cover symbolic links.  This explicitly
permits that to avoid running into SELinux denials.
https://bugzilla.redhat.com/show_bug.cgi?id=2071215
> selinux: Permit read access to symbolic links in /var/lib/flatpak

- app/flatpak-builtins-build-export.c
The docs for g_spawn_sync() say:
"Note that you must set the G_SPAWN_STDOUT_TO_DEV_NULL and
G_SPAWN_STDERR_TO_DEV_NULL flags when passing NULL for standard_output
and standard_error."
So add in the stdout flag when calling flatpak-validate-icon in the
build-export command. Without this, there's output in the test logs
from when they're building the test app, due to
https://github.com/flatpak/flatpak/pull/4803
> build-export: Fully ignore stdout content of icon validation

- common/flatpak-utils.c
These were mistakenly only added to flatpak-error.h
> common: Add missing error codes to GDBusErrorEntry array

- common/flatpak-utils.c
Backport of #5008
(cherry picked from commit bf37034663f611c47257412eb198f8efb3c8fe73)
> [flatpak-1.12.x] common: Add missing error codes to GDBusErrorEntry array

- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
- doc/flatpak-flatpakref.xml
- doc/flatpak-flatpakrepo.xml
- tests/test-repo.sh
When Flatpak's P2P updates support was replaced with the "sideloading"
implementation in 1.7.1, a new server side repo config key
"deploy-sideload-collection-id" was added which gets set when you pass
"--deploy-sideload-collection-id" to "flatpak build-update-repo", and
has the effect of setting "xa.deploy-collection-id" in the repo metadata
that is pulled by clients, which itself causes a collection id to be set
on the remote for clients using Flatpak >= 1.7.1.
This commit adds an analogous key in flatpakref and flatpakrepo files,
so the collection id can be set when the remote is configured, rather
than later on when the repo metadata is pulled and acted upon. As before
with DeployCollectionID, it has no difference in function compared to
DeployCollectionID or CollectionID and the only …
> Add DeploySideloadCollectionID flatpakref/flatpakrepo key

- app/flatpak-builtins-build-export.c
Here's an attempt at explicitly allowing empty `Exec` values, as discussed here: https://github.com/flatpak/flatpak-docs/pull/324#discussion_r830537072
Additionally, I found and fixed a segfault that occurred when the `Exec` line is omitted from the desktop file.
> build-export: Proper validation of Exec line in desktop file

- app/flatpak-builtins-enter.c
- common/flatpak-run.c
* run: Preserve X11 display number instead of redirecting it to :99
Suppose the user's "real" X11 display on the host is Xorg or Xwayland
listening on :42, but they also have an Xvfb server listening on :99.
If we change the X11 display number to the arbitrary value :99, and
the Flatpak sandbox shares its network namespace with the host, then
clients inside the Flatpak sandbox will prefer to connect to the
abstract socket @/tmp/.X11-unix/X99 (which is Xvfb), rather than the
filesystem-backed socket /tmp/.X11-unix/X99 in the sandbox (which is
really /tmp/.X11-unix/X42 on the host, i.e. Xorg or Xwayland).
If they're relying on Xauthority (MIT-MAGIC-COOKIE-1) for access
control (as many display managers do), then this will fail, because
we gave the sandboxed app access to the cookies for …
> run: Preserve X11 display number instead of redirecting it to :99

- common/flatpak-context.c
- doc/flatpak-run.xml
We already allow normal apps to own MPRIS names but subsandboxes could not.
This allows them with the same dbus restrictions that they must be prefixed by `$app_id.Sandboxed.`.
This will be used by WebKitGTK.
> Allow sub-sandboxes to own MPRIS names

- app/flatpak-main.c
- doc/flatpak-config.xml
- doc/flatpak-create-usb.xml
- doc/flatpak-history.xml
- doc/flatpak-info.xml
- doc/flatpak-install.xml
- doc/flatpak-list.xml
- doc/flatpak-make-current.xml
- doc/flatpak-mask.xml
- doc/flatpak-override.xml
- doc/flatpak-pin.xml
- doc/flatpak-remote-add.xml
- doc/flatpak-remote-delete.xml
- doc/flatpak-remote-info.xml
- doc/flatpak-remote-ls.xml
- doc/flatpak-remote-modify.xml
- doc/flatpak-remotes.xml
- doc/flatpak-repair.xml
- doc/flatpak-run.xml
- doc/flatpak-search.xml
- doc/flatpak-uninstall.xml
- doc/flatpak-update.xml
Save folks a few keystrokes. There is a command which already has a '-u'
option, document-export, but it doesn't support --user so there should
be no conflict. However '-s' is used by the info command among others,
so we can't use that for --system.
> app: Add -u alias for --user

- common/flatpak-exports.c
This helps to figure out what is going on if the expected paths are not
being exported.
The general design principle here is that I've used flatpak_debug2()
(which appears in `flatpak -v -v` but not `flatpak -v`) for situations
which occur under normal circumstances, and g_debug() (which appears
in `flatpak -v` or higher) for situations which are expected to be
uncommon.
---
This was very useful in figuring out a regression in steam-runtime-tools, which contains a copy of this code.
> exports: Add logging at a finer granularity

- .github/workflows/check.yml
- configure.ac
- revokefs/main.c
- revokefs/writer.c
- revokefs/writer.h
- tests/can-use-fuse.c
- tests/flatpak.supp
* revokefs: Use FUSE version 3 if possible
Based on a change contributed by Léo Stefanesco (#3661); but instead of
unconditionally using FUSE 3, leave a fallback code path for FUSE 2 for
older distros.
Co-authored-by: @ineol
* tests: Add valgrind suppression for ostreedev/ostree#2592
This is fixed in v2022.3, but that version missed the boat for Ubuntu
22.04.
* workflows: Build with FUSE 3 for Ubuntu 22.04
This ensures we exercise both code paths.
> revokefs: Use FUSE version 3 if possible

- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-run.c
- doc/flatpak-build-finish.xml
- doc/flatpak-build.xml
- doc/flatpak-override.xml
- doc/flatpak-run.xml
> Add --socket=gpg-agent

- common/flatpak-utils-http.c
There can happen a race condition between internal libcurl structure
content when two threads set the `data` structure for the callbacks
from two threads, which can cause access of already freed stack-allocated
`data`, resulting in a memory corruption.
Closes https://github.com/flatpak/flatpak/issues/3701
-------------------------------------------
An alternative solution, which can run requests in parallel, would be to create a new `FlatpakHttpSession` for every request. It seems to be a cheap structure, both for libcurl and for libsoup, but I'm not that used to those structures, thus I cannot tell for sure. I can change the commit to do that instead, if needed.
> common: Add thread safety on libcurl usage

- SECURITY.md
1.15.x doesn't exist yet but I don't think it hurts to add it here.
I am assuming 1.10.x and 1.12.x are still supported based on the fact that things are just recently being backported to them.
cc @debarshiray @alexlarsson @smcv
> SECURITY.md: Update for 1.14.0 release

- common/flatpak-utils-http.c
~~The CURLOPT_PROTOCOLS option has been deprecated for CURLOPT_PROTOCOLS_STR in 7.85.0 and using CURLOPT_PROTOCOLS returns an error code.~~ Nvm, I mistook the line numbers, using the deprecated option works fine as of now.
A check has also been added to ensure that curl actually supports HTTP2 before trying to use it
Also all the error code checking seems to use CURLM_OK instead of CURLE_OK. Is this intentional? Doesn't matter though since both are defined to 0
The same fixes are required in ostree https://github.com/ostreedev/ostree/blob/main/src/libostree/ostree-fetcher-curl.c#L875-L887
> libcurl fixes

- .github/workflows/check.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- app/flatpak-builtins-document-list.c
(flatpak documents:2965757): GLib-CRITICAL **: 11:27:35.128: g_variant_iter_next_value: must not be called again after NULL has already been returned.
This is due to the applications iterator being checked twice even though it is empty.
> app: Fix warning when listing a document with no permissions.

- configure.ac
- flatpak.pc.in
Some projects such as GNOME-Software need this information to know
if its safe to build against (libsoup2 vs libsoup3 conflicts).
Closes #5053
> flatpak.pc: Add httpbackend variable for curl/libsoup detection

- .github/workflows/check.yml
- common/flatpak-uri.c
g_time_zone_new_offset() was new in GLib 2.58, but Ubuntu 18.04 'bionic'
only has GLib 2.56, and in theory we still claim to support versions
all the way back to GLib 2.46. If that function isn't available,
reimplement it in terms of the deprecated g_time_zone_new().
---
Yes, I've been packaging backports today. How could you tell?
> uri: Don't rely on g_time_zone_new_offset()

- common/flatpak-enum-types.c.template
- common/flatpak-enum-types.h.template
`@filename@` expands to the relative or absolute path to the source
file, which varies between build systems and build directories.
`@basename@` expands to the basename of the file, which stays constant
across more build configurations.
---
Noticed while comparing build results of Autotools and Meson builds with https://github.com/flatpak/flatpak/pull/4845.
> enum-types: Make generated files more reproducible

- common/flatpak-run.c
- doc/flatpak-run.xml
In combination with https://github.com/gssapi/gssproxy/issues/45 and with changes included in the GNOME 43 flatpak runtime, this will allow securely proxying kerberos authentication via the host system without sandbox holes.
> gssproxy! (it's like a portal for kerberos)

- session-helper/flatpak-session-helper.c
Exiting the process with a custom exit status (1) after systemctl stop (SIGTERM) makes systemd treat the flatpak-session-helper service as if it had failed.
> session-helper: Run default signal handler after handle_sigterm()

- profile/flatpak.fish
The profile script previously nuked `XDG_DATA_DIRS` and then “helpfully” re-populated it with FHS paths. This was especially bad for systems like NixOS, which do not have `/usr` and rely on `XDG_DATA_DIRS` heavily.
Quoting from https://fishshell.com/docs/current/cmds/set.html
> If a variable is set to zero elements, it will become a list with zero elements.
And indeed, that is what the `set -x --path XDG_DATA_DIRS` command does. We need to list the value explicitly, if we want to preserve it while setting variable options.
> profile.d: Do not destroy XDG_DATA_DIRS in fish

- tests/testlib.h
* Update libglnx to commit e701578c
In particular, this version has more gtestutils backports, including a
version of g_test_message() that preserves correct TAP syntax for
multi-line messages.
* testlib: Remove local backport of g_assert_no_errno()
libglnx now provides this.
> Update libglnx to 2022-10-10

- revokefs/writer.c
This fixes the build on ILP32 architectures such as i386 with the Meson
build system. The Autotools build system accidentally didn't build
revokefs with -Werror=format, because it sets the target-specific CFLAGS
for revokefs but does not include the $(AM_CFLAGS) in them.
Fixes: aeecbb7d "revokefs: Split out the writing part from the fuse implementation"
> revokefs: Use correct format string for a ssize_t

- Makefile.am
- icon-validator/Makefile.am.inc
- revokefs/Makefile.am.inc
* revokefs: Remove incorrect libglnx include directory
revokefs already gets the correct include directory from the AM_CPPFLAGS.
This would also break the build with -Werror=missing-include-dirs.
* automake: Consistently include $(AM_CFLAGS) in target-specific CFLAGS
When built for i386 with Autotools, this would have detected the format
string issue fixed in #5148.
> automake: Consistently include $(AM_CFLAGS) in target-specific CFLAGS

- common/flatpak-context.c
When filesystem=host access is provided, some root folders are hidden, including /boot.
The bootloader specification now recommends mounting the system EFI filesystem in /efi (currently visible) instead of /boot/efi (currently hidden). This hides /efi for the same  reasons /boot is already hidden.
> Add /efi in the hidding list when (fs=host)

- app/meson.build
Since we include the base private headers, we need the common base sources to be generated.
> app/meson.build: Add missing dep

- common/flatpak-run.c
This supplements clearing TMPDIR env variable which is only one among variables used for storing temporary files. Any of those leaking from host may confuse flatpak apps which try to save temporary files under non-existing directory in sandbox.
See https://github.com/flathub/com.logseq.Logseq/issues/29 for real world example.
> Clear more temporary file paths from env

- common/flatpak-dir.c
This already happens for installs due to the cleanup path in `flatpak_dir_deploy_install()`, but it doesn’t happen for other calls to `flatpak_dir_deploy()`. Notably, during updates of already installed apps.
Specifically, this means that if an app update is cancelled due to being blocked by a parental controls policy, the temp deploy dir for that app (such as
`~/.local/share/flatpak/app/com.corp.App/x86_64/stable/.somehex-XXXXXX`) will be leaked. It will never be automatically cleaned up, as it’s not in `/var/tmp` either.
Fix that by using `glnx_mkdtempat()` to create a scoped temporary directory.
(cherry picked from commit ce1829a703f2bc2e7868fd314ddefb63fbf7dce1)
---
Trivial backport of #5146 to `flatpak-1.12.x`. Tested, and it …
> [flatpak-1.12.x] flatpak-dir: Clean up temp deploy dir on failure of flatpak_dir_deploy()

- common/flatpak-dir.c
This already happens for installs due to the cleanup path in `flatpak_dir_deploy_install()`, but it doesn’t happen for other calls to `flatpak_dir_deploy()`. Notably, during updates of already installed apps.
Specifically, this means that if an app update is cancelled due to being blocked by a parental controls policy, the temp deploy dir for that app (such as
`~/.local/share/flatpak/app/com.corp.App/x86_64/stable/.somehex-XXXXXX`) will be leaked. It will never be automatically cleaned up, as it’s not in `/var/tmp` either.
Fix that by using `glnx_mkdtempat()` to create a scoped temporary directory.
(cherry picked from commit 85a83a06f954080bd1fbba5f07b465955e34040c with minor conflicts)
---
Straightforward backport of #5146 to …
> [flatpak-1.10.x] flatpak-dir: Clean up temp deploy dir on failure of flatpak_dir_deploy()

- selinux/flatpak.te
Backport of #4992
cc @debarshiray
> [flatpak-1.12.x] selinux: Permit read access to symbolic links in /var/lib/flatpak

- common/flatpak-dir.c
Following on from commit 85a83a06f95, add some code to clean up old
leaked deploy tmpdirs when we next try to deploy the same app
(successfully or not).
This should free up disk space leaked by failed deploys pre-85a83a06f95.
> flatpak-dir: Clean up old leaked deploy dirs at start of deploy

- common/flatpak-run.c
- doc/flatpak-run.xml
This variable is typically used to configure the use of a custom
set of XKB definitions. In those cases, it's mostly meant for the
X11 server or Wayland compositor. NixOS is known to employ this
variable for their custom XKB layout implementation.
When the path it points to is unreachable (due to the sandbox),
most GTK+/Qt applications will crash on Wayland.
Unsetting this does not seem to negatively impact the use of custom
XKB layouts with Flatpak applications.
> flatpak-run: unset XKB_CONFIG_ROOT

- profile/flatpak.fish
Previously in a0505f52d993837ce7ce96801f54eb37d55dadfb
the profile script was modified to preserve XDG_DATA_DIRS.
This had the side-effect of making the script not idempotent,
adding duplicate entries for every installation every time it's sourced.
On my current system  that results in this value:
/home/mkhl/.local/share/flatpak/exports/share /var/lib/flatpak/exports/share /home/mkhl/.local/share/flatpak/exports/share /var/lib/flatpak/exports/share /usr/local/share /usr/share
which in turn has the side-effect of the GNOME search settings showing two entries
for every application installed via flatpak.
This change makes the script check that an entry is new before adding it.
It also uses `set -p` (short for `--prepend`) to add them.
N.B.
`set -p VAR val` is equivalent to `set VAR val $VAR` …
> profile.d: Only add new directories to XDG_DATA_DIRS in fish

- common/flatpak-run.c
- doc/flatpak-run.xml
This variable contains paths to load GIO modules from. For the most part, they refer to paths outside of the sandbox or if they happen to be in the sandbox, would contain modules that are incompatible with the sandbox runtime (ie. different libc).
While I've not found programs that would crash outright, it may cause unexpected behaviors (eg. Apostrophe not being able to render math in preview panel).
This variable is set by NixOS for its dependency boxing.
> flatpak-run: unset GIO_EXTRA_MODULES

- selinux/meson.build
With custom_target, providing build_by_default is not enough to install the output, which must be explicitly requested.
> selinux: Install when using meson

- app/flatpak-main.c
- oci-authenticator/flatpak-oci-authenticator.c
- portal/flatpak-portal.c
- session-helper/flatpak-session-helper.c
- system-helper/flatpak-system-helper.c
- tests/test-authenticator.c
* main: Treat g_info() as equivalent to g_debug()
This makes us consistent with the default behaviour of GLib, and
its behaviour with G_MESSAGES_DEBUG=all. g_debug() and g_info() are
the two lowest priority levels, and GLib normally silences them by
default.
At the moment, Flatpak uses G_LOG_LEVEL_DEBUG in the flatpak2 domain
as its lowest-priority log level (only shown with flatpak -v -v), and
G_LOG_LEVEL_DEBUG in the flatpak domain as its second-lowest
(shown with flatpak -v or higher). I want to move towards using
G_LOG_LEVEL_INFO for flatpak -v messages, and G_LOG_LEVEL_DEBUG for
flapak -v -v, so that we don't need a second log domain: this is a
policy I've used successfully in Flatpak-derived Steam Runtime code.
This change does not fully implement that policy, but gives us a …
> main: Treat g_info() as equivalent to g_debug()

- common/flatpak-dir.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
- portal/flatpak-portal.c
* portal: Factor out flatpak_bwrap_is_unprivileged()
We can use this for other features that rely on having a non-setuid
version of bubblewrap.
* dir: Use consistent FlatpakRunFlags everywhere
In principle either of these functions might read any of the flags.
---
Prerequisite for the version of #5084 I'm now proposing.
> Refactoring to prepare for #5084

- common/flatpak-context.c
- common/flatpak-exports-private.h
- common/flatpak-exports.c
- tests/test-exports.c
If we try to share certain reserved directories with the sandbox, that can break our ability to set up sandbox-specific things: the app in `/app`, the runtime in `/usr` and `/etc`, OS stuff in `/dev` and `/proc`, and Flatpak-specific information in `/.flatpak-info`, `/run/flatpak` and `/run/host`.
Previously, we would silently prevent descendants of most of these paths from being shared (#5035). We still prevent that, but now there is a warning so that users will be less mystified.
We did not previously prevent descendants of `/.flatpak-info`, `/run/flatpak` and `/run/host` from being shared, but now those three have joined the list.
We also did not previously prevent *ancestors* of the reserved paths from being shared, which in practice manifested in two ways: a symlink like `/the-root …
> Avoid exporting reserved directories more thoroughly / improve error reporting

- common/flatpak-utils.c
Exporting to an existing repo on a Samba filesystem failed with EACCES when libglnx called renameat() to replace the old summary.idx file.
error: renameat: Permission denied
This occurred even when the user had appropriate permissions to the file and its ancestor directories.
The problem was that flatpak had mapped the old file into memory for reading, and still held a reference to that mapping when attempting to replace the underlying file. Apparently this works on some filesystems, but not on cifs.
We therefore release the memory mapping before replacing the underlying file.
Fixes #5257
> utils: Unmap the old summary.idx file before trying to replace it

- .github/workflows/check.yml
- NEWS
- app/flatpak-builtins-repair.c
- app/flatpak-main.c
- common/flatpak-run.c
- common/flatpak-utils.c
- doc/flatpak-run.xml
- oci-authenticator/flatpak-oci-authenticator.c
- portal/flatpak-portal.c
- profile/flatpak.fish
- session-helper/flatpak-session-helper.c
- system-helper/flatpak-system-helper.c
- tests/test-authenticator.c
* #5257 
* #5198 
* #5206 
* #5194 
* #5204 
* Don't allow `KRB5CCNAME` to inherit into sandbox (part of #4914, I don't intend to backport the rest)
* Treat `g_info()` as equivalent to `g_debug()` to make backports from 1.15.x more straightforward (part of #5001, I don't intend to backport the rest)
> [1.14.x.] Backport various smaller changes from main

- common/flatpak-run.c
g_subprocess_get_stdout_pipe() does not transfer ownership, so the stream still belongs to the GSubprocess and we must not unref it.
Fixes: 764e5a4d "Add --socket=gpg-agent"  
Resolves: https://github.com/flatpak/flatpak/issues/5095
cc @bl00mber 
---
Should be backported to 1.14.x once merged, but I'm not going to block on this for 1.14.2.
> run: Avoid double-free of gpgconf stdout stream

- common/flatpak-utils-http.c
CURLOPT_PROTOCOLS_STR is documented as the replacement for CURLOPT_PROTOCOLS.
> utils-http: Avoid deprecation warning with curl >= 7.85.0

- NEWS
- common/flatpak-run.c
> [1.14.x] run: Avoid double-free of gpgconf stdout stream

- app/flatpak-builtins-list.c
- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-installation.c
* list: Handle error in flatpak_dir_load_deployed()
flatpak_dir_load_deployed() can fail and return NULL. If that happens,
there is a semi-installed but broken app, and we should show a warning
rather than crashing.
Resolves: https://github.com/flatpak/flatpak/issues/5293
* list: Show a warning if we can't load the current version
Conceptually similar to the previous commit, except it didn't crash
before, just didn't display anything.
* dir: If overrides are syntactically invalid, include path in error message
It's unhelpful to say something like "Key file contains line “x” which is
not a key-value pair, group, or comment" without specifying which file
we are talking about.
* dir: If metadata is syntactically invalid, say which file is the problem
Similar to the previous commit, but for …
> Don't crash on malformed overrides

- NEWS
- common/flatpak-context.c
- common/flatpak-exports-private.h
- common/flatpak-exports.c
- po/POTFILES.in
- tests/test-exports.c
Backport of #5213 to 1.14.x. What do other maintainers think? Good for 1.14.x, or too intrusive?
* exports, context: List unexported paths one per line in sorted order
This will reduce conflicts when new entries are added.
Helps: https://github.com/flatpak/flatpak/issues/5205
* exports: Never try to export paths below /run/flatpak or /run/host
These directories are reserved for Flatpak's own use.
Helps: https://github.com/flatpak/flatpak/issues/5205
* exports: Never try to export /.flatpak-info
Just for completeness, in practice the host system will not have this.
Helps: https://github.com/flatpak/flatpak/issues/5205
* exports: Make _exports_path_expose produce a GError on failure
This is a step towards allowing its direct and indirect callers to decide
how serious the failure is, and …
> [1.14.x] Avoid exporting reserved directories

- common/flatpak-run.c
- doc/flatpak-run.xml
If the `GDK_BACKEND` environment variable is present and it's value does not match the Wayland and X11 socket configuration, then a GTK app will fail to run since it will only consider the display backend from the environment variable.
This should probably be extended to cover other display environment variables such as `QT_QPA_PLATFORM` for Qt and `SDL_VIDEODRIVER` for SDL. However, I've only tested this with GTK applications.
> flatpak-run: Unset GDK_BACKEND

- common/flatpak-transaction.c
- tests/test-repo.sh
- tests/testlibrary.c
If `no_deploy` has been set to `TRUE` in a transaction, then the intention is that no changes will be made to the installed flatpaks. Currently that's not the case for explicitly or implicitly added uninstall operations. That's particularly bad for eol-rebase flatpaks since they old version will be automatically removed without the new version being installed. To address this, prevent uninstall operations from being added for no deploy transactions.
Closes: #5172
> transaction: Ignore uninstall operations for no deploy

- NEWS
- app/flatpak-builtins-list.c
- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-installation.c
Cherry-picks of #5295 to 1.14.x, fixing #5293, plus a NEWS update.
(I also cherry-picked #5303 already, since it's trivial.)
> [1.14.x] Backport fixes for #5293

- common/flatpak-transaction.c
Introduces no functional changes, but simplifies the code a little.
> transaction: Remove unused error argument from flatpak_transaction_add_op()

- common/flatpak-transaction.c
- tests/test-repo.sh
- tests/testlibrary.c
From: @dbnicholson 
If `no_deploy` has been set to `TRUE` in a transaction, then the intention is that no changes will be made to the installed flatpaks. Currently that's not the case for explicitly or implicitly added uninstall operations. That's particularly bad for eol-rebase flatpaks since they old version will be automatically removed without the new version being installed. To address this, prevent uninstall operations from being added for no deploy transactions.
Closes: #5172
(cherry picked from commit fba3a7d35e7739a6b923f74596d388a3ae7a2cfa)
---
cc @pwithnall @wjt 
Cherry-pick from 1.15.3, and I hope this is equivalent to what you're shipping in your Flatpak builds?
> [1.14.x] transaction: Ignore uninstall operations for no deploy

- doc/flatpak-override.xml
This addition includes the override path in Flatpak override command documentation.
This is similar to #401. This pull request modifies the file [doc/flatpak-override.xml](https://github.com/flatpak/flatpak/blob/main/doc/flatpak-override.xml).
> feat(flatpak override) add override path

- common/flatpak-utils.c
`ostree_raw_file_to_content_stream` will try to read it, causing a critical warning with GLib 2.76 causing tests to fail.
Ostree probably shouldn't try to use the size of a symlink, but that seems to be more complicated than a single line.
> Set size of file info for symlinks to 0

- SECURITY.md
We have too many branches and too few maintainers to be able to treat old-stable branches as fully supported.
Helps: #5352
> security policy: Downgrade 1.12.x, 1.10.x to "supported if feasible"

- tests/test-exports.c
- tests/test-instance.c
g_test_init() is meant to be called before any other use of GTest APIs, and isolated_test_dir_global_setup() can call g_test_message(). GLib 2.76 makes this more of a practical problem.
(isolated_test_dir_global_setup() is essentially a reimplementation of G_TEST_OPTION_ISOLATE_DIRS, since we don't depend on GLib 2.60.)
Alternative to https://github.com/flatpak/flatpak/pull/5355.
---
As suggested by @pwithnall on #5355. @heftig, please could you try this?
> tests: Call g_test_init() before isolated_test_dir_global_setup()

- tests/testlibrary.c
As with commit 43085c0e "dir: Consistently initialize g_autofree variables", this is currently harmless because we never actually early-return or goto out of the region between declaration and initialization, but some compiler versions log a warning here anyway.
> testlibrary: Initialize autofree variable to silence a compiler warning

- .github/workflows/differential-shellcheck.yml
Also, update `differential-shellcheck` to the latest version (`v4.0.2`) - https://github.com/redhat-plumbers-in-action/differential-shellcheck/releases Push events are supported since `v4.0.0`.
Fixes: https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/215
This should get rid of annoying messages from the `github-code-scanning` bot.
> ci: trigger differential-shellcheck workflow on push

- .github/workflows/block-autosquash-commits.yml
- .github/workflows/check.yml
Recently on April 1st, Ubuntu 18.04 runners reached the unsupported state and will no longer be available in actions (More information here: https://github.com/actions/runner-images/issues/6002). This PR is to update not only for updating the runners but also for updating the related actions. I tested these changes before creating this PR in my fork's actions here https://github.com/kbdharun/flatpak/actions. Since this is a major change a thorough review is required. 
- [check.yml: bump actions/checkout version and replace deprecated 18.04 runner with 20.04](https://github.com/flatpak/flatpak/commit/45b7df6d1ded5d23ec3779a79b1cf44b4c9c5625)
- [block-autosquash-commits.yml: bump block-autosquash-commits-action version to 2.2.0](https://github.com/flatpak/flatpak/commit/902cc6807db97c7f077d6 …
> [major, fix] workflows: bump actions version and remove unsupported runner 18.04

- common/flatpak-run-sockets.c
This could be uninitialized if the app has --socket=fallback-x11 but not --socket=wayland, although that's a combination that doesn't make a great deal of sense. Regression introduced during recent refactoring.
Fixes: db7a8bb5 "common: Split up socket setup from flatpak-run into multiple files"
> common: Fix an uninitialized variable

- common/flatpak-dir.c
Use the same run flags and highlight which ones are specific to apply_extra. Also mark the flatpak context as sandboxed.
> dir: Set up the apply_extra sandbox like flatpak-run --sandbox

- app/flatpak-builtins-install.c
- app/flatpak-builtins-remote-add.c
- common/Makefile.am.inc
- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-dir-private.h
- common/flatpak-exports-private.h
- common/flatpak-exports.c
- common/flatpak-instance.c
- common/flatpak-metadata-private.h
- common/flatpak-oci-registry-private.h
- common/flatpak-ref-utils-private.h
- common/flatpak-ref-utils.c
- common/flatpak-run-private.h
- common/flatpak-run.c
- common/flatpak-transaction.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
- portal/flatpak-portal-app-info.h
- tests/httpcache.c
- tests/test-context.c
- tests/test-exports.c
- tests/test-instance.c
Various smaller refactors in preparation for #5409.
* common: Move declaration of get_compat_arch_reverse back to -utils
The implementation never actually moved to -ref-utils.
* common: Move flatpak_abs_usrmerged_dirs to FlatpakExports
This will help to break circular dependencies between FlatpakExports
and flatpak-run.
* common: Move flatpak_is_app_runtime_or_appstream_ref to ref-utils
This matches where it was declared.
* common: Remove unused functions
* common: Stop including utils-http in utils
utils-http is conceptually larger than utils.
* common: Explicitly include context's own header
Previously we were relying on flatpak-utils-private.h having a circular
dependency on this, but I'm intending to remove that during future
refactoring.
* common: Move metadata to its own header
This …
> utils: Refactoring

- app/flatpak-builtins-utils.c
- app/flatpak-builtins-utils.h
- configure.ac
- meson.build
* app: Provide a stub implementation of AS_CHECK_VERSION if needed
Our only code that is conditional on the libappstream version wants
version 0.14.0, which conveniently is exactly the version that
introduced AS_CHECK_VERSION.
* app: Use AS_FORMAT_STYLE_CATALOG if available
AS_FORMAT_STYLE_COLLECTION is a deprecated alias for ..._CATALOG, and
was removed entirely in appstream git main (presumably version 0.17
or 1.0).
Resolves: https://github.com/flatpak/flatpak/issues/5472
---
@Justinzobel, please try compiling flatpak with this change? It should fix #5472.
> Improve libappstream version detection, and use newer APIs if available

- sideload-repos-systemd/meson.build
Previously, the meson build just didn't work
> meson: Properly install tmpfiles.d config

- app/flatpak-builtins-build.c
- common/Makefile.am.inc
- common/flatpak-bwrap-private.h
- common/flatpak-bwrap.c
- common/flatpak-dir.c
- common/flatpak-run-dbus.c
- common/flatpak-run-private.h
- common/flatpak-run-sockets-private.h
- common/flatpak-run-sockets.c
- common/flatpak-run-wayland-private.h
- common/flatpak-run-wayland.c
- common/flatpak-run.c
- common/meson.build
- configure.ac
- meson.build
- meson_options.txt
This exposes a reliable way for Wayland compositors to get
identifying information about a client. Compositors can then
apply security policies if desirable.
~~TODO: `bwrap --sync-fd` can only be specified once (only the last param is taken into account), but D-Bus already uses it. Any ideas how to address this?~~
References: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/68
> Add support for Wayland security context

- common/flatpak-bwrap.c
- common/flatpak-dir.c
- common/flatpak-instance.c
- common/flatpak-oci-registry.c
- common/flatpak-prune.c
- common/flatpak-run-dbus.c
- common/flatpak-run-x11.c
- common/flatpak-run.c
- common/flatpak-utils.c
- portal/flatpak-portal.c
- tests/test-exports.c
- tests/test-portal.c
* Update submodule: libglnx 2023-08-29 ([changes](https://gitlab.gnome.org/GNOME/libglnx/-/compare/4e44fd...54ad67?from_project_id=1636&straight=false))
* Add g_steal_fd() backport
* Add g_strv_equal() backport
* Disable crash reporting when testing assertions
* Use g_steal_fd()
This was new in GLib 2.70, but libglnx now provides a backport, so we
can use it unconditionally.
* dir: Use g_strv_equal()
This was new in GLib 2.60, but libglnx now provides a backport, so we
can use it unconditionally.
We still need a wrapper because g_strv_equal() is not NULL-safe, but
it's a very thin wrapper now.
> Update libglnx submodule

- .github/workflows/check.yml
- .github/workflows/differential-shellcheck.yml
This PR bumps the `actions/checkout` version from v3 (Node 16) to v4 (Node 20) as Node 16 is reaching eol soon.
Ref. https://nodejs.org/en/blog/announcements/nodejs16-eol
> CI: bump actions/checkout to v4

- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-run.c
- doc/flatpak-build-finish.xml
- doc/flatpak-build.xml
- doc/flatpak-metadata.xml
- doc/flatpak-override.xml
- doc/flatpak-run.xml
This new permission exposes the host's /dev/input directory, providing
minimal game controller support without resorting to --device=all.
(It originally handled /dev/uinput and /dev/hidraw* as well, for the sake of motion controls, Steam Input, and similar advanced features, but that functionality has since been removed.)
I made this for my own use, but thought it might be a helpful contribution, since I've noticed multiple suggestions for something like it.
Ref:
https://github.com/flatpak/flatpak/issues/7
https://github.com/flatpak/flatpak/issues/4405#issuecomment-916792716
> Add --device=input permission

- common/Makefile.am.inc
- common/meson.build
- configure.ac
- meson.build
Follow-up for #4920. cc @emersion 
* build: Link Wayland code into full libflatpak-common only
This is only needed in flatpak-run-wayland.c, so we don't need it when
linking ancillary daemons that don't need any of flatpak-run, such as
the portal, session helper, system helper and OCI authenticator.
* build: Generate Wayland glue code as private
The `code` argument to wayland-scanner is deprecated in favour of
`private-code`, which marks the symbols as private, avoiding them
leaking into the ABI of `libflatpak.so.0`.
`private-code` was new in wayland-scanner 1.15, which is available in
relatively old LTS distributions like CentOS 7, Debian 10 and
Ubuntu 18.04, and is much older than wayland-protocols 1.32.
> Clean up build system integration for Wayland security contexts

- common/flatpak-utils-http.c
There was already a timeout set using `CURLOPT_CONNECTTIMEOUT`, but that only affects the initial connection. Once a HTTP connection is established, the timeout is ineffective.
That means that once a HTTP connection is established, there is no bound on the length of time a download can take. Sometimes, downloads drop to very low speeds (for Networking Reasons) and we need a way to give up on a download if that happens.
So, set a low speed limit of 10KB/s for 60s. If a curl download goes more slowly than this, it will be considered timed out, and the `CURLE_OPERATION_TIMEDOUT` code path will be taken.
Fixes: https://github.com/flatpak/flatpak/issues/5519
> utils-http: Add transfer speed timeout for libcurl HTTP downloads

- app/flatpak-builtins-remote-info.c
Use architecture instead of id in call to
flatpak_dir_load_appstream_store ().
Without this, remote-info does not show AppStream metadata.
Fixes: adb3b61f "decomposed: Return FlatpakDecomposed from flatpak_dir_find_remote_ref()"
> remote-info: Fix call to flatpak_dir_load_appstream_store()

- common/flatpak-instance.c
- portal/flatpak-portal-app-info.c
- revokefs/main.c
Follow-up to https://github.com/flatpak/flatpak/pull/5510#discussion_r1321752302. Only build-tested.
CC: @smcv
---
* instance: Use glnx_opendirat() where possible
Doing so adds the following flags to the openat() call:
O_RDONLY | O_NONBLOCK | O_NOCTTY
And removes the following flag: O_PATH
Also let libglnx handle the error message formatting.
* portal: Use glnx_opendirat()
Also print error message in case the operation fails.
No change in behavior apart from printing the error message.
* revokefs: Use glnx_opendirat_with_errno()
No change in behavior.
> Use `glnx_opendirat()` and `glnx_opendirat_with_errno()` where possible

- tests/make-test-runtime.sh
The tests/make-test-runtime.sh scripts sets '-e' in lieu of implementing useful error checking, but doesn't actually check if the programs it uses exist in the first place; and aborts silently when they're not available.
It is more useful to warn about them, and stop execution earlier. This leaves some leftover files, but arguably that's better than leaving leftover files AND people scratching their heads.
Warn about missing required programs.
Related: https://github.com/flatpak/flatpak/issues/5020
> tests: Check if program exists before using it

- common/flatpak-run.c
- doc/flatpak-run.xml
These environment variables inform the Vulkan loader on where to find driver files. Since they typically point to locations on the host filesystem, any application that attempts to load Vulkan within the flatpak sandbox would break with these set.
Anyone who explicitly wishes to point toward a Vulkan driver within the flatpak sandbox can do so using the `--env` parameter.
> flatpak-run: Unset VK_DRIVER_FILES and VK_ICD_FILENAMES

- .github/workflows/check.yml
- common/flatpak-dir.c
Use the new GetUsersLanguages() method from AccountsService to get the
list of all the locales that each user is interested in.
See https://gitlab.freedesktop.org/accountsservice/accountsservice/-/merge_requests/99
Closes: #5006
> dir: Use new AccountsService feature to get languages

- common/flatpak-run-wayland.c
To align with work in D-Bus, the security-context's sandbox engine names are now supposed to follow the reverse-DNS style.
This change should be fine because there has not been a release of flatpak with security-context support, yet.
Related: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/253
We need to either merge both MRs or none of them.
> flatpak-run-wayland: Change security-context sandbox engine name

- app/flatpak-builtins-remote-info.c
- app/flatpak-builtins-remote-ls.c
- app/flatpak-builtins-search.c
- app/flatpak-builtins-utils.c
- app/flatpak-builtins-utils.h
Hi!
This patch adjusts Flatpak to build with the currently in-development AppStream 1.0 series as well as the older 0.16.x series.
While AppStream 1.0 is not currently released yet, I also do not expect any major API changes to happen anymore (if everything goes well we will release it late this or early next month), so this patch should be safe to merge already, for future-proofing.
Cheers,
Matthias
> Adjust to AppStream 1.0 API changes

- doc/flatpak-metadata.xml
It'd be nice if these sections could be referenced through a link, at most I can get a https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-metadata. I wanted to reference it in the flathub docs https://github.com/flathub/documentation/pull/112
> docs: Clarify that an app can own its app-id as subname of MPRIS bus

- portal/flatpak-portal.c
- session-helper/flatpak-session-helper.c
Otherwise, the child process will inherit GIO_USE_VFS=local, breaking its ability to use GVfs and other GIO plugin interfaces.
Resolves: https://github.com/flatpak/flatpak/issues/5567
> portal, session-helper: Save original environment and use it for child

- meson.build
This fixes:
| Program /usr/bin/wayland-scanner found: NO
|
| ../git/common/meson.build:123:25: ERROR: Program '/usr/bin/wayland-scanner' not found or not executable |
| A full log can be found at /home/flk/poky/build/tmp/work/corei7-64-poky-linux/flatpak/1.15.6/build/meson-logs/meson-log.txt | ERROR: meson failed
At least for the openembedded build environment
> meson.build: require native wayland-scanner

- po/de.po
This has been bothering me for a while... looking forward to translate more lines in the future.
> Fix formatting for some German messages

- common/flatpak-run.c
If flatpak is run within a container manager that sets the `container` environment variable, it will override the attempted `flatpak` value.
> run: Ensure container environment variable is used

- tests/test-bundle.sh
- tests/test-update-portal.sh
These tests try to install flatpaks, which fails in the system case when FUSE isn't available to mount revokefs-fuse.
> tests: Skip more tests when FUSE isn't available

- app/flatpak-builtins-uninstall.c
- common/flatpak-dir-private.h
- common/flatpak-dir.c
- common/flatpak-installation.c
- common/flatpak-transaction.c
- doc/flatpak-metadata.xml
- tests/list-unused.c
- tests/test-unused.sh
In order to maintain a system over time update automatically removes any EOL runtimes that are unused.
This extends it to also remove any autopruned refs. In practice this means removing no longer used driver versions as the system is updated.
Closes #5261
> update: Make autopruned refs automatically removed

- common/flatpak-dir.c
```
(flatpak update:8279): GLib-GIO-CRITICAL **: 15:50:11.938: GFileInfo created without standard::is-symlink
(flatpak update:8279): GLib-GIO-CRITICAL **: 15:50:11.938: file ../gio/gfileinfo.c: line 1677 (g_file_info_get_is_symlink): should not be reached
(flatpak update:8279): GLib-GIO-CRITICAL **: 15:50:11.957: GFileInfo created without standard::is-symlink
(flatpak update:8279): GLib-GIO-CRITICAL **: 15:50:11.957: file ../gio/gfileinfo.c: line 1677 (g_file_info_get_is_symlink): should not be reached
(flatpak update:8279): GLib-GIO-CRITICAL **: 15:50:11.979: GFileInfo created without standard::is-symlink
(flatpak update:8279): GLib-GIO-CRITICAL **: 15:50:11.979: file ../gio/gfileinfo.c: line 1677 (g_file_info_get_is_symlink): should not be reached
(flatpak update:8279): …
```
> dir: Fix glib criticals

- .github/workflows/check.yml
We added this entirely unrelated apt repo to make CI work, but in fact it now makes CI fail.
This reverts commit b6d5e20857b3587c212ce97de78cdbc2ef01d548.
> Revert "CI: Add mono apt repo to fix build"

- doc/flatpak-run.xml
Do not accept this PR if you enjoy reading a sentence like this:  arguments between '@@ u' and '@@' are considered uris, and any file: uris are exported.
> Update flatpak-run.xml - Fix ambiguity due to lack of punctuation & capitalization

- app/flatpak-builtins-info.c
Flatpak looks for extensions in all installations, but `flatpak info -e` would display an error when an extension isn't present in the same installation as the ref.
Also display the installation name for each extension.
I couldn't see a good way to get the installation name for unmaintained extensions without substantial changes, so I left them as 'unknown'.
Side note: I've always known those as 'unmanaged' extensions, but I've just learned that flatpak doesn't call them that. It took me a bit to realize that's what I was looking at, and not something relating to the typical meaning of 'unmaintained'. https://github.com/flatpak/flatpak-docs/pull/419 uses 'unmanaged' throughout; maybe we should change to that? The term is only exposed in the UI here in `flatpak info -e`, and it's not in …
> info: display extensions found in other installations

- doc/flatpak-metadata.xml
Follow-up to #5481
This is consistent with other places.
> doc: Add since version for --device=input

- common/flatpak-bwrap-private.h
- common/flatpak-bwrap.c
- common/flatpak-run.c
- tests/test-run.sh
* Always allow app to inherit redirected fds from flatpak-run(1)
As noticed on #5615, under normal circumstances, flatpak-run(1) replaces itself with the bwrap process via execve(), and does not close any fds that it might have inherited from its parent. This allows for patterns like:
flatpak run com.example.App --in-fd=3 --out-fd=5 3<foo 5>bar
However, using execve() is annoying when trying to analyze code coverage, because the coverage instrumentation does not get the opportunity to write out its data during exit, so it is possible to set FLATPAK_TEST_COVERAGE=1 to make flatpak run the app as a child process and wait for it. This puts us on the code path normally used for apps launched in the background by flatpak_installation_launch_full(), which *don't* inherit arbitrary fds from …
> Always allow app to inherit redirected fds from flatpak-run(1)

- app/flatpak-builtins-create-usb.c
- app/flatpak-cli-transaction.c
- app/flatpak-quiet-transaction.c
- common/flatpak-dir.c
- common/flatpak-locale-utils.c
- common/flatpak-prune.c
- common/flatpak-transaction.c
- common/flatpak-utils.c
- icon-validator/validate-icon.c
- portal/flatpak-portal-app-info.c
- portal/flatpak-portal.c
- session-helper/flatpak-session-helper.c
- system-helper/flatpak-system-helper.c
- tests/test-portal.c
- tests/test-update-portal.c
Build with address sanitizer and run the tests
> Fix memory leaks

- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-run-sockets.c
- common/flatpak-run-wayland-private.h
- common/flatpak-run-wayland.c
- doc/flatpak-build-finish.xml
- doc/flatpak-build.xml
- doc/flatpak-metadata.xml
- doc/flatpak-override.xml
- doc/flatpak-run.xml
- tests/test-exports.c
1. For security context creation, only relies on WAYLAND_DISPLAY, do not
use WAYLAND_SOCKET since the file descriptor defined by WAYLAND_SOCKET
can be only consumed once.
2. Due to the incompatiblity between WAYLAND_SOCKET and the security
context, add a new permission --socket=inherit-wayland-socket
to limit the usage of WAYLAND_SOCKET to an opt-in feature. Only when
this flag is set, WAYLAND_SOCKET will be passed to the sandbox.
3. When WAYLAND_SOCKET is not inherited, set FD_CLOEXEC to avoid it to
be leaked the to sandbox.
Closes: #5614
> Limit the usage of WAYLAND_SOCKET to an opt-in feature

- meson.build
this fixes:
| Run-time dependency gtk-doc found: NO (tried pkgconfig) |
| ../git/meson.build:206:13: ERROR: Dependency "gtk-doc" not found, tried pkgconfig
> meson.build: require native gtkdoc

- app/Makefile.am.inc
- common/flatpak-bwrap.c
- common/flatpak-dir.c
- common/flatpak-run-dbus.c
- common/flatpak-run.c
- common/flatpak-utils-base-private.h
- common/flatpak-utils-base.c
- portal/flatpak-portal.c
- system-helper/flatpak-system-helper.c
- tests/Makefile.am.inc
* build: Consistently put libglnx.la last in lists of dependencies
It needs to be able to satisfy dependencies of higher-level Flatpak
static libraries.
* Replace flatpak_close_fds_workaround() with g_fdwalk_set_cloexec()
flatpak_close_fds_workaround() wasn't technically async-signal-safe,
because the requirement for sysconf() to be async-signal-safe was
removed in POSIX.1-2008.
It could also leave high fds open in some cases: in practice
sysconf(_SC_OPEN_MAX) returns the soft resource limit, but if our
resource limit has been reduced by an ancestor process, we could
conceivably still have fds open and inherited above that number.
We can fix this by using g_fdwalk_set_cloexec() with GLib >= 2.79.2,
or the backport in libglnx with older GLib. This uses close_range()
if possible, falling …
> Replace flatpak_close_fds_workaround() with g_fdwalk_set_cloexec()

- doc/Makefile.am
- doc/flatpak-docs.xml.in
- doc/flatpak-install.xml
- doc/flatpak-remote-add.xml
- doc/flatpak-remote.xml
- doc/flatpak.xml
- doc/flatpakref.xml
- doc/flatpakrepo.xml
- doc/meson.build
Added symlinks to preserve flatpak-prefixed names.
Also fixed section reference in flatpak-install(1).
Followup to https://github.com/flatpak/flatpak/pull/5659
> doc: rename man pages to flatpakref(5) and flatpakrepo(5)

- tests/httpcache.c
- tests/test-context.c
- tests/testlibrary.c
Continuation of #5690, fixing bugs in the test itself. Detected by running tests compiled with AddressSanitizer.
This fixes testlibrary, plus a few issues in other tests that I found before reducing the scope of what I was trying to just testlibrary.
After this has been reviewed I'm intending to continue to clean up AddressSanitizer issues as time permits, but repeatedly running the tests under AddressSanitizer is rather time-consuming, so I'd prefer to land this a piece at a time.
---
* tests: Fix a double-free when exercising argument parsing
g_option_context_add_group() takes ownership of the group that it's
given, so we can't also free it.
Fixes: fab0f8ed "test-context: Exercise some corner cases for merging filesystems"
* testlibrary: Don't leak transactions
* testlibrary: Don't leak …
> Fix memory errors in testlibrary and other test code

- common/flatpak-dir.c
- common/flatpak-run.c
- configure.ac
- meson.build
These symbols were soft-renamed in libmalcontent 0.5.0 (released in February 2020). We can probably now safely depend on that, and use the renamed versions.
> common: Fix use of deprecated libmalcontent symbols

- common/flatpak-dir.c
- meson.build
- meson_options.txt
- tests/can-use-fuse.c
- tests/libtest.sh
- tests/meson.build
The hard-coding is not appropriate. According to libfuse 3.0.0 release notes: "The fusermount and mount.fuse binaries have been renamed to fusermount3 and mount.fuse3 to allow co-installation of libfuse 2.x and 3.x". Some distributions seem to install a symlink, but this is not upstream's default behavior.
In addition, fusermount might be provided from non-distro sources. So a build-time option takes precedence over auto-detection logic.
Fixes #5104
Fixes #5694
`executable.path()` is deprecated in meson, but `full_path` was only available in 0.55, and the minimum version is 0.53. So I guess this introduces a bit of technical debt...
@smcv as promised
> Do not hard-code fusermount, add option or auto-detect instead

- common/flatpak-appdata.c
- tests/make-test-app.sh
- tests/test-info.sh
`<developer_name>` has been deprecated in favor of `<developer>` with a `<name>` child. We need to ensure that this developer name isn't parsed as the application name.
Fixes: #5700
> appdata: exclude <name> element inside <developer>

- app/flatpak-builtins-ps.c
This is used for the active and background columns.
There still doesn't appear to be any way to find the backend for a portal, as mentioned in the original commit: https://github.com/flatpak/flatpak/commit/5ec73b9a9af8d3b9c3d4479fcee05e5eef94ee6a
> ps: Add gnome to background portal backend list

- common/flatpak-dir.c
This is best effort. There is a 2s timeout and if something fails everything continues on.
This is called from flatpak_dir_run_triggers because it gets called whenever we might have changes to the exported service files.
> dir: Reload DBus daemon config to ensure services get picked up

- common/flatpak-bwrap.c
- portal/flatpak-portal.c
- system-helper/flatpak-system-helper.c
With older GLib, it's provided by libglnx, but with newer GLib, we need to include the correct header.
Fixes: 7b1cd206 "Replace flatpak_close_fds_workaround() with g_fdwalk_set_cloexec()"
> Fix missing declaration for g_fdwalk_set_cloexec() with GLib 2.80.x

- common/flatpak-prune.c
Otherwise, an out-of-bounds left shift can occur, as diagnosed by UBSan here:
../../../../src/flatpak/common/flatpak-prune.c:387:14: runtime error: left shift of 253 by 24 places cannot be represented in type 'int'
> flatpak-prune: Make sure to calculate hash in the unsigned domain

- common/flatpak-run.c
- tests/test-repo.sh
If the current app data dir is removed, flatpak would try to migrate the
symlink that it had previously created, creating a symlink loop.
Fixes: #5668
I had considered also making `uninstall --delete-data` remove the leftover symlinks, but that turns out to be a larger project than anticipated. The delete-data implementation is in the app, not libflatpak, so the same change would need to be made in the other frontends for consistency. A more sophisticated implementation could be added to the library, but I don't know if it's worth the effort, given that the symlinks should be harmless with this change in place.
> run: Ignore leftover eol-rebase data dir symlink

- app/flatpak-builtins-list.c
- app/flatpak-builtins-remote-ls.c
- app/flatpak-builtins-search.c
- app/flatpak-table-printer.c
Instead of having each command call `flatpak_get_window_size()`, do it by default in `flatpak_table_printer_print()`. This fixes the display of ellipsized columns in `flatpak remotes -d` with wide terminals.
If preferred, I can fix the remotes command instead, but this seemed a better option.
> app: Improve table ellipsization

- app/flatpak-cli-transaction.c
The transaction ops are a g_autolist(FlatpakTransactionOperation) which means the list gets freed automatically. Calling g_list_free_full without clearing the variable to NULL results in a double-free.
> cli-transaction: Do not double free transaction ops

- tests/installed-tests.sh.in
- tests/libtest.sh
- tests/meson.build
Otherwise, tests for OCI and the update portal fail with:
/usr/libexec/installed-tests/Flatpak/libtest.sh: line 611: FUSERMOUNT: unbound variable
Fixes: 2cb17b4e "Do not hard-code fusermount, add option or auto-detect instead"
> tests: Make sure FUSERMOUNT gets set for "as-installed" tests

- tests/test-run.sh
Arguably bwrap should exit with status 127 if it can't find the executable, but right now it exits 1, so we accept any nonzero status. The implementation was correct, but the comment was wrong.
Fixes: 84984e49 "test-run: Add a reproducer for CVE-2024-32462"
> tests: Fix a misleading comment

- .github/workflows/check.yml
* workflows: Disable Microsoft-specific apt repository
We don't need anything from here, and its secure-apt signing is
currently broken.
Workaround-for: https://github.com/orgs/community/discussions/120966
---
If Github provided an image that was purely Ubuntu (rather than the "Ubuntu with Github and Microsoft additions" that they *actually* provide) then we wouldn't have to do this sort of thing every few months.
> workflows: Disable Microsoft-specific apt repository

- common/flatpak-run.c
- doc/flatpak-run.xml
I don't think this env var makes much sense to pass into the sandbox for similar reasons to LD_LIBRARY_PATH. Libraries from the host just aren't relevant.
Users can still pass `--env=LD_PRELOAD=/foo` to use this functionality.
> run: Don't inherit LD_PRELOAD/LD_AUDIT from the host

- tests/testlib.h
- tests/testlibrary.c
* tests: Add macros to assert that a copied string has a desired value
Suggested by Patrick during review of #5691.
* testlibrary: Make use of assert_cmpstr_free_lhs(), etc.
> tests: Add macros to assert that a copied string has a desired value

- .devcontainer/devcontainer.json
This is useful for easy development on a live system without compromising the developer's `/usr`.
> Add devcontainer for codespace development

- common/flatpak-dir.c
Related to issue #4746.
This makes these two strings:
1. `No entry for %s in remote '%s' summary flatpak cache `
2. `No entry for %s in remote '%s' summary cache `
look like this other string in the code:
`No entry for %s in remote %s summary flatpak sparse cache`
This technically removes the two strings and adds one new one: `No entry for %s in remote %s summary flatpak cache`.
> dir: Uniformize two similar strings

- common/flatpak-dir.c
The path was clobbered make the g_autoptr no work
The leak was around a 100 bytes.
> flatpak-dir: Fix a memory leak when installing a package

- tests/libtest.sh
- tests/make-test-app.sh
- tests/test-prune.sh
I was trying to get the `flatpak` for Chimera Linux template to run tests. However, due to Chimera Linux using core utilities based on FreeBSD's, some stuff used in the test shell scripts didn't work there and caused issues. While I eventually gave that endeavour up, I wanted to upstream the upstreamable changes I had anyway.
> tests: improve shell portability

- profile/meson.build
I don't know if there's a reason this wasn't being installed, but it does seem to work correctly in a quick test with tcsh. I don't see any evidence it was ever installed in autotools either.
> profile: Install flatpak.csh

- common/flatpak-dir.c
Closes: https://github.com/flatpak/flatpak/issues/5856
Fixes: 9532c8d3 ("dir: Reload DBus daemon config to ensure services get picked up")
> dir: Free the returned GVariant of g_dbus_connection_call_sync

- app/flatpak-builtins-permission-list.c
This occur by just running flatpak permission <SOME APP>
> flatpak-permissions: Fix a memory leak

- doc/flatpak-config.xml
To include all languages, the languages key must be set to `*all*`, not `all`. That was apparently intended to provide symmetry with how the value is represented in the output of `flatpak config`.
Alternatively, it might be better to only mention `*`. I don't really see the point of including two equivalent values (that are both stored as `xa.languages=''`), especially when `*all*` is so awkward. I'm happy to do that instead if you'd like.
> doc: Correct special value for flatpak config

- common/flatpak-run.c
In a restrictive environment where access to /sys/ is blocked to regular users, flatpak should not depend on sysfs as discussed in issue #5138
> Test whether sysfs mountpoints are accessible before mounting them

- common/flatpak-dir.c
parse_ref_file() cleared all its out params to NULL, with the exception of collection_id_out. Make sure to clear this one as well to avoid surprises in the future.
Fixes commit ae7d96037 that added collection ID support to flatpakref.
> dir: Make sure all parse_ref_file out params are consistently cleared

- common/flatpak-dir.c
- common/flatpak-repo-utils.c
- oci-authenticator/flatpak-oci-authenticator.c
- portal/flatpak-portal.c
- revokefs/main.c
- tests/flatpak-asan.supp
- tests/flatpak.supp
- tests/meson.build
Tried to reproduce an issue with address sanitizer but couldn't. Then tried to see if the tests would reproduce the issue but they would fail rather randomly. Figured out that we rely on structured output in a bunch of places so redirecting all the asan output works.
Fixed most of the issues that asan then found but couldn't figure out the ones coming from:
```
leak:flatpak_authenticator_request_proxy_new_for_bus_sync
leak:flatpak_authenticator_proxy_new_for_bus_sync
```
> Add support for address sanitizer and fix a bunch of memory leaks

- app/flatpak-complete.c
- app/flatpak-complete.h
- app/flatpak-table-printer.c
- common/flatpak-dir.c
- common/flatpak-run-dbus.c
- common/flatpak-run.c
- common/flatpak-utils.c
- revokefs/demo.c
- session-helper/flatpak-session-helper.c
- tests/can-use-fuse.c
- tests/testcommon.c
Prompted by updating the copy of some Flatpak-derived code in a project that compiles with `-Wwrite-strings` ([steam-runtime-tools](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools)).
This is not enough to get Flatpak fully const-correct for strings: there are still a lot of missing casts around `flatpak_strv_merge()` and `flatpak_subpaths_merge()` (which should ideally take `const char * const *` arguments, but that would be inconvenient for many callers).
* utils: Be more const-correct
For historical reasons C string literals are officially of type `char *`,
but if we build with -Wwrite-strings, they are `const char *` as they
should be.
* complete: Slightly increase const-correctness
* table-printer: Slightly increase const-correctness
* Constify tables of immutable strings
* …
> Use const strings where it's straightforward to do so

- app/flatpak-main.c
- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-dir.c
- common/flatpak-run.c
- common/flatpak-utils-private.h
- common/flatpak-utils.c
* utils: Add flatpak_is_debugging()
This can be used to disable code paths that assemble relatively
"expensive" debug information when debugging is not enabled.
It's activated by `flatpak -v -v`.
With a sufficiently modern GLib version, it also activates for
`G_MESSAGES_DEBUG=all` or `G_MESSAGES_DEBUG=flatpak`.
* context: Add a function to log a FlatpakContext
This writes out the context as a series of debug messages.
* dir: When we load overrides, log them as debug messages
The more involved parts of this are skipped if debug logging is disabled.
This will help to diagnose what is going on when users have added
overrides that make their app not work as intended.
* run: Debug-log sources of parameters other than overrides
Every time we load something into the context, debug-log what it …
> Log overrides and context when running an app

- subprojects/dbus-proxy.wrap
We still only require a system xdg-dbus-proxy to be v0.1.0 or later, although a newer release is recommended.
> subprojects: Update dbus-proxy.wrap to v0.1.6

- subprojects/libglnx/glnx-backports.h
- subprojects/libglnx/meson.build
* Fix function detection when using -Werror=return-type (Resolves: flatpak/flatpak#5778)
* Add a fallback definition for G_PID_FORMAT
* Avoid warnings for g_steal_fd() when targeting older GLib
* Include \<glib-unix.h> from glnx-backports.h
---
Changes: https://gitlab.gnome.org/GNOME/libglnx/-/merge_requests/55, https://gitlab.gnome.org/GNOME/libglnx/-/merge_requests/56, https://gitlab.gnome.org/GNOME/libglnx/-/merge_requests/57, https://gitlab.gnome.org/GNOME/libglnx/-/merge_requests/59
>  Update subtree: libglnx 2024-08-23

- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-run-dbus-private.h
- common/flatpak-run-dbus.c
- common/flatpak-run.c
- data/org.freedesktop.portal.Flatpak.xml
- doc/flatpak-run.xml
- portal/flatpak-portal.c
- tests/test-portal.c
This is necessary for WebKit, and potentially LibreOffice, that may spawn a Flatpak subsandbox proceess with an a11y tree, and may need to connect both trees.
Add `--a11y-own-name` to flatpak-run, and a corresponding way to pass this value through the Flatpak portal.
> Allow owning app id names on the a11y bus

- common/flatpak-context-private.h
- common/flatpak-context.c
- common/flatpak-run.c
- doc/flatpak-build-finish.xml
- doc/flatpak-build.xml
- doc/flatpak-metadata.xml
- doc/flatpak-override.xml
- doc/flatpak-run.xml
This adds a new `usb` device in the list to grant access to the whole
USB bus. This is narrower than `all` and should be enough for
anything accessing the USB directly (i.e. using libusb or equivalent).
This doesn't grant access to synthesized devices, i.e those exposed
in /dev but using USB, including but not limited to USBserial, webcams,
hidraw, hid, sound.
Close #4405 
-- END COMMIT MESSAGE
This is part of the ongoing work in #5620.
With `--device=usb` the whole USB bus is exposed without having to use `--device=all`.
This has the same problem from #5681 with PR #5708 as a proposal.
With the USB device portal from #5620, the plan is to have the disable if the use of the portal is requested. The idea is to compromise between the work required to use the USB portal (it's not zero cost) …
> flatpak-run: Mount /dev/bus/usb with --device=usb

- common/flatpak-context.c
Because flatpak_get_real_xdg_runtime_dir() return an allocated string we have to return strduped.
Close flatpak/flatpak#5920
> context: Fix a memory leak

- common/flatpak-dir.c
- doc/flatpak-remote.xml
- doc/flatpak.xml
- doc/flatpakrepo.xml
This is more compliant with FHS specification. Most remarkably, /etc
is not appropriate to hold distro configuration, which is a common
use for the remotes.d feature. It is better practice to put things
under /usr/share, and let the system administrator modify /etc to
their will, of course giving them priority.
In the process, fix a couple of leaks. 
I know that FHS might not be the most up-to-date standard. But luckily the purpose of /etc hasn't really changed. FHS states: ` /etc : Host-specific system configuration`. So not feasible for distributions to put their configuration.
> dir: search for repositories also under FLATPAK_BASEDIR

- common/flatpak-run.c
- doc/flatpak-run.xml
We now resolve the zoneinfo and always make it available at
/usr/share/zoneinfo in the sandbox so we unset TZDIR to get flatpak apps
looking at the right directory.
Completely untested.
> run: Unset $TZDIR environment variable

- common/flatpak-dir.c
When iterating more than one group, the variable got clobbered. Narrowing their scope helps.
This was triggered installing an Inkscape test build
The leak was:
```
==158172==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 40 byte(s) in 2 object(s) allocated from:
#0 0x7f39fc2f7350 in calloc (/lib64/libasan.so.8+0xf7350) (BuildId: a4ad7eb954b390cf00f07fa10952988a41d9fc7a)
#1 0x7f39fc980871 in g_malloc0 (/lib64/libglib-2.0.so.0+0x64871) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
#2 0x7f39fc9a1394 in g_shell_parse_argv (/lib64/libglib-2.0.so.0+0x85394) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
#3 0x5855bd in export_desktop_file ../common/flatpak-dir.c:7676
#4 0x588369 in rewrite_export_dir ../common/flatpak-dir.c:7848
#5 0x587965 in rewrite_export_dir …
```
> Fix a memory leaks

- app/flatpak-builtins-remote-ls.c
- common/flatpak-dir.c
- common/flatpak-exports.c
- common/flatpak-repo-utils.c
- common/flatpak-transaction.c
- tests/test-exports.c
For historical reasons g_qsort_with_data() "only" works with up to 2**31 items, so it won't necessarily work for pathologically large arrays and therefore is deprecated.
One advantage of g_qsort_with_data() and its replacement g_sort_array() is that GLib guarantees that they are a stable sort (will not permute items that already compare equal), which is not a guarantee for glibc's qsort() and qsort_r(). However, I don't think it's actually relevant whether we are doing a stable sort in any of these places: most of the time we are sorting an array of unique items (often the keys of a hash table, which are necessarily unique), therefore the compare function will not compare equal in any case.
Another advantage of the GLib functions is that they are portable, unlike qsort_r(). However, …
> app, common, tests: Avoid deprecated g_qsort_with_data()

- common/flatpak-run-private.h
- common/flatpak-run.c
The systemd Desktop Environments conventions for cgroup names is
`app[-<launcher>]-<ApplicationID>[@<RANDOM>].service`
where RANDOM should ensure that multiple instances of the application can be launched. Currently flatpak uses the PID of itself but the instance fullfills this convention and is a bit more useful for matching the cgroup to a flatpak instance.
> run: Use the instance id in the cgroup name

- app/flatpak-builtins-search.c
We add the component name as part of the fallback search.
Before this patch, queries as
flatpak search Element
or
flatpak search d-spy
return no results even though the search term coincides with the application name.
> app: Check for component name when searching

- subprojects/bubblewrap.wrap
<https://github.com/containers/bubblewrap/releases/tag/v0.11.0>
We don't use any of the new features yet, so the minimum required version in the build system is still 0.10.0.
> subprojects: Update bubblewrap to v0.11.0

- common/flatpak-run-private.h
- common/flatpak-run.c
apply_extra_data() passes a null instance ID to
flatpak_run_add_environment_args(), causing a segfault in flatpak_run_in_transient_unit() which assumes the instance ID is non-null. Revert this for now: flatpak#5962 was non-essential, and we can redo it in a less crashy way later.
This reverts commit 7d6f3e8b6b51f26b380235fad8e32a4872449ff1.
Resolves: https://github.com/flatpak/flatpak/issues/6009
cc @swick 
I'm going to merge this immediately, assuming CI is successful. I'm happy to review a redo of #5962 (and I might even implement one myself if I find some time for it) but for now let's stop the bleeding, since several major distros are (IMO unwisely) already using our development releases as though they were stable releases.
> Revert "run: Use the instance id in the cgroup name"

- tests/meson.build
Without this, "as-installed" tests via `ginsttest-runner` will fail, for example in Debian's autopkgtest framework.
Fixes: 1d56bd37 "context: Implement device lists for usb"
> tests: Install missing test data

- common/flatpak-context.c
flatpak-context.c contains two strings mentioning `A list of USB device that are enumerable`.
This feels a bit strange grammatically, so change it to plural with `list of USB devices`.
> context: Use plural form in string

- common/flatpak-run-wayland.c
* wayland: Avoid some duplication when getting the Wayland display name
There's no need to have the logic for falling back to `wayland-0` in more
than one place.
* wayland: Only have one code path to bind-mount WAYLAND_DISPLAY into sandbox
In the older code path where we were not using Wayland security contexts,
we would try to preserve the name of the Wayland display socket
(`$WAYLAND_DISPLAY`), only falling back to `wayland-0` if the name was
something unconventional (contains `/` or does not start with `wayland-`).
This means that in practice, apps could often successfully use a value
of `$WAYLAND_DISPLAY` from the wrong "world" - for example reading the
value used outside the sandbox from a file in code that runs inside the
sandbox, or conversely, passing the value used inside the …
> wayland: Only have one code path to bind-mount WAYLAND_DISPLAY into sandbox

- app/flatpak-cli-transaction.c
- app/flatpak-tty-utils-private.h
- app/flatpak-tty-utils.c
Following on systemd adopting the progress OSC that ConEmu and Windows Terminal use, this exports the progress percentage to the terminal emulator.
VTE also has support for this in the upcoming 0.80 release and is used by Ptyxis to display progress in the tab widget.
> flatpak: emit progress escape sequence

- common/flatpak-dir.c
- meson.build
- tests/meson.build
Now that we read remotes from `$datadir/flatpaks/remotes.d` as well as `/etc/flatpaks/remotes.d`, we should have a mechanism to redirect this, as we do for almost all other filesystem path locations.
To avoid an explosion of new variables, we introduce `FLATPAK_OS_CONFIG_DIR` to represent configuration that ships with the operating system.
This is useful:
* To fix sandboxing of tests
* When installing using flatpak into a chroot, so that we read the chroot's configuration rather than the host.
It also is used when reading triggers, but the current `FLATPAK_TRIGGERSDIR` is left for compatibility.
---
Notes:
* Should this apply to trigger at all? Are the triggers really configuration?
* If it *should* apply for triggers, then do we need compat handling of `FLATPAK_TRIGGERSDIR`?
> Add FLATPAK_DATA_DIR environment variable

- subprojects/libglnx/glnx-shutil.c
- subprojects/libglnx/meson_options.txt
- subprojects/libglnx/tests/test-libglnx-shutil.c
* Fix an assertion failure attempting to create a directory that exists
as a dangling symlink ([GNOME/libglnx#1](https://gitlab.gnome.org/GNOME/libglnx/-/issues/1))
* Fix a Meson deprecation warning ([GNOME/libglnx!60](https://gitlab.gnome.org/GNOME/libglnx/-/merge_requests/60))
> Update subtree: libglnx 2024-12-06

- common/flatpak-installation.c
This is a new warning. Reproducible on F41
Fixes:
```
../common/flatpak-installation.c:1963: Warning: Flatpak: invalid closure annotation: only valid on callback parameters 
../common/flatpak-installation.c:1858: Warning: Flatpak: invalid closure annotation: only valid on callback parameters 
../common/flatpak-installation.c:2129: Warning: Flatpak: invalid closure annotation: only valid on callback parameters 
../common/flatpak-installation.c:2014: Warning: Flatpak: invalid closure annotation: only valid on callback parameters 
../common/flatpak-installation.c:1732: Warning: Flatpak: invalid closure annotation: only valid on callback parameters 
../common/flatpak-installation.c:2177: Warning: Flatpak: invalid closure annotation: only valid on callback parameters …
```
> gir: Fix closure annotations

- app/flatpak-tty-utils.c
- doc/flatpak.xml
And add the FLATPAK_PTY_PROGRESS env var to re-enable it.
This seems to only be supported by recent versions of terminal emulators which will cause problems with shipping Flatpak on older distros.
Closes https://github.com/flatpak/flatpak/issues/6052
> flatpak: Disable progress escape sequence by default

- portal/flatpak-portal.c
Include the non-matching name in the message for ease of debugging.
This was useful for https://github.com/flathub/engineer.atlas.Nyxt/issues/19
> portal: Improve error message for invalid a11y own name

- doc/flatpak.xml
Reference documentation only, no functional changes.
* flatpak(1): Sort environment variables alphabetically
* flatpak(1): Re-word introduction to the list of environment variables
This is more grammatically correct.
* flatpak(1): Document more environment variables
> flatpak(1): Document more environment variables

- doc/flatpak-permission-show.xml
This was probably accidentally copied from flatpak-permissions(1).
Closes #4859
> flatpak-permission-show(1): Remove incorrect paragraph from description

- app/flatpak-tty-utils.c
The VTE project has requested that we terminate our OSC sequence with ANSI_ST rather than \007 (BEL) and may enforce this in the near future.
> tty-utils: use ANSI_ST to terminate OSC sequence

- common/flatpak-run.c
- doc/flatpak-run.xml
This repeatedly lead to errors when users had it set to a directory accessible from the flatpak when importing pillow/PIL.
Briefly discussed and suggested in #4280 
Incidents which led me to create this PR:
https://github.com/pdfarranger/pdfarranger/issues/866
https://github.com/pdfarranger/pdfarranger/issues/1194 (not yet confirmed but very likely)
> run: Unset PYTHONPYCACHEPREFIX from envrionment

- common/flatpak-dir.c
Return a borrowed extra_data_name from g_variant_get_child
> flatpak-dir: Fix a memory leak installing extra-data

- common/meson.build
Static libraries do not carry information about their dependencies. Thus, libflatpak_dep must include all of the dependencies for libraries to link against libflatpak.  To do this, I've repurposed the libflatpak_common_deps variable, which previously was either empty or contained only wayland_client, and was then included into the list of dependencies for libflatpak-common, to be a list of all dependencies required to both build libflatpak-common, and link against it (or libflatpak).
This fixes building Flatpak with -Ddefault_library=static.  gtkdoc must currently be disabled due to [a Meson bug I'm working on][1].
[1]: https://github.com/mesonbuild/meson/pull/14257
> build: fix build with -Ddefault_library=static

- app/flatpak-builtins-uninstall.c
`confirm_runtime_removal()` doesn't know about autoprune-unless extensions, so it prompts unnecessarily when they're removed by `flatpak uninstall --unused`. To avoid this, we can simply skip it and trust `flatpak_dir_list_unused_refs()`.
Closes #5712
Helps #2718
> uninstall: Skip in-use runtime check with --unused

- common/flatpak-dir.c
Fixes 9cd682b057206de8596bdba6303a0414207ef621
Helps #5170
> dir: Avoid overwriting error in apply_extra_data()

- po/ru.po
Change "системой" to "системной"
> fix: typo in `ru.po`

- .github/workflows/block-autosquash-commits.yml
- .github/workflows/check.yml
This is necessary for the merge queue.
> ci: Trigger CI on 'merge_group' event

- .github/workflows/block-autosquash-commits.yml
Instead of using an old, unmaintained action, manually check using the GitHub CLI tool and jq.
> ci: Rework autosquash checker

- portal/flatpak-portal.c
Most access to the `client_pid_data_hash` hash table are unsafe due to
threading.
One approach to solve this would be to protect the hash table with a
mutex, but as per a deeper analysis, nothing in these callbacks is
slow or heavy enough to justify the need for separate threads.
Make method invocations run in the main thread.
Closes: https://github.com/flatpak/flatpak/issues/5605
>  portal: Don't run method invocations in a thread

- po/ro.po
"Branch" was translated to Romanian as a verb, but it's actually used as a noun.
Replaced the verb with the noun.
> Fix Romanian translation

- portal/flatpak-portal.c
>  backport: portal: Don't run method invocations in a thread

- common/flatpak-run-sockets.c
- common/flatpak-run-wayland-private.h
- common/flatpak-run-wayland.c
To handle those details at the right place (flatpak-run-wayland.c), we pass if the wayland socket is allowed to flatpak_run_add_wayland_args and handle it there instead of in the caller.
Closes #3948
> wayland: Unset WAYLAND_DISPLAY, WAYLAND_SOCKET when socket is disabled

- common/flatpak-run.c
udmabuf allows clients to allocate virtual memory as dmabufs, which then potentially can be imported by other dma subsystems - most importantly GPU drivers and KMS. This can avoid copies and thus increase performance.
Unlike other dmabuf allocators like e.g. dma heaps this doesn't have known issues relevant for sandboxing. Notably memory accounting works as expected, so apps can't use udmabuf to escape resource limitations. For this reason systemd, since version 257[1], grants "uaccess" access to udmabuf by default, considering it as "safe".
With udmabuf increasingly being availably by default, various apps and libraries start making use of it - examples include libcamera, mesa llvmpipe and Gstreamer. Thus let's grant access to it in Flatpak as well.
For now limit it to "dri" access as …
> run: Add udmabuf to --device=dri

- common/flatpak-prune.c
The original idea behind this code was that the initial lockless scan of reachable objects will make the locking one fast enough that it won't matter to software managing flatpak repos like flat-manager. Few years later I can say this is not true, and the locking variant of scan does take too long and affects Flathub's publishing process.
By keeping only the lockless variant in dry run, we can run it on a weekly schedule without affecting operations, and issue actual pruning with flat-manager which will hold a lock in external system and avoid executing any actions requiring locking to avoid errors/timeouts.
> prune: Move locking operations to execute only outside dry run

- profile/flatpak.sh
Error: SHELLCHECK_WARNING (CWE-758): [#def1]
/etc/profile.d/flatpak.sh:1:1: error[SC2148]: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
Resolves: https://openscanhub.fedoraproject.org/task/51962/log/flatpak-1.16.0-3.fc43/scan-results.html#def1
> profile: fix a shellcheck warning

- CONTRIBUTING.md
Autotools support was removed as of commit 8e63eda, remove mention of the Autotools support in the CONTRIBUTING file
Alternatively, we could still reference the support in 1.14.x, but remove the bit where it says you may set up autotools building in the newer revs.
> CONTRIBUTING: Remove mention of Autotools

- tests/testlib.c
The F_DUPFD and its relative F_DUPFD_CLOEXEC both expect an int argument as extra argument, being the minimal value for the new FD. This argument must be within the accepted range (see ulimit -H -n).
This was detected in Ubuntu during testing against the latest glibc, stracing resulted in:
107244 fcntl(1, F_DUPFD_CLOEXEC, 1847846346272) = -1 EINVAL (Invalid argument)
On the system in question (ppc64el machine running Ubuntu Questing), the relevant limit is 524288.
For the fix we use 3 as a reasonable floor value, as in the first one after stderr. It also happens to be the one used in revokefs/main.c.
Bug-Ubuntu: https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/2121039
> testlib: add expected argument to fcntl(F_DUPFD)

- common/flatpak-utils.c
Enable VA-API extension for Intel GPUs if either i915 or xe is loaded
The xe module supports newer Intel discrete GPUs (the Arc series) and the i915
module is for older or integrated GPUs.
Resolves: https://github.com/flatpak/flatpak/issues/5248
> Enable VA-API extension for Intel GPUs if either i915 or xe is loaded

- common/flatpak-context.c
- common/flatpak-exports-private.h
- common/flatpak-exports.c
- doc/flatpak-build-finish.xml
- doc/flatpak-build.xml
- doc/flatpak-metadata.xml
- doc/flatpak-override.xml
- doc/flatpak-run.xml
Adapted from: https://github.com/flatpak/flatpak/pull/6125
In systemd v259, /run/host/root will be a documented location for bind mounting the host's root filesystem into a container. Ref: https://github.com/systemd/systemd/pull/38384
host-root is the sledgehammer permission for file browsers and similar apps that the user might want to give full access to.
This works same as the existing host keywords by mounting into /run/host/root. applications will need adjustments to essentially treat that path as "root".
Since this opens the door to all sorts of malicious software, the permission should be put under tight review in flatpak repositories.
Resolves: #5723
> exports: add host-root

- common/flatpak-utils-http.c
Fixes c75ba1c7e1587300be9a418116c02d0b6bf8b34e
```
In file included from /usr/lib/aarch64-linux-gnu/glib-2.0/include/glibconfig.h:9,
from /usr/include/glib-2.0/glib/gtypes.h:34,
from /usr/include/glib-2.0/glib/galloca.h:34,
from /usr/include/glib-2.0/glib.h:32,
from /usr/include/glib-2.0/gobject/gbinding.h:30,
from /usr/include/glib-2.0/glib-object.h:24,
from /usr/include/glib-2.0/gio/gioenums.h:30,
from /usr/include/glib-2.0/gio/giotypes.h:30,
from /usr/include/glib-2.0/gio/gio.h:28,
from ../common/flatpak-utils-http.c:23:
In function ‘glib_autoptr_clear_GFileEnumerator’,
inlined from ‘glib_autoptr_cleanup_GFileEnumerator’ at /usr/include/glib-2.0/gio/gio-autocleanups.h:69:1,
inlined from ‘flatpak_get_certificates_for_uri’ at ../common/flatpak-utils-http.c:284:34: …
```
> utils-http: Fix an uninitialised variable warning
