builder/builder-main.c
builder/builder-manifest.c

Capitalize all error messages.

builder: Some consistency fixes for output

---

common/flatpak-utils.c
common/flatpak-utils.h

completion: Don't show one-time switches already in use

---

builder/builder-manifest.c
builder/builder-module.c
builder/builder-module.h

This lets us group modules, and disable them as a group.
It will become more useful when we allow includes.

Support recursive modules

---

app/flatpak-builtins-enter.c
app/flatpak-main.c

The bash completion is this complex, constantly out of date, underfeatured bash script. We really should be doing this in C, similar to how e.g. the gdbus tool does it.

Handle bash completion in C

---

Makefile.am
autogen.sh
common/Makefile.am.inc
document-portal/Makefile.am.inc
lib/Makefile.am.inc
permission-store/Makefile.am.inc
tests/Makefile.am.inc

Here are some build system fixes, mostly around `make distcheck`.

Get "make distcheck" to work

---

tests/test-run.sh

This test effectively assumed that ${test_builddir} is in /home, /opt,
a non-FHS top level directory, or some other directory that isn't
in dont_mount_in_root[] in flatpak-run.c. In a distro build where
${libexecdir} is below /usr, when running the installed-tests
so ${test_builddir} is ${libexecdir}, this assumption doesn't hold.
We can't just copy the file we're dealing with into a subdirectory
of /tmp or /var/tmp either, because those directories aren't
part of --filesystem=host. Meanwhile, we also don't want to pollute
$HOME with test detritus.
For the best possible coverage given all those constraints, we try
three directories: ${test_builddir}; ${TEST_DATA_DIR}, which is
in /var/tmp; and ~/.flatpak-tests, but only if it already exists.
When testing --[no]filesystem=host overrides, …

test-run: avoid testing cases of filesystem binding that won't work

---

system-helper/flatpak-system-helper.c

Reduces code duplication. Also plugs a minor memleak.

system-helper: Reorder flatpak_authorize_method_handler

---

document-portal/xdp-main.c

As soon as we get our D-Bus name, we can start receiving method calls. If
we reply immediately, callers will think our mount point is ready.
In particular, if FUSE is unavailable, we want "flatpak run" to proceed
with no document portal; it currently tries and fails to bind-mount the
nonexistent document portal mount-point into the container.
Signed-off-by: Simon McVittie <smcv@debian.org>

document portal: don't reply to GetMountPoint() until ready

---

common/flatpak-run.c
doc/flatpak-build-finish.xml
doc/flatpak-build.xml
doc/flatpak-override.xml
doc/flatpak-run.xml

We need to expose /run/system/journal/{socket ,stdout} in the sandbox.

make journal logging work in the sandbox

---

doc/Makefile.am
doc/flatpak-metadata.xml

This is useful information that should be available in a
single place.

Document the metadata format

---

Makefile.am
document-portal/Makefile.am.inc
document-portal/xdp-main.c

This PR makes it so that it's possible to open files in /app through the document portal.

Add support to open files in /app

---

document-portal/xdp-fuse.c

In testing readonly exports, I noticed that gedit is does not believe
the mode it gets from stat()ing a file a million times. Instead
it calls access() to determine whether to treat it as readonly.
Since the document portal fuse file system did not implement
access(), gedit treated my file as writable and then failed when
I clicked "Save". With this patch, gedit treats the file as read-only
from the get-go.

document-portal: Implement access()

---

builder/builder-cache.c
builder/builder-context.c
builder/builder-main.c
builder/builder-options.c

These changes fix some memory leaks that valgrind pointed out.

builder: Fix a few memory leaks

---

app/flatpak-builtins-run.c
common/flatpak-run.c
common/flatpak-run.h
configure.ac
doc/flatpak-run.xml

Reverts flatpak/flatpak#202
I'm reverting this because it breaks the tests, and I want to get a release out.
Also, I'm not sure this is quite right, it needs discussions.

Revert "Set up logging to the journal"

---

app/flatpak-builtins-build-export.c

While it is frowned upon nowadays, there are still applications
that use system-provided icons for the Icon field in their desktop
file.
Reduce the error to a warning to allow this for now.

Reduce icon validation

---

builder/builder-source-git.c

Some projects declare their Git submodules with URLs relative to their own.
For example, gedit is hosted at git://git.gnome.org/gedit, and has its libgd submodule declared with the ../libgd URL. We should treat the latter as git://git.gnome.org/libgd.
This was in fact properly done in the past, but I broke it in commit 1171e1d2020b660dda9ebac51775d3f5a2918afc.
This fixes it again.

builder: Handle submodules using with relative URLs

---

document-portal/xdp-main.c

Strip /newroot prefix from document path since validate_parent_dir()
depends on a system path to get the parent directory stat.

document-portal: Fix the document portal for files outside /app

---

po/LINGUAS
po/sk.po

First commit of slovakian translation. I will translate new strings on the fly.

Added slovak translation

---

app/flatpak-builtins-build-bundle.c
app/flatpak-builtins-build-init.c
app/flatpak-builtins-build-sign.c
app/flatpak-builtins-override.c
common/flatpak-dir.c
common/flatpak-utils.c
common/flatpak-utils.h
document-portal/xdp-fuse.c
document-portal/xdp-main.c

Return detailed information about the problem with the name in
the GError. Update all callers.

Make flatpak_is_valid_name set a GError

---

app/flatpak-builtins-enter.c
common/flatpak-run.c
common/flatpak-utils.c
document-portal/xdp-fuse.c
document-portal/xdp-main.c
po/LINGUAS
po/sv.po
system-helper/org.freedesktop.Flatpak.policy.in

Commit 352e761c0ef506f42f818c1da39ae504d45fea36 started the trend
to print the errno error code when unable to open a file, make all
occurrences where files are opened print the same kind of message.

run: Print errno error code consistently.

---

doc/Makefile.am
doc/flatpak-docs.xml.in
doc/flatpak-flatpakref.xml
doc/flatpak-flatpakrepo.xml
doc/flatpak-install.xml
doc/flatpak-remote-add.xml

Add a man page with details about this file format: flatpak-flatpakref.5

Document the flatpakref file format

---

app/flatpak-builtins-ls-remote.c

This helps with consistent formatting.

Port remote-ls to FlatpakTablePrinter

---

doc/flatpak.xml

This is interesting information for distributors.

Document how remotes can be preconfigured

---

flatpak-docs.html
reference/html/FlatpakInstallation.html
reference/html/flatpak-Version-information.html
reference/html/flatpak.devhelp2
reference/html/full-api-index.html
reference/html/index.html

Just locally built the html and copied it here...

Update documentation to 0.6.13

---

common/flatpak-dir.c
tests/testlibrary.c

Add the unit tests plus a small refactor on flatpak-dir.c, so that we can easily mock the config location of those files normally under `/etc/flatpak/installations.d`, for testing.

Add new unit tests for the multiple installations feature

---

po/LINGUAS
po/ru.po

This mostly translated (86% btw) po file

ru translations file

---

common/flatpak-dir.c

In extract_extra_data(), flatpak currently returns TRUE whenever
flatpak_repo_get_extra_data_sources() returns NULL, which is correct
most of the times since that's usually caused by the extra-data
finish-args argument not being present.
However, that operation relies on OSTree's ostree_repo_load_variant()
too, which could fail for unrelated reasons. And in those cases flatpak
would still keep returning TRUE here even in cases where the extra-data
sources could be there, but an error happened while retrieving it.
This seems to be a bug leading to unlikely -yet possible- situations,
where the user would end up with an "external app" like Spotify reported
to be succesfully installed but without the files/extra directory, which
is useless.

Don't ignore OSTree errors when fetching the extra-data sources

---

common/flatpak-run.c

On unmonitored systems (if the session helper is not available), we
currently decide whether to create a symlink or a read-only bind mount
for /etc/localtime based on whether that's a symlink in the host or
not, but we don't check whether that symlink would be reachable in
the sandboxed environment, which might lead to bad situations.
This patch adds some extra checks relying on GFile's API to check
whether that symlink would be reachable before making the final
decision: if it's not, then do a bind mount despite of the file
being a symlink in the host.
#409

 Check if symlink target for /etc/localtime exists in the runtime

---

builder/builder-source-archive.c
builder/builder-source-file.c
common/flatpak-dir.c
common/flatpak-utils.c
lib/flatpak-installation.c

Fixes https://github.com/flatpak/flatpak/issues/558

Fix progress when downloading extra files using the public API

---

po/ru.po

Update russian translation for master branch

Update russian translation

---

common/flatpak-run.c

At the moment, flatpak applications are only given FamilyLocal family
xauth cookies from the Xauthority file.  This is so, the sandboxed
application doesn't inadvertently get access to displays on other
computers.
But FamilyLocal isn't the only xauth family that's local.  FamilyWild
entries can be local as well.
Furthermore, FamilyWild entries are preferable to FamilyLocal entries
when found, because they don't break if the system hostname is changed.
This commit makes FamilyWild xauth entries get propagated in the same
way as their FamilyLocal counterparts.

run: propagate wildcard xauth entries to app bundle

---

common/flatpak-dir.c
lib/flatpak-installation.c

Fixes the issue described in flatpak/flatpak#609

Improve progress report

---

lib/flatpak-installation.c

Fixing a stray comment after flatpak/flatpak#609 fixes landed

Fix comment

---

builder/builder-module.c
builder/builder-source-shell.c
common/flatpak-dir.c
common/flatpak-utils.c

* Use realpath instead of canonicalize_file_name
* Add missing include

Fix some issues with musl

---

app/flatpak-builtins-update.c
po/cs.po
po/de.po
po/hu.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sk.po
po/sv.po
po/uk.po

Fix typo in translatable string

---

po/cs.po
po/de.po
po/hu.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sk.po
po/sv.po
po/uk.po

Proper fix this time. Sorry for the previous broken PR.

Fix typo in pofiles and update Czech translation

---

.gitignore
Makefile.am
app/flatpak-builtins-build-bundle.c
builder/builder-utils.c
common/flatpak-dir.c
common/flatpak-run.c
common/flatpak-utils.c
common/flatpak-utils.h
configure.ac
lib/flatpak-installed-ref.c
lib/flatpak-related-ref.c
m4/attributes.m4

Depends: https://github.com/flatpak/flatpak/pull/652

Import ostree warnings

---

common/flatpak-utils.h

See: https://github.com/ostreedev/ostree/pull/756

utils: Prepare for libostree 2017.4 defining autocleanups

---

builder/builder-manifest.c

The Icon= field inside desktop files is translatable, so rename all the
translated versions if the translation matches the untranslated icon
name.

builder-manifest: Rename localized icon fields as well

---

app/Makefile.am.inc
app/flatpak-builtins-repo.c
app/flatpak-builtins.h
app/flatpak-main.c
doc/Makefile.am
doc/flatpak-repo.xml

Add a nascent repo command

---

doc/flatpak-metadata.xml

Document the ExtensionOf and Extra Data groups.

More metadata docs

---

app/flatpak-builtins-list-remotes.c
app/flatpak-builtins-list.c
app/flatpak-builtins-ls-remote.c
app/flatpak-builtins-repo.c
app/flatpak-main.c
common/flatpak-table-printer.c
common/flatpak-table-printer.h
common/flatpak-utils.c
common/flatpak-utils.h
document-portal/xdp-main.c
permission-store/permission-store.c

Column titles, and decimal alignment where appropriate.

Nicer output

---

app/flatpak-builtins-info.c
doc/flatpak-info.xml

Emit more information, and format it in a better way.

Improve info output

---

app/flatpak-builtins-info.c

Make sure that info prints at least the same amount of
information as list -d.

info: Print some more information

---

app/flatpak-builtins-repo.c

This seems useful, at least it shows that a key is there.

repo: Print out gpg key hash too

---

po/hu.po

Hi @alexlarsson 
Here is the updated Hungarian translation for branch flatpak-0.8.x.

[flatpak-0.8.x] Updated Hungarian translation

---

po/hu.po

Hi @alexlarsson 
Here is the updated Hungarian translation for branch master.

[master] Updated Hungarian translation

---

builder/builder-post-process.c
common/flatpak-oci-registry.c

I think the new tmpfile here is a lot better.

Bump libglnx, port to new tmpfile API

---

po/LINGUAS
po/tr.po

by GNOME Turkish Translation Team
Signed-off-by: Muhammet Kara <muhammetk@gmail.com>

Added Turkish translation

---

data/org.freedesktop.portal.Documents.xml

Add some missing newlines, and document that
AddFull was added in version 2.

Small documentation improvements

---

app/flatpak-builtins-build-export.c

This canonicalizes the file modes for directories to 0755, and
for files to 0755 for executables or 0644 otherwise.
This means we never get files/dirs writable by non-root in the
system repo, and we never get setuid/setgid/sticky-bit, all
which could potentially be a problem if we store them in the
system repo.
See https://github.com/flatpak/flatpak/pull/837 for some discussion
about this.

build-export: Canonicalize file permissions

---

common/flatpak-dir.c

We need to re-create the cache repo if it has not been previously
configured as the expected mode (default to bare-user), so it avoids
permissions related issues.

Re-create the cache repo if it is not the expected mode

---

doc/flatpak-remote-ls.xml

Fix example

---

app/flatpak-builtins-ls-remote.c
common/flatpak-dir.c
common/flatpak-dir.h

More bits and bobs of refactoring prior to the LAN and USB stuff being submitted.

LAN and USB preparatory refactoring

---

app/flatpak-builtins-add-remote.c

Updating the metadata at the end of adding a remote means that it fails
if we're offline, even if we have the .flatpakrepo file available.
Unlike the other error cases in the process, which mean the operation
really has messed up, the remote is actually usable even if the
metadata update fails, because future operations will grab the
summary and any new metadata - so we should change this to a warning
to allow the operation to succeed when we're offline.
https://github.com/flatpak/flatpak/issues/917

allow remote add to succeed when offline

---

tests/testlibrary.c

- Replace `if (g_test_verbose ()) g_print("...\n")` with
`g_test_message ("...")`, which prints the message if the test is
either verbose or in TAP mode. Otherwise, post-mortem debugging
of failing tests on an autobuilder is very difficult.
In some cases, since commit f1dbe9bc "tests: Print spawned program
argv in testlibrary" we already had the g_test_message(), but
still had the redundant g_print() too.
- Factor out running a subprocess into a helper function to reduce
duplication.
- Capture invoked subprocesses' stderr and stdout where possible, so we
can log it as diagnostics. Again, this should make it easier to carry
out post-mortem debugging based on autobuilder logs.
Signed-off-by: Simon McVittie <smcv@collabora.com>

Improve test diagnostics

---

app/flatpak-builtins-ls-remote.c

Show update-able apps/runtimes but dont download or install

---

po/sv.po

Swedish translation - fixed minor typos after review

---

common/flatpak-dir.c

In case the summary file is GPG-signed, we already have other better
ways of verifying expectations around the installed ref.
If the deployed branch does not match xa.ref, simply warn instead of
aborting.
Based on a patch by Dan Nicholson <nicholson@endlessm.com>

dir: relax requirements around xa.ref matching deployed commit

---

po/LINGUAS
po/es_ES.po

Spanish translation based on the standards defined by RAE (Real Academia Española, Royal Spanish Academy). I have marked it as es_ES because may differ from some Latin-American dialects, but is the facto standard in Spain.

Spanish translation added

---

po/LINGUAS

Fix Spanish in LINGUAS as well

---

app/flatpak-builtins-build-finish.c
doc/flatpak-build-finish.xml

This lets you set the priority of the extension.

build-finish: Add --extension-priority option

---

app/flatpak-builtins-update.c
doc/flatpak-update.xml

This is especially useful since we now have flatpak search which uses
this data.

Update appstream data on "flatpak update"

---

po/sv.po

Again, an update to the Swedish Translation.

Updated Swedish Translation

---

po/id.po

update Indonesian translation

---

lib/flatpak-installation.c
lib/flatpak-installed-ref-private.h
lib/flatpak-installed-ref.c
lib/flatpak-installed-ref.h
lib/flatpak-remote-ref.c

This matches the API for FlatpakRemoteRefs

Support EOL for installed refs in libflatpak

---

common/flatpak-context.c

This fixes https://github.com/flatpak/flatpak/issues/1617

dir: Fix saving of features in metadata

---

app/flatpak-builtins-build.c

When building a runtime extension we still want to allow other
extensions to be used.
This fixes https://github.com/flatpak/flatpak-builder/issues/156

build: Respect extensions when building an extension

---

common/flatpak-run.c

When allocating an instance id we create a unique directory
in $XDG_RUN_DIR/.flatpak/$id and create a .ref file in it which
we then read-lock (with F_SETLK). This lock is also taken by
the bwrap pid 1, so it will be taken for as long as the
app lives.
To clean up old is we remove any directories where we can successfully
write-lock the .ref file. As long as the sandbox lives this should
make it safe against removal.
However, there is a tiny race in the sandbox setup between the inital
O_CREAT of the .ref file and the F_SETLK fcntl. A GC at this point
may find the .ref file existing but not locked and then remove the
directory.
We work around this by only trying to lock .ref files that are more
than 3 seconds old.

Fix lock in instance id creation

---

po/pl.po

Please also cherry-pick to `master`.

Update Polish translation 181007

---

common/flatpak-transaction.c

Fix a typo

---

common/flatpak-transaction.c

Found while writing transaction tests.

Local error

---

app/Makefile.am.inc
app/flatpak-builtins-history.c
app/flatpak-builtins.h
app/flatpak-main.c
common/Makefile.am.inc
common/flatpak-dir-private.h
common/flatpak-dir.c
common/flatpak-utils-private.h
configure.ac
doc/Makefile.am
doc/flatpak-docs.xml.in
doc/flatpak-history.xml
doc/flatpak.xml
system-helper/flatpak-system-helper.c

Add some information about transaction results to the systemd journal.

Logging and history

---

Makefile.am
app/flatpak-builtins-build-finish.c
app/flatpak-cli-transaction.c
common/flatpak-context-private.h
common/flatpak-context.c
common/flatpak-dir.c
common/flatpak-installation.c
common/flatpak-remote.c
common/flatpak-run.c
common/flatpak-transaction.c
common/flatpak-transaction.h
common/flatpak-utils-private.h
common/flatpak-utils.c
configure.ac
doc/flatpak-build-finish.xml
session-helper/flatpak-session-helper.c

These are some backports from master that we should backport for a 1.0.4 release.

Flatpak 1.0.x backports

---

tests/test-run.sh

I had a report of (and old version of) flatpak stopping
an entire "flatpak update" because one app had a new required
version. This adds a test of this (and it seems fixed now).

tests: Add a test for multi-updates and required version

---

po/pl.po

Please also cherry-pick to `master`.

Update Polish translation 181028

---

common/flatpak-dir.c
common/flatpak-remote.c

Improve validation of remote and installation names.

Name validation

---

common/flatpak-dir.c

Fix build with clang

---

common/flatpak-installed-ref.c

There were a few small copy-paste errors.

Improve appdata getter docs

---

app/flatpak-complete.c

Add completion for --installation=

---

app/flatpak-builtins-install.c
app/flatpak-builtins-uninstall.c
tests/test-basic.sh

This makes more sense.
Closes: #2505

uninstall: Look through all installations

---

icon-validator/validate-icon.c

I meant to allow 16 as a size limit.

icon validator: Fix an off-by-one

---

selinux/Makefile.am.inc

...by moving everything selinux specific into the scope of the
if.

Avoid installing empty dirs with --disable-selinux-module

---

.github/workflows/check.yml

But, only to a limited subset of branches

Trigger CI on pull_request too

---

.github/workflows/check.yml
.gitignore
common/flatpak-context-private.h
common/flatpak-context.c
common/flatpak-dir-private.h
common/flatpak-dir.c
common/flatpak-installation-private.h
common/flatpak-installation.c
data/org.freedesktop.portal.Flatpak.xml
portal/Makefile.am.inc
portal/flatpak-portal.c
portal/org.freedesktop.portal.Flatpak.service.in
portal/portal-impl.c
portal/portal-impl.h
tests/Makefile-test-matrix.am.inc
tests/Makefile.am.inc
tests/libtest.sh
tests/make-test-app.sh
tests/make-test-runtime.sh
tests/org.freedesktop.impl.portal.desktop.test.service.in
tests/test-extensions.sh
tests/test-portal-impl.c
tests/test-update-portal.c
tests/test-update-portal.sh
tests/test.portal.in

Add update monitoring and self-update functionality to the flatpak portal.

portal: Add updates monitoring

---

common/flatpak-dir.c

Rather than unlinking and symlinking the new value we symling into
a temporary name and then atomically renames on top of the (possibly)
pre-existing file.
This has two advantages. First it is atomic, whereas the previous code
could end up removing the old code without creating the new one, and
secondly this will generate a move inotify event which is what dbus-broker
uses to detect changes in the services file directory.
Fixes https://github.com/flatpak/flatpak/issues/3145

Fix detection of exported dbus-services with dbus-broker

---

.github/workflows/check.yml
common/flatpak-error.h
common/flatpak-utils.c
system-helper/org.freedesktop.Flatpak.policy.in

Fixups following the merger of #2797.

Parental controls fixups

---

tests/http-utils-test-server.py
tests/oci-registry-client.py
tests/oci-registry-server.py
tests/test-http-utils.sh
tests/test-oci-registry.sh
tests/test-webserver.sh

Python2 is pretty much dead, lets make us only use python3.

tests: Convert all tests to python3

---

.gitignore

Please forgive the brevity of this commit message but I can't think of
anything more useful to say.

.gitignore: flatpak-permission-dbus.[ch]

---

app/flatpak-cli-transaction.c

Otherwise, it is not clear what changes the question below
the table refers to.
Fixes: https://github.com/flatpak/flatpak/issues/3075

install: Always show the op column

---

app/flatpak-builtins-permission-remove.c
data/org.freedesktop.impl.portal.PermissionStore.xml

Use the new DeletePermission method that is added in 
https://github.com/flatpak/xdg-desktop-portal/pull/404

Permission store v2

---

common/flatpak-dir.c

Make it clear which refs we delete and why, per the discussion here:
https://github.com/endlessm/flatpak/pull/200#discussion_r350053918

dir: Improve comments about deleting mirror refs

---

README.md

Fix the link to bubblewrap, reword a few things, and
explain a few more components.

README.md: Some updates

---

app/flatpak-builtins-build-commit-from.c
app/flatpak-builtins-kill.c

Don't put a period after an error message. It looks wrong

Error message cosmetics

---

common/flatpak-installation.c

Cache remote state so that each remote is only queried once
for getting its state.
Follow up from https://github.com/flatpak/flatpak/pull/3204#discussion_r349642324

installation: Cache remote states while querying installed refs

---

doc/flatpak-permission-set.xml

This shows how --data formatting works on the commandline.

doc: Add an example for permission-set

---

.github/workflows/check.yml

See:
https://github.community/t5/GitHub-Actions/ubuntu-latest-Apt-repository-list-issues/m-p/41163/highlight/true#M4513

Work around github repo issue

---

.github/workflows/check.yml
common/flatpak-transaction.c
tests/test-auth.sh
tests/test-authenticator.c

This might be useful to the authenticator, and is no cost for us to add.
@pwithnall asked about this on the list.

Pass collection-id (if any) to authenticator when requesting tokens

---

common/flatpak-dir.c

---
Noticed while testing #3307.

dir: Don't leak result of flatpak_get_current_locale_langs()

---

tests/testlibrary.c

---
Noticed while testing #3307.

testlibrary: Fix some leaks in the test itself

---

app/flatpak-builtins-remote-add.c
app/flatpak-builtins-remote-modify.c
common/flatpak-auth.c
doc/flatpak-remote-add.xml
doc/flatpak-remote-modify.xml

This fixes the cli to work with the new format and updates the manpages. Also minor changes to how they are handled (see commits).

Fix handling of authenticator options

---

portal/flatpak-portal.c

Stop polling for updates on metered networks. Allow
overriding this with the new --poll-when-metered
option.
Fixes: https://github.com/flatpak/flatpak/issues/3286

portal: Don't poll for updates on metered networks

---

po/gl.po

The FLOSS galician translators group decided make some changes in the glossary, this PR is to change aplicativo -> aplicación

Update Galician translations

---

common/flatpak-run.c

It is a common user error to prepend many flatpak commands with sudo
and doing so with run is quite unsafe and can cause issues.
This check simply handles the `sudo flatpak run foo` case and does
not prevent running as root or even running in a shell created by
sudo.
See also #1357

run: Prevent accidentally running with sudo

---

po/cs.po

Also update the translation in a stable branch. :-)
/cc @alexlarsson

Update Czech translation [flatpak-1.6.x]

---

app/flatpak-builtins-document-export.c

This adds support for exporting a directory as a document, as
supported by version 4 of the portal:
https://github.com/flatpak/xdg-desktop-portal/pull/447
Note: Don't merge until the portal side is merged

document-export: Support exporting directories

---

common/flatpak-transaction.c

I assume this isn't meant to be user-facing.

transaction: Remove a stray debugging message

---

common/flatpak-installation.c
common/flatpak-installation.h
common/test-lib.c
doc/reference/libflatpak-docs.xml
tests/testlibrary.c

* installation: Fix typos in deprecations
* installation: Formally deprecate deprecated methods

Really deprecate functions deprecated in 102c710b

---

.github/workflows/check.yml
common/flatpak-dir.c
common/flatpak-oci-registry.c
common/flatpak-run.c
common/flatpak-utils-http.c
oci-authenticator/flatpak-oci-authenticator.c
tests/libtest.sh
tests/test-repo.sh

I want to do a release with the progress fix, but these are some additional useful backports.

1.6.3 backports

---

Makefile.am
completion/flatpak.fish

This should work with at least fish 3.0, not sure for earlier versions.

Add fish shell completion

---

app/flatpak-quiet-transaction.c

Currently when you create a FlatpakQuietTransaction object using a
FlatpakDir, the dir will have no_interaction set to TRUE even after the
transaction runs. I don't think it makes sense to have a side effect
like that, and it causes the remote-delete command to fail in the case
where it has to uninstall things. So, restore the old no_interaction
value during destruction of the FlatpakQuietTransaction.
Fixes https://github.com/flatpak/flatpak/issues/3140

quiet-transaction: Remove side-effect on no-interaction

---

app/flatpak-builtins-uninstall.c
tests/test-repo.sh

Possible solution for issue #3513. it's my first collaboration, please say me if need modify anything

issue #3513

---

common/flatpak-dir.c

In the implementation of flatpak_deploy_data_get_string() and a few
other getters, we borrow a value from a GVariant that is a child of the
main GVariant, and free the child via g_autoptr(). Since we then no
longer hold a reference to the child variant, if it is freed internally
in GLib, the borrowed value is no longer safe to access. And GLib frees
all children of a GVariant when serializing it; see the implementation
of g_variant_get_data().
Therefore, in the implementation of the list command the value returned
by flatpak_deploy_data_get_runtime() is not valid after
flatpak_deploy_data_get_origin() is called, and the end result is that
the values in the runtime column of the output are sometimes gibberish.
For the flatpak-1.6.x branch, fix it by ensuring that the GVariant for
deploy …

dir: Fix use-after-free in deploy GVariant code (flatpak-1.6.x branch)

---

app/flatpak-builtins-build-update-repo.c
app/flatpak-builtins-install.c
app/flatpak-builtins-remote-info.c
app/flatpak-builtins-remote-ls.c
app/flatpak-builtins-update.c

Fixes https://github.com/flatpak/flatpak/issues/3546

app: Add translators comments about sideloading

---

common/flatpak-dir.c

dir: set cache directory when creating child repos

---

app/flatpak-main.c

Fixes https://github.com/flatpak/flatpak/issues/3607

app: Make upgrade an alias for update

---

po/zh_TW.po

| key      | value               |
|:--------:|:-------------------:|
| commit | 0c291cf1c9251 |
| untranslated | 3 |
| glossaries | [20/05/17 zh_TW](https://github.com/flatpak/flatpak/files/4640006/glossary-flatpak-zh_Hant.zip) |
| bare diff | [flatpak-5ff2235c-master.zip](https://github.com/flatpak/flatpak/files/4640017/flatpak-5ff2235c-master.zip) |
Thanks!

i18n: zh_TW: update translation

---

app/flatpak-main.c

flatpak enter must not be multi-threaded because it calls setns. This was causing a problem because g_vfs_get_default spawns threads in some environments.
I don't understand well enough the reason for the gvfs workaround to be sure that this does not cause other problems.
Fixes #3646 
Might be relevant to #3406 and #3059.

Fix flatpak enter being multi-threaded and failing

---

common/flatpak-run.c
common/flatpak-utils.c

This is an alternative fix to https://github.com/flatpak/flatpak/pull/3617 which uses temp directories and atomic file operations rather than locks.

Fix ld so race

---

app/flatpak-builtins-create-usb.c
doc/flatpak-create-usb.xml

create-usb: Include partial commits

---

app/flatpak-builtins-enter.c

Sometimes bubblewrap does not create an intermediate user namespace, as one can see with [userns_overview](https://man7.org/tlpi/code/online/dist/namespaces/userns_overview.go.html) for example. For example when there is no `--dev` argument, because it does not need to map the current user to root.
This makes the current flatpak enter implementation fail because it is already in the target ns after the `"base_user"` phase.
As of today, enter would fail for firefox and vlc for this reason (flathub) and this patch seems to fix the problem by detecting that the `base_user` and `user` have the same target namespace.

Fix flatpak enter when bubblewrap does not create an intermediate user namespace

---

common/flatpak-transaction.c

This is just  #3718 for 1.8 branch

 Avoid authentication of no-op updates (1.8)

---

po/LINGUAS
po/ro.po

Adding all the translation work done here: https://l10n.gnome.org/vertimus/flatpak/master/po/ro/
Thanks Florentina Mușat for translation efforts.

Added Romanian Translation.

---

common/flatpak-run.c

Fixes #3722. FWIW this is the main remaining impediment to a Zypak that can use expose-pids, since some Electron Flatpaks do use `--device=all`.

run: Don't use userns2 if same as userns

---

app/flatpak-builtins-run.c

run: Fix --no-session-bus

---

po/cs.po
po/da.po
po/de.po
po/en_GB.po
po/es.po
po/gl.po
po/hr.po
po/hu.po
po/id.po
po/pl.po
po/pt_BR.po
po/ro.po
po/ru.po
po/sk.po
po/sv.po
po/tr.po
po/uk.po
po/zh_TW.po

Fixes https://github.com/flatpak/flatpak/issues/3729

Fix flatpak-1.8.x branch to contain 1.8.1

---

po/uk.po

Tested with "msgfmt -vc" for validity.
Many thanks in advance for merging.

po: Update Ukrainian translation

---

common/flatpak-dir.c

Currently if the user configures a collection ID on a remote which is
incorrect, either because it doesn't match the one configured server
side or because the server doesn't have one configured at all, Flatpak
will not notice the issue and happily still pull from the remote. This
is new since 1.7.1; before that such a problem would be caught because
the server wouldn't provide the ostree-metadata ref for the configured
collection ID.
This commit catches such errors by checking commit metadata, as we
already do for the ref binding metadata. Otherwise such a mismatch would
prevent successful offline distribution of the apps/runtimes provided by
the remote.
The impetus for this is to keep an eos-updater unit test passing with
Flatpak 1.8.x: …

dir: Validate locally configured collection IDs

---

profile/flatpak.csh

Hi,
that is a simple port of the current flatpak.sh forward to tcsh.
Signed-off-by: Werner Fink <werner@suse.de>

Add also support for tcsh users

---

portal/flatpak-portal.c

An interesting side effect of #3770 was that the portal would loop
forever, waiting for a process to come up every 100ms. This isn't really
ideal; of course, *ideally* nothing would hang, but in practice this
can happen in unusual cases, and spamming the logs every 100ms when it
does isn't terribly ideal.
Now, if the process is not running after around 2 seconds, the repeat
timer is changed to a full second. This isn't perfect, but it would help
prevent bizarre problems becoming even more problematic.

portal: Make the SpawnStarted code more robust

---

common/flatpak-dir.c
common/flatpak-transaction.c
doc/flatpak-update.xml
tests/testlibrary.c

These are patches from #3783 which are unrelated to the main topic of that PR.

Miscellaneous fixes

---

.gitignore

These services are all generated at build time.

gitignore: Ignore tests/services

---

app/flatpak-builtins-uninstall.c
common/flatpak-dir-private.h
common/flatpak-dir.c
common/flatpak-installation.c
common/flatpak-ref.c
common/flatpak-ref.h
common/flatpak-transaction.c
portal/flatpak-portal.c
tests/testlibrary.c

Minor fixes

---

app/flatpak-builtins-repair.c

This change makes repair print the current ref number being verified and the total number, that way the user can observe the repair progress. In addition, if fancy output is not disabled, the progress will be cleanly printed on a single line.
On a dry run, this also will still print the delete messages without actually performing the operations, to show what actions would be taken on a non-dry-run.
Demo of how it looks (for testing, I added a `rand()` to adjust the fsck status value to show how errors are handled, I don't actually have any invalid objects :sweat_smile:)

repair: Add basic and "fancy" verify progress

---

po/LINGUAS
po/oc.po

Two changes to add the Occitan language.

i18n: Occitan translation

---

system-helper/flatpak-system-helper.c

Before:
After:
(those are from different computers)

Make app uninstall polkit message friendlier

---

common/flatpak-dir.c

We used to go:
* indexed summary memory cache
* indexed summary fetch
* compat summary memory cache
* compat summary fetch
But now we go:
* indexed summary memory cache
* compat summary memory cache
* indexed summary fetch
* compat summary fetch
This means in the compat case we don't constantly have to fail the
summary fetch before using the memory cache.

remote state: Try loading non-index summary from memory cache before fetching

---

NEWS
tests/libtest.sh
tests/make-test-app.sh
tests/make-test-runtime.sh
tests/test-auth.sh
tests/test-extensions.sh
tests/test-repo.sh
tests/test-run.sh
tests/test-update-remote-configuration.sh

Initial update of the NEWS file for 1.9.1 (although still waiting on an ostree release before it can go out).

Update NEWS for 1.9.1

---

common/flatpak-dir.c

Currently this error is happening on the eos3.9 dev branch of Endless
OS:
Nov 19 12:05:55 endless eos-updater-flatpak-installer[464]:
eos-updater-flatpak-installer: Couldn’t apply some flatpak update
actions for this boot: Error opening directory
'/root/.local/share/flatpak/app': Permission denied
The reason is that we have a check in flatpak_dir_list_unused_refs() to
check if the per-user installation exists and only try to list the refs
there if so, but the existence check falsely succeeds due to the systemd
sandboxing on eos-updater-flatpak-installer.service, and
flatpak_dir_list_refs() then fails in find_used_refs(). Specifically the
ProtectHome=yes systemd service option makes /root inaccessible, and due
to a bug in GLib[1] this makes g_file_query_exists() falsely return TRUE
for any …

dir: Fix spurious permission denied errors

---

common/flatpak-dir.c

This was causing us to never cache the summary in user installations

remote-metadata-update: Don't clean caches if nothing changed

---

common/flatpak-dir.c
common/flatpak-utils.c

Rather than having two static filenames `summary.idx` and `sumary.idx.sig` we have `summary.idx` and `summaries/${SHA256}.idx.sig`, where the checksum is of the main file. This means that during an update there is only a single filename that controls the entire lookup, so there is never a race where only one of two files is updated. This fixes a tiny race in general, but its also much easier to handle caches for this on e.g. a CDN or just in general for cached http servers.
For now we also create the old `summary.idx.sig` file for old 1.9.1. and 1.9.2 clients, but long-term we can just drop them.
This was proposed by @smcv in https://github.com/flatpak/flatpak/issues/3983 and https://github.com/ostreedev/ostree/issues/2250#issuecomment-740701041

New summary format - use a digest-based name for the signature

---

common/flatpak-enum-types.c.template

See:
https://gitlab.gnome.org/GNOME/glib/-/commit/fab561f8d05794329184cd81f9ab9d9d77dcc22a

Fix build with GCC 11

---

common/flatpak-run.c

This brings us closer to matching what happens in libpulse.so.0.
This path is the default for a system-wide PulseAudio instance, which
is discouraged on non-embedded systems but is easy to check for.
In particular, SteamOS, an "appliance"-style gaming OS, uses this
socket.
Adapted from Steam's pressure-vessel container tool, which reuses
various Flatpak modules, including this function.

run: Try using /var/run/pulse/native as PulseAudio socket

---

common/flatpak-run.c

Includes #4057.
* run: Try using /var/run/pulse/native as PulseAudio socket
(See #4057, this is the same commit)
* run: More accurately match PulseAudio's logic for finding its socket
On systems with no XDG_RUNTIME_DIR, PulseAudio falls back to creating
a temporary directory in /tmp, then creating a symlink in
legacy directory ~/.pulse or its more modern replacement ~/.config/pulse.
The symlink is named according to the machine ID, falling back to the
hostname.
Resolves: #4058  
Might-resolve: #2169

run: More accurately match PulseAudio's logic for finding its socket

---

common/flatpak-ref.c

See these links for context on this change:
- https://lists.freedesktop.org/archives/flatpak/2021-January/002087.html
- https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/583#note_1006763

common: Update FlatpakRef docs with respect to uniqueness

---

common/flatpak-run.c

OpenSUSE inherits the hostname value from DHCP without updating its X11
authentication cookie, and it keeps the initial value in
`XAUTHLOCALHOSTNAME`.
To avoid breaking X11 applications, OpenSUSE patches libxcb so that
it also considers the value in `XAUTHLOCALHOSTNAME` as another possible
hostname.
https://bugzilla.opensuse.org/show_bug.cgi?id=262309
To cope with that behavior we need to check `XAUTHLOCALHOSTNAME` too
and, if we have a cookie with that address, propagate it inside the
container adjusting its address to the canonical hostname
`unames.nodename`.
Fixes: #4043

run: Propagate X11 cookies with an address equals to XAUTHLOCALHOSTNAME

---

.github/workflows/check.yml
common/flatpak-bundle-ref.h
common/flatpak-installation.h
common/flatpak-installed-ref.h
common/flatpak-instance.h
common/flatpak-ref.h
common/flatpak-related-ref.h
common/flatpak-remote-ref.h
common/flatpak-remote.h
common/flatpak-transaction.h
tests/testlibrary.c

Backport patches from #4119 and #4106

Backport a couple patches to 1.10.x

---

acinclude.m4
app/Makefile.am.inc
app/parse-datetime.y
configure.ac

Closes: https://github.com/flatpak/flatpak/issues/3487

Fix yacc warnings

---

common/flatpak-utils-http.c

Iterate the `GMainContext` manually instead. This makes the exit
condition from the loop much more obvious, and eliminates the potential
class of problems where `g_main_loop_quit()` is called before
`g_main_loop_run()` and has no effect.

flatpak-utils-http: Don’t use GMainLoop

---

common/flatpak-utils-http.c

This reverts commit c1561b1dedfbf98b2efb842ee66165421ab1422b, which seems to trigger a hang in the `test-oci-registry@system.wrap` test-case.

Revert "flatpak-utils-http: Don’t use GMainLoop"

---

common/flatpak-progress.c
common/flatpak-utils-http.c
common/flatpak-utils-private.h
system-helper/flatpak-system-helper.c

Hopefully this fixes the CI hangs. Mainly it is about handling soup async callbacks in the right thread.

un-revert http GMainlop change and fix hangs in the CI

---

common/flatpak-dir.c

Previously, the polkit query was always interactive, even if the
`FlatpakDir` was operating in non-interactive mode (for example, for a
background update in gnome-software). Make the interactivity match the
interactivity of the `FlatpakDir`.
Do the same for the `mct_manager_get_app_filter()` call, although this
is less important since under normal conditions it will never prompt the
user.
This should hopefully stop polkit prompts appearing periodically when
background updates are being done while logged in as a non-privileged
user with parental controls set to prevent application installation.

flatpak-dir: Make parental controls polkit query interactive iff dir is

---

app/flatpak-builtins-create-usb.c

This is a backport of #4193 to the stable branch.

create-usb: Skip copying extra-data flatpaks (1.10.x backport)

---

common/flatpak-installation.h

flatpak-installation: Fix some typos in documentation comments

---

common/flatpak-run.c

Closes: https://github.com/flatpak/flatpak/issues/3963

Improve error message for sudo flatpak run

---

po/es.po

Translator: Me
Reviewer: Daniel Mustieles

Update Spanish Translation

---

app/flatpak-builtins-repair.c

Issue was shown in this comment:
https://github.com/flatpak/flatpak/issues/3542#issuecomment-917497591

repair: Fix incorrect progress when refs are skipped

---

.github/workflows/check.yml
Makefile.am
common/flatpak-dir.c
configure.ac

This is a backport of the fixes for [CVE-2021-21381](https://github.com/flatpak/flatpak/issues/4146)

[flatpak-1.8.x] Disallow @@ and @@u magic tokens in desktop files

---

app/flatpak-builtins-document-export.c
common/flatpak-dir.c
common/flatpak-utils.c
portal/flatpak-portal.c

This is meant to be applied after https://github.com/flatpak/flatpak/pull/4442

[flatpak-1.8.x] Fix several memory leaks

---

app/flatpak-main.c

Fixes https://github.com/flatpak/flatpak/issues/4036

app: Don't tab-complete on aliases or deprecated

---

app/flatpak-builtins-list.c

The man page states that the --all option for the list command includes
runtime extensions (e.g. that end in .Locale or .Debug) and this is the
case. When --all is omitted, we only show such extensions when the thing
they extend is not already in the list. However when you run a command
like "flatpak list --runtime --columns=application,branch", you get a
list that excludes runtime locale extensions but includes app locale
extensions, since the corresponding apps are not in the list despite
presumably being installed. This doesn't seem like the right behavior,
so tweak the logic so that app locale extensions are excluded when --all
is omitted and --runtime is used.
Strictly speaking the "extension-of" information is not guaranteed to be
present in the deploy data (which acquires it from …

list: Tweak logic for excluding Locale/Debug extensions

---

po/en_GB.po

Several of our users have been reporting this error to me, can never
tell what could be wrong.
Here you can see confused developers trying to see what's going on:
https://bugs.kde.org/show_bug.cgi?id=417078

Do not forget to pass the actual error message

---

po/LINGUAS
po/fr.po

Closes https://github.com/flatpak/flatpak/issues/3437

po: Add French translation

---

app/flatpak-builtins-document-unexport.c
doc/flatpak-document-unexport.xml

Fixes https://github.com/flatpak/flatpak/issues/1897

document-unexport: Implement --doc-id

---

app/flatpak-builtins-build-init.c
app/flatpak-builtins-list.c
app/flatpak-cli-transaction.c
app/flatpak-quiet-transaction.c
common/flatpak-dir-private.h
common/flatpak-dir.c
common/flatpak-installation.c
common/flatpak-transaction.c
common/flatpak-utils-http.c
common/flatpak-utils.c
system-helper/flatpak-system-helper.c
tests/testlibrary.c

[flatpak-1.12.x] More 1.12.x backports

---

tests/Makefile-test-matrix.am.inc
tests/Makefile.am.inc
tests/test-repair.sh

Follow up from https://github.com/flatpak/flatpak/pull/4661#issuecomment-1010242816

[flatpak-1.12.x] Backport repair unit test

---

NEWS
common/flatpak-context-private.h
common/flatpak-context.c
doc/flatpak-build-finish.xml
doc/flatpak-build.xml
doc/flatpak-override.xml
doc/flatpak-run.xml
tests/Makefile.am.inc
tests/test-context.c
tests/test-exports.c
tests/test-override.sh

Similar to #4686. Any wording improvements on that branch should also be made here.

[1.10.x] Backport #4678, prepare NEWS

---

app/flatpak-builtins-history.c
app/flatpak-main.c
common/flatpak-ref-utils-private.h
common/flatpak-utils.c
tests/Makefile-test-matrix.am.inc
tests/Makefile.am.inc
tests/test-history.sh

[flatpak-1.12.x] Backport fixes for history command

---

common/flatpak-dir.c

If during appstream deploy there is an error, the temporary files were not deleted, resulting in leaked files in /var/lib/flatpak/appstream. Over time these could add up to a significant size. In particular this happes if several deploys happen in parallel, because then the final move into place will fail with EEXIST.
This fixes the cleanup of both the temporary directory and the temporary link on any error. In addition, we scan for and delete leftover temporary files older than a day.
Fixes https://github.com/flatpak/flatpak/issues/4735

appstream deploy: Delete old tmpfiles

---

po/pt_BR.po

Is `flatpak-1.12.x` branch receiving translation updates? If yes, please consider this PR; otherwise, you may close this and merge only #4747)
Translated by Matheus (@barbomat) and proofread by me in [Damned Lies](https://l10n.gnome.org/vertimus/flatpak/flatpak-1.12.x/po/pt_BR/).

Update Brazilian Portuguese translation (branch 1.12.x)

---

common/flatpak-utils.c

Looking up the schema recursively fixes false negatives.

Fix reliability of detecting GTK theme

---

icon-validator/validate-icon.c

As discussed here: https://github.com/flatpak/xdg-desktop-portal/pull/696#discussion_r824699621

icon-validator: Write size and format to stdout

---

common/flatpak-dir.c
common/flatpak-utils-private.h
common/flatpak-utils.c

Fixes https://github.com/flatpak/flatpak/issues/4703

Rewrite dynamic launcher entries when an app is renamed

---

po/id.po

This PR updates the Indonesian translation file by:
- Fixing several grammatical errors
- Using more localized terms instead of adopted ones

l10n: update Indonesian translation

---

po/tr.po

This commit updates Turkish translation.

Uptade Turkish translation

---

common/flatpak-remote.c

flatpak-remote: Fix some minor leaks of some property values

---

app/flatpak-builtins-uninstall.c
app/flatpak-cli-transaction.c
common/flatpak-dir-private.h
common/flatpak-dir.c
common/flatpak-utils-private.h
common/flatpak-utils.c

This branch makes various improvements, mostly related to #3531 and #4549

Improve EOL messages and uninstall command

---

portal/flatpak-portal.service.in
session-helper/flatpak-session-helper.service.in

Stop flatpak-session-helper and flatpak-portal when the session ends

---

common/flatpak-run.c

Closes #4297, by locking `modify_ldt` behind `--allow=multiarch`.

Allow the modify_ldt syscall when using multiarch

---

po/cs.po

Cherry-picked from #5052 for the stable branch.

[1.14.x] Update Czech translation

---

common/flatpak-dir.c

This already happens for installs due to the cleanup path in `flatpak_dir_deploy_install()`, but it doesn’t happen for other calls to `flatpak_dir_deploy()`. Notably, during updates of already installed apps.
Specifically, this means that if an app update is cancelled due to being blocked by a parental controls policy, the temp deploy dir for that app (such as
`~/.local/share/flatpak/app/com.corp.App/x86_64/stable/.somehex-XXXXXX`) will be leaked. It will never be automatically cleaned up, as it’s not in `/var/tmp` either.
Fix that by using `glnx_mkdtempat()` to create a scoped temporary directory.
(cherry picked from commit ce1829a703f2bc2e7868fd314ddefb63fbf7dce1)
---
Trivial backport of #5146 to `flatpak-1.14.x`. Tested, and it …

[flatpak-1.14.x] flatpak-dir: Clean up temp deploy dir on failure of flatpak_dir_deploy()

---

app/flatpak-builtins-repair.c

Fixes https://github.com/flatpak/flatpak/issues/5204
(I checked to make sure this fix works)

repair: Fix off-by-one error in fancy output

---

app/flatpak-builtins-build-bundle.c
common/flatpak-dir.c
common/flatpak-installed-ref.c
common/flatpak-utils-private.h
common/flatpak-utils.c

This pr picks up of the work @barthalion has done in #4904 and completes it. It includes the changes that were recommended in the original pr.

Add support for files generated by appstreamcli compose

---

common/flatpak-dir.c

Inspired by the slight mystery of
https://github.com/flatpak/flatpak/issues/5192, this commit adds more debug output to the functions that analyze installations for unused refs. Some of the output is g_debug() (enabled by -vv) and some is g_info() (enabled by -v) since otherwise the output would be too verbose. This should hopefully help debug problems, not only related to the unused refs code but anything involving dependencies.

dir: Add more debug output for unused refs

---

po/LINGUAS
po/nl.po

Adds Dutch translation. It's currently 80% complete and approved by the Dutch GNOME translation team.

Add Dutch translation

---

common/flatpak-dir.c

Closes https://github.com/flatpak/flatpak/issues/5588
Fixes https://github.com/flatpak/flatpak/commit/14c548301c7bd3bd170228c1860ac7fa40c61667

Initialize system locales properly

---

common/flatpak-run.c

Currently if the parental controls check can't connect to the system bus, apps are not allowed to run. However, apps are also allowed to run if the malcontent (or accounts-service) D-Bus services aren't available. Since it's trivial to meet that requirement by starting a temporary dbus-daemon and setting `DBUS_SYSTEM_BUS_ADDRESS` to use it, not being able to access the system bus at all is no less secure.
This primarily affects flatpak running in a container where D-Bus is generally not available.
Fixes: #5076

run: Ignore system bus failures in parental controls check

---

profile/flatpak.sh

Fixes: #5574
Shell scripting isn't my forte, but this seems correct, as suggested by @leio.

profile: Unset temporary variable

---

po/zh_CN.po

Fixed some translations to make it easier to understand, such as using git official translated terms.

i18n: update Chinese simplified translation

---

common/flatpak-locale-utils.c

This restores support for 'mixed' system locales where different locale categories are configured with different languages. AccountsService currently only includes the LC_MESSAGES language from the system locale.
Helps #5497

locale-utils: Always get system locale languages from localed

---

app/flatpak-cli-transaction.c
app/flatpak-quiet-transaction.c

Close https://github.com/flatpak/flatpak/issues/5816
Also reenable leak checking in the test

Fix a memory leak in flatpak-update

---

po/hi.po

Fixes and update for Hindi translation.
Cheers.

Hindi Translation Update

---

po/ka.po

Hello,
Here's update for Georgian translation.
BR, Ekaterine

po: Update Georgian translation

---

tests/test-run.sh

test-run: Make it more obvious that we are setting G_DEBUG empty

---

app/flatpak-builtins-utils.c

Commit f268f4a870292e85173496d689ff05990f81ed87 that changed flatpak_resolve_matching_remotes() to automatically pick the remote if it's the only matching one, missed an opportunity to clean up the rest of the function.
Now that `remote_dir_pairs->len == 1` is handled as a first case, we can drop the old, dead code that handled it differently, and simplify the nested conditionals.

builtin-utils: Remove dead code branch and simplify

---

po/POTFILES.in

See https://github.com/flatpak/flatpak/pull/5620#issuecomment-2426460452

po: Update POTFILES.in for usb

---

NEWS
meson.build
po/cs.po
po/da.po
po/de.po
po/en_GB.po
po/es.po
po/fr.po
po/gl.po
po/hi.po
po/hr.po
po/hu.po
po/id.po
po/ka.po
po/nl.po
po/oc.po
po/pl.po
po/pt.po
po/pt_BR.po
po/ro.po
po/ru.po
po/sk.po
po/sv.po
po/tr.po
po/uk.po
po/zh_CN.po
po/zh_TW.po

Prepare 1.15.11 release

---

common/flatpak-oci-registry.c

Instead of hardcoding /var/tmp when temporarily downloading layer tarballs, support overriding with a FLATPAK_DOWNLOAD_TMPDIR environment variable.
We don't use TMPDIR because the layer tarballs can be very big (in extreme cases like an SDK > 1GB), and TMPDIR is more likely to point to a in-memory tmpfs.

Add a FLATPAK_DOWNLOAD_TMPDIR variable

---

doc/flatpak.xml

Prompted by #6061 which adds a similar environment variable.

doc: Document $FLATPAK_FANCY_OUTPUT

---

doc/flatpak.xml

Based on #6061, please let that one land first (it's a lot more important than this).

Document FLATPAK_TTY_PROGRESS more clearly

---

.github/workflows/check.yml

There should be no other changes required other than the version bump.

ci: Update to actions/upload-artifact@v4

---

common/flatpak-utils-http.c

utils-http: Simplify unclear expression discovered by clang

---

app/flatpak-builtins-permission-reset.c

This reduces the best case (no-op) execution time from ~900 ms to <100 ms on my system.
Closes #5772

permission-reset: Avoid setting unchanged table entries

---

po/LINGUAS
po/bg.po

Originally from https://l10n.gnome.org/vertimus/flatpak/main/po/bg/

Add Bulgarian tranlation

---

common/flatpak-run-dbus.c

In the real at-spi2-core client library, `AT_SPI_BUS_ADDRESS` is treated as higher-precedence than the `AT_SPI_BUS` X11 atom or the `GetAddress()` D-Bus method. Mimic this.
We don't currently implement querying the X11 atom because that would require a libX11 dependency, so leave a comment indicating where it would appear in precedence order.

run-dbus: Don't call GetAddress() if AT_SPI_BUS_ADDRESS is set

---

.github/workflows/check.yml

Use Ubuntu 22.04 for the older check, and 24.04 for the regular ones.

ci: Update Ubuntu versions

---

po/LINGUAS
po/sl.po

Adding Slovenian translation to flatpak.

Add sl (Slovenian) to flatpak

---

common/flatpak-run.c

Use document portal's AddFull interface to forward dirs to sandboxed apps. Requires version 4 of AddFull.
Closes: #4799

run: Add directory forwarding support

---

.github/workflows/check.yml

Avoid doing it manually for each stable branch, and
needing extra steps to create a stable branch.
https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#filter-pattern-cheat-sheet

ci: Use a regex to define the stable branches

---

common/flatpak-context.c

Just a few spacing things pointed out in https://github.com/flatpak/flatpak/pull/6314

formatting(flatpak-context): Fix a few wrong indentations
